.github/workflows/tests.yaml
db/deploy/tables/applications.sql
db/deploy/util_functions/grant_permissions.sql
db/revert/util_functions/grant_permissions.sql
db/sqitch.plan
db/test/grant_permissions_test.sql
db/verify/util_functions/grant_permissions.sql

This PR grants permissions to auth and guest users on the applications table

Grant permissions

---

.github/ISSUE_TEMPLATE/pull-request-template.md

This PR is for a new PR template.

New PR template

---

app/components/Layout.tsx
app/components/StyledGovButton.tsx
app/cypress/integration/index.spec.js
app/lib/theme/widgets/TextAreaWidget.tsx
app/pages/index.tsx
app/tests/components/StyledGovButton.test.tsx
app/tests/pages/index.test.tsx

This PR is to refactor the landing page as per the Figma design
References #25
_(Include any notes you have about this pull request)_

Landing Page

---

.github/workflows/end_to_end.yaml
app/cypress/integration/index.spec.js

Alright looks like this fixed it :crossed_fingers:

fix: workflow yarn issue

---

app/development.json
app/schema/schema.graphql
helm/app/templates/deployment.yaml

This PR is to fix sso-express oidcIssuer for the test deployment

fix: rename namespace env

---

.github/workflows/publish_deploy_image.yaml

Did a test commit here to make sure prod deployment actually works since we can't test this part until we push to main:
https://github.com/bcgov/CONN-CCBC-portal/runs/6730862669
Let me know what you think of the deployment flow ie requiring dev -> test -> prod:
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/2436428713

feat: enable prod ci workflow

---

app/backend/lib/session.ts
app/server.ts
app/test.json

This PR is to investigate why logging in won't work in dev or test

Login investigation

---

app/formSchema/schema.ts

fix: typos

---

.github/actions/app/action.yaml
.github/workflows/publish_deploy_image.yaml
app/components/Form/ApplicationForm.tsx
app/config.js
app/development.json
app/formSchema/schema.ts
app/next.config.js
app/package.json
app/pages/_app.tsx
app/production.json
app/test.json
app/tsconfig.json
app/yarn.lock
helm/app/templates/deployment.yaml
helm/app/values.yaml

This is for #145 feature flagging. Configured growthbook and added individual form page feature flagging. I can walk you through it but you can see how I use the features in ApplicationForm and pass them to the schema where we conditionally render pages.
If you log into growthbook and click features you can see how to toggle them on and off. Seems to require either refreshing the page a few times or opening it in a new browser window and starting the form again before they turn on/off.

145 growthbook

---

app/lib/theme/FormWithTheme.tsx
app/lib/theme/widgets/CheckboxesWidget.tsx
app/lib/theme/widgets/index.ts

Added custom checkboxes widget so we can complete some of the pages required for this sprint.

feat: add checkboxes widget

---

app/components/Layout.tsx
app/formSchema/uiSchema.ts
app/pages/_app.tsx

Not sure what is happening here, everything looks fine locally and the padding for the main div was never touched but I noticed once deployed to dev it disappears. Adding a media query seems to fix it and also looks nicer on mobile.
Dev issue here:
Locally working fine:

fix: add media query for layout padding

---

app/components/FormDiv.tsx
app/components/Layout.tsx

Elliott asked to make the top padding 40px in his review.

refactor: make top padding 40px for page content

---

app/.babelrc
app/package.json
app/pages/_document.tsx
app/yarn.lock

This PR is intended to fix the issues with styled-components not rendering properly on page loads

Fix styled components rendering issues

---

app/components/Form/SuccessBanner.tsx

This PR changes the app number to CCBC-010001

Change ccbc applicaiton number

---

docs/Definition_of_ Ready.md

---
name: Pull Request Template
about: Default pull request template
title: ''
labels: ''
assignees: ''
---
_(Brief description of the pull request.)_
References # \<issue number\>
_(Include any notes you have about this pull request)_

Update Definition_of_ Ready.md

---

app/formSchema/pages/alternateContact.ts
app/formSchema/pages/authorizedContact.ts
app/formSchema/pages/contactInformation.ts
app/formSchema/uiSchema.ts
app/lib/theme/FormWithTheme.tsx
app/lib/theme/widgets/CheckboxWidget.tsx
app/lib/theme/widgets/CheckboxesWidget.tsx
app/lib/theme/widgets/index.ts

This PR is for the Contact information form pages. Includes new custom checkbox widget.
ref #78

78 contact info

---

app/formSchema/pages/declarations.ts
app/formSchema/pages/declarationsSign.ts
app/formSchema/pages/index.ts
app/formSchema/schema.ts
app/formSchema/uiSchema.ts
app/lib/theme/widgets/CheckboxesWidget.tsx
app/lib/theme/widgets/DatePickerWidget.tsx
helm/app/values.yaml

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/90

90 declarations

---

app/formSchema/pages/benefits.ts
app/formSchema/pages/index.ts
app/formSchema/pages/projectPlan.ts
app/formSchema/pages/techSolution.ts
app/formSchema/schema.ts
app/formSchema/uiSchema.ts
app/lib/theme/widgets/DatePickerWidget.tsx
app/lib/theme/widgets/TextAreaWidget.tsx
app/styles/GobalStyles.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/85
Added tech solution, benefits and project planning to form, pages 6/7/8.
Also included a couple bug fixes for the date picker.

85 tech benefits planning

---

app/components/Form/ApplicationForm.tsx
app/components/Review/BudgetDetailsTable.tsx
app/components/Review/OrganizationLocationTable.tsx
app/components/Review/OrganizationProfileTable.tsx
app/components/Review/OtherFundingSourcesTable.tsx
app/components/Review/ProjectAreaTable.tsx
app/components/Review/ProjectFundingTable.tsx
app/components/Review/Review.tsx
app/components/Review/Table.tsx
app/components/Review/index.ts
app/formSchema/pages/declarations.ts
app/formSchema/pages/estimatedProjectEmployment.ts
app/formSchema/pages/index.ts
app/formSchema/pages/organizationProfile.ts
app/formSchema/pages/projectInformation.ts
app/formSchema/pages/review.ts
app/formSchema/pages/supportingDocuments.ts
app/formSchema/pages/templateUploads.ts
app/formSchema/schema.ts
app/formSchema/uiSchema.ts
app/lib/theme/components/FormBorder.tsx
app/lib/theme/widgets/CheckboxWidget.tsx
app/tests/components/Review/Review.test.tsx
app/utils/formatMoney.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/116
This was a pretty big one and includes a refactor for some form pages to make them work better with the review page. I also created a test for the `Review` component that is hydrated with mock data.

116: review page

---

app/formSchema/pages/mapping.ts
app/formSchema/uiSchema.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/303

Add new upload#303

---

app/formSchema/pages/projectPlan.ts
app/formSchema/uiSchema.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/286

Add "Overview project management team" question#286

---

app/lib/theme/widgets/FileWidget.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/267

Bug: Clicking on text on supporting docs & mapping page triggers upload button #267

---

.github/actions/app/action.yaml
helm/app/templates/deployment.yaml

I had a couple of mistakes in my deployment that shouldn't have made it to main. I've opened up an issue to have helm chart linting step in CI in the future.
This has been tested with a test commit that disabled the requirement to push to main that I've since deleted.

fix: deployment yaml formatting error

---

app/components/Form/Label.tsx
app/formSchema/pages/alternateContact.ts
app/formSchema/pages/authorizedContact.ts
app/formSchema/pages/benefits.ts
app/formSchema/pages/contactInformation.ts
app/formSchema/pages/estimatedProjectEmployment.ts
app/formSchema/pages/organizationProfile.ts
app/formSchema/pages/otherFundingSources.ts
app/formSchema/pages/projectFunding.ts
app/formSchema/uiSchema.ts
app/lib/theme/widgets/FileWidget.tsx
app/lib/theme/widgets/MoneyWidget.tsx
app/lib/theme/widgets/NumberWidget.tsx
app/lib/theme/widgets/TextWidget.tsx
app/lib/theme/widgets/index.ts
app/package.json
app/styles/GobalStyles.ts
app/tests/components/Form/MoneyWidget.test.tsx
app/tests/components/Form/NumberWidget.test.tsx
app/tests/components/Form/TextWidget.test.tsx
app/utils/formatPhone.ts
app/yarn.lock

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/291

291 inputs and masks

---

app/formSchema/pages/organizationProfile.ts
app/formSchema/uiSchema.ts
app/lib/theme/widgets/TextWidget.tsx
app/tests/components/Form/TextWidget.test.tsx

This is branched off of PR #316 and just adds a couple of small changes and a test for the email field. 
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/217

217 input constraints

---

app/components/Form/CustomTitles/IndigenousEntity.tsx
app/components/Form/CustomTitles/ProjectBenefits.tsx
app/components/Review/ProjectFundingTable.tsx
app/components/Review/Review.tsx
app/formSchema/pages/alternateContact.ts
app/formSchema/pages/authorizedContact.ts
app/formSchema/pages/benefits.ts
app/formSchema/pages/budgetDetails.ts
app/formSchema/pages/declarations.ts
app/formSchema/pages/declarationsSign.ts
app/formSchema/pages/estimatedProjectEmployment.ts
app/formSchema/pages/existingNetworkCoverage.ts
app/formSchema/pages/mapping.ts
app/formSchema/pages/organizationProfile.ts
app/formSchema/pages/otherFundingSources.ts
app/formSchema/pages/projectArea.ts
app/formSchema/pages/projectFunding.ts
app/formSchema/pages/projectInformation.ts
app/formSchema/pages/projectPlan.ts
app/formSchema/pages/supportingDocuments.ts
app/formSchema/pages/techSolution.ts
app/formSchema/uiSchema.ts
app/tests/components/Review/Review.test.tsx
app/tests/components/Review/mockFormData.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/281

refactor: uppercase defined terms

---

app/formSchema/pages/benefits.ts
app/formSchema/uiSchema.ts

This is branched from #291 and is a small PR to add a new field to the benefits page.
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/260

260 add indigenous field

---

.gitignore
Infrastructure/.terraform.lock.hcl
Infrastructure/README.md
Infrastructure/main.tf
Infrastructure/modules/s3_bucket/main.tf
Infrastructure/variable.tf

Updated Terraform script to provision private s3 bucket

Terraform script to provision s3 bucket

---

app/components/Review/Table.tsx
app/lib/theme/widgets/FileWidget.tsx
app/tests/components/Review/mockFormData.ts

Fix for file widget using proper form id and fix for review page upload fields file names not rendering.

Fix uploads

---

app/components/Form/CustomTitles/ProjectBenefits.tsx
app/formSchema/pages/benefits.ts
app/formSchema/uiSchema.ts

Fix for a couple of things I missed on benefits page.
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/214
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/260

fix: benefits page wording

---

app/__generated__/deleteAttachmentMutation.graphql.ts
app/components/CancelIcon.tsx
app/components/Dashboard/Table.tsx
app/components/index.ts
app/lib/theme/widgets/FileWidget.tsx
app/schema/mutations/attachment/createAttachment.ts
app/schema/mutations/attachment/deleteAttachment.ts
app/schema/schema.graphql
app/styles/GobalStyles.ts
app/tests/components/Form/FileWidget.test.tsx
db/deploy/tables/attachment.sql
db/deploy/trigger_functions/update_timestamps.sql
db/test/unit/tables/table_attachment_test.sql

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/274
Might want to actually test this one whoever is reviewing this. I made it so once the column `is_deleted` is set to true the `deleted_at` and `deleted_by` gets updated using the `update_timestamps` trigger function. Then there is some logic on the front end to remove it from the file from our RJSF field file list.

274 delete uploaded file

---

app/backend/lib/graphql/resolveFileUpload.ts

Fix for uuid not saving in attachment table.

fix: upload uuid

---

app/__generated__/createAttachmentMutation.graphql.ts
app/__generated__/deleteAttachmentMutation.graphql.ts
app/__generated__/getAllApplicationsByOwnerQuery.graphql.ts
app/schema/queries/getAllApplicationsByOwnerQuery.ts

fix: order of dashboard by last updated

---

app/lib/theme/widgets/FileWidget.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/276

feat: soft delete files with replace button

---

app/__generated__/dashboardQuery.graphql.ts
app/components/Dashboard/Table.tsx
app/components/Form/ApplicationForm.tsx
app/components/Review/Table.tsx
app/formSchema/pages/mapping.ts
app/formSchema/pages/supportingDocuments.ts
app/formSchema/pages/templateUploads.ts
app/formSchema/schema.ts
app/formSchema/uiSchema.ts
app/lib/theme/widgets/FileWidget.tsx
app/tests/components/Review/Review.test.tsx
app/utils/bytesToText.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/277

277 - Upload validations

---

app/components/Form/ApplicationForm.tsx
app/components/Form/CalculationForm.tsx
app/components/Form/index.ts
app/formSchema/pages/estimatedProjectEmployment.ts
app/formSchema/uiSchema.ts
app/lib/theme/FieldTemplate.tsx
app/lib/theme/ObjectFieldTemplate.tsx
app/lib/theme/customFieldCalculations.ts
app/lib/theme/widgets/NumberWidget.tsx
app/lib/theme/widgets/ReadOnlyWidget.tsx
app/lib/theme/widgets/index.ts
app/tests/components/Form/CalculationForm.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/262

262 automate calculations

---

app/formSchema/schema.ts

Remove Growthbook feature flags from form schema.
Todo: remove flags in Growbook console once this is merged in.

chore: remove form schema page feature flags

---

app/__generated__/dashboardQuery.graphql.ts
app/pages/dashboard.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/31
This is a small change to list applications on the dashboard by newest created first.

refactor: query applications by newest created

---

.github/actions/app/action.yaml
.github/workflows/publish_deploy_image.yaml
helm/app/templates/_helpers.tpl
helm/app/templates/db-pre-upgrade-job.yaml
helm/app/values-dev.yaml
helm/app/values-test.yaml

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/402
Tested CI here: https://github.com/bcgov/CONN-CCBC-portal/actions/runs/2843025463
Dev is up and running with a clear database: bc-dev.apps.silver.devops.gov.bc.ca

402 - Database schema cleanup

---

app/components/SessionExpiryHandler.tsx

- updated `enabled` flag;
- changed redirect URL to home page;

expiryHandler settings

---

app/formSchema/pages/acknowledgements.ts

@AntBush hey this one is good to go, I wanted you to review it because it might effect your checkboxes PR. I noticed that this one has 17 questions vs 15 from before.

359 - Update acknowledgement checkbox labels

---

app/components/Form/ApplicationForm.tsx
app/components/Form/CalculationForm.tsx
app/formSchema/pages/acknowledgements.ts
app/tests/components/Form/ApplicationForm.test.tsx

Uses the calculated component to expose the internal form state to allow the 'Continue' button to be selectively disabled/enabled based on whether the form fields for the Acknowledgements and Submission page were filled.
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/280

280 required acknowledgement and submission

---

app/components/Form/ApplicationForm.tsx
app/components/Form/CustomTitles.tsx
app/components/LoginForm.tsx
app/components/Review/Table.tsx
app/formSchema/pages/mapping.ts
app/formSchema/pages/otherFundingSources.ts
app/formSchema/pages/projectArea.ts
app/formSchema/pages/projectFunding.ts
app/formSchema/pages/submission.ts
app/formSchema/pages/supportingDocuments.ts
app/formSchema/uiSchema.ts
app/lib/theme/functions/formatDates.ts
app/pages/form/[id]/success.tsx
app/pages/index.tsx
app/tests/components/Form/ApplicationForm.test.tsx
app/tests/components/Review/Review.test.tsx
app/tests/pages/form/success.test.tsx

Wording Updates
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/380
Note that one of the changes will not be implemented, as noted as a comment in the card

380 wording update

---

.github/workflows/deploy_tools_chart.yaml
helm/ccbc-tools/.helmignore
helm/ccbc-tools/Chart.yaml
helm/ccbc-tools/templates/_helpers.tpl
helm/ccbc-tools/templates/deployer/deployerRole.yaml
helm/ccbc-tools/templates/deployer/deployerRoleBinding.yaml
helm/ccbc-tools/templates/deployer/deployerServiceAccount.yaml
helm/ccbc-tools/templates/sysdigteam.yaml
helm/ccbc-tools/values.yaml

Adds a sysdig team object to grant access to sysdig. A GH action deploys the chart to tools automatically

feat: add helm chart for sysdigteam

---

app/formSchema/uiSchema.ts

Removes optional as per issue 464

fix: remove optional on read-only widgets under estimatedPorjectEmployment

---

app/pages/index.tsx

Adds the ISED statement under General Information.

ISED Statement

---

app/server.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/444
This should fix this error, though we should still likely set more max lengths on input fields because I suspect he is pasting in massive amounts of text.

fix: 413 payload too large

---

.github/actions/app/action.yaml
.github/workflows/publish_deploy_image.yaml
.gitignore
helm/app/Chart.lock
helm/app/Chart.yaml
helm/app/templates/routes/secureRoute.yaml
helm/app/values-prod.yaml
helm/app/values.yaml

For #378
Cronjob will need to be manually run

feat: use entrust ssl certs in dev, test, prod

---

helm/app/templates/deployer/deployerRole.yaml

fix: remove double-declared routes and add list verb

---

app/formSchema/uiSchema.ts

Mars asked to make this only accept a single file upload.

set geographic coverage upload to only allow single file

---

app/backend/lib/graphql/authenticationPgSettings.ts
app/backend/lib/sso-middleware.ts
app/pages/dashboard.tsx
app/schema/schema.graphql
db/deploy/functions/session.sql
db/deploy/mutations/create_user_from_session.sql
db/deploy/tables/applications.sql
db/deploy/tables/ccbc_user.sql
db/deploy/trigger_functions/update_timestamps.sql
db/deploy/types/keycloak_jwt.sql
db/test/unit/functions/session_test.sql
db/test/unit/mutations/create_user_from_session_test.sql
db/test/unit/tables/ccbc_guest_test.sql
db/test/unit/tables/ccbc_user_test.sql
db/test/unit/tables/table_applications_access_test.sql
db/test/unit/trigger_functions/update_timestamps_test.sql
db/test/unit/types/keycloak_jwt_test.sql

Started implementing this via the JSON Alec added to 1pass though currently I'm blocked by my lack of IDIR.

296 - migrate keycloak

---

helm/app/values.yaml

fix: turn on the certbot cron

---

.github/workflows/tests.yaml

feat: trivy container scanning

---

.github/workflows/publish_deploy_image.yaml
.github/workflows/tests.yaml

continues #522 to increase sensitivity and integrate with the github security tab
ref #366

feat: tune trivy scanning severity

---

.github/workflows/publish_deploy_image.yaml
.github/workflows/tests.yaml
app/package.json
app/yarn.lock

more static analysis tooling, relates to #146

feat: codeql analysis of typescript/javascript

---

.github/workflows/tests.yaml
app/Dockerfile
db/Dockerfile

an attempt to improve base layer security posture

feat: migrate to ubi9 base image

---

app/components/LoginForm.tsx
app/pages/index.tsx
app/tests/pages/index.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/484

484 landing page updates

---

app/Dockerfile

[confirmed](https://github.com/bcgov/CONN-CCBC-portal/pull/550/checks?check_run_id=8083258999) fixes CVE-2022-29244

npm 8.18.0

---

app/Dockerfile
helm/app/templates/routes/secureRoute.yaml

continues #544 to resolve [failed deploy](https://github.com/bcgov/CONN-CCBC-portal/runs/8083900978)

fix: secureRoute is a value not a function

---

.github/workflows/deploy.yaml
.github/workflows/main.yaml

This should fix our deployment

fix: re-add CI env vars that were lost in refactor

---

app/components/Dashboard/Table.tsx
app/components/Form/ApplicationForm.tsx
app/formSchema/pages/supportingDocuments.ts
app/formSchema/schema.ts
app/formSchema/uiSchema.ts
app/lib/theme/FieldTemplate.tsx
app/lib/theme/widgets/FieldLabel.tsx
app/tests/components/Review/Review.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/454
This PR also reverts the other supporting documents schema back to an object and not a function as that conditional required isn't needed anymore.

454 -  Change Evidence of connectivity speeds upload

---

helm/app/templates/routes/secureRoute.yaml

continues #544 to resolve unbound cert issue by hardcoding route names

fix: hardcode route name to fix broken lookup

---

app/pages/form/[id]/[page].tsx
app/tests/pages/form/[page].test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/381

381 - Add Editing Alert Banner

---

.github/workflows/test-code.yaml

per teams thread about turning off [the bot](https://github.com/cocogitto/cocogitto-bot)

ci: add cocogitto github action

---

app/components/FooterLinks.tsx
app/components/Form/CustomTitles.tsx
app/components/NavbarLinks.tsx
app/components/Review/Table.tsx
app/cypress/integration/index.spec.js
app/formSchema/pages/benefits.ts
app/formSchema/pages/projectArea.ts
app/formSchema/pages/supportingDocuments.ts
app/formSchema/uiSchema.ts
app/lib/theme/FieldTemplate.tsx
app/pages/dashboard.tsx
app/pages/form/[id]/[page].tsx
app/pages/form/[id]/success.tsx
app/pages/index.tsx
app/tests/components/FooterLinks.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/313

313 external links

---

app/components/IntakeAlert.tsx
app/components/index.ts
app/pages/dashboard.tsx
app/pages/index.tsx
app/tests/pages/dashboard.test.tsx
app/tests/pages/index.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/494
The custom `create_application` mutation is being handled in #566 now, I've updated the tickets accordingly.

494 block new applications

---

app/components/Form/CustomTitles.tsx
app/formSchema/pages/coverage.ts

Fixes a wording error that got through and updated the wording slightly as Elliott requested.

fix: coverage page wording error

---

.github/workflows/build.yaml
.github/workflows/test-code.yaml
.github/workflows/test-containers.yaml

I'll concede that I used too many concurrencies

ci: limit concurrency

---

.bin/install-gitleaks-linux-x64.sh
.github/workflows/test-code.yaml
.gitignore

even though this might already be contemplated via pre-commit...

ci: scan for secrets with gitleaks

---

.github/workflows/scorecards.yml

something to consider
https://github.com/ossf/scorecard-action

ci: add ossf scorecards

---

.bin/install-gitleaks-linux-x64.sh
app/lib/theme/customFieldCalculations.ts

- updated calculateEmployment to return two decimal points if needed

fix: FTE field formatting

---

app/cypress/integration/index.spec.js
app/formSchema/pages/otherFundingSources.ts
app/formSchema/pages/projectFunding.ts
app/formSchema/uiSchema/pages/otherFundingSources.ts
app/formSchema/uiSchema/pages/projectFunding.ts
app/tests/components/Review/Review.test.tsx
app/tests/components/Review/mockFormData.ts

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/504
Started a new branch for this rather than deal with merge conflicts from the `uiSchema` refactor.

504 - Move CIB fields to Other Funding Sources Page

---

app/components/Form/ApplicationForm.tsx
app/components/Form/CalculationForm.tsx
app/cypress/integration/index.spec.js
app/formSchema/pages/otherFundingSources.ts
app/formSchema/pages/projectFunding.ts
app/formSchema/uiSchema/pages/otherFundingSources.ts
app/formSchema/uiSchema/pages/projectFunding.ts
app/lib/theme/customFieldCalculations.ts
app/lib/theme/widgets/ReadOnlyMoneyWidget.tsx
app/lib/theme/widgets/index.ts
app/tests/components/Form/CalculationForm.test.tsx
app/tests/components/Form/ReadOnlyMoneyWidget.test.tsx
app/tests/lib/relay/theme/customFieldCalculations.test.tsx

https://app.zenhub.com/workspaces/connectivity-intake-61c0c1204c8bcb001491c5f3/board

450 calculate totals

---

app/components/Form/ApplicationForm.tsx
app/tests/components/Form/ApplicationForm.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/477

feat: acknowledgement and submission page disabled for submitted applications

---

app/components/Layout.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/643

fix: remove 0 from main layout margin

---

app/components/IntakeAlert.tsx
app/tests/components/IntakeAlert.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/648

fix: update date for banner

---

.github/workflows/build.yaml
.github/workflows/cache.yaml
.github/workflows/main.yaml
.github/workflows/nightly.yaml

looks like #638 got closed without a devops resolution; this pr adds the manual fix documented in the closed pr as a manually triggered pipeline workflow

ci: add a manual workflow to clear github actions cache

---

.github/workflows/publish_deploy_image.yaml

Fix for security scan alert regarding CVE-2022-31129

Pass Trivy container scan

---

.github/workflows/publish_deploy_image.yaml

Fix for security scan alert regarding CVE-2022-31129

fix: using main branch

---

db/deploy/mutations/submit_application.sql
db/test/unit/mutations/submit_application_test.sql

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/477
Adds the backend enforcement for acknowledgements

feat: backend validation for acknowledgements

---

docs/process_to_manipulate_data.md

This PR adds a doc for manipulating data in production. Definitely need devs to give their thoughts on any changes and additions to this, thanks.

502 - manipulate data in production

---

app/Dockerfile
helm/app/templates/deployment.yaml

The time travel feature was added, but mock_schema was not deployed, so the time travel does not work in dev and test environments.
This PR fixes the issue.

fix: deploy mock_schema

---

.bin/install-gitleaks-linux-x64.sh

Fixes gitleaks to a specific version

fix(ci): set gitleaks to static version

---

app/formSchema/pages/organizationProfile.ts

Add isIndigenousEntity as required

fix: add required for isIndigenousEntity

---

.github/actions/local-app-run/action.yaml
app/components/Form/ApplicationForm.tsx
app/components/Form/ApplicationFormStatus.tsx
app/cypress/integration/index.spec.js
app/cypress/support/commands.js

Branch to have consistent happo screens

fix: set cookie time

---

app/cypress/integration/index.spec.js
app/lib/theme/widgets/FileWidget.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/708
Removes the internal state and useEffects to update the form

fix: no longer infinite loop on upload pages

---

app/components/Form/CustomTitles.tsx
app/components/NavbarLinks.tsx
app/components/Review/ReviewPageField.tsx
app/cypress/integration/index.spec.js
app/formSchema/pages/benefits.ts
app/formSchema/pages/projectPlan.ts
app/formSchema/pages/supportingDocuments.ts
app/formSchema/uiSchema/pages/projectInformation.ts
app/formSchema/uiSchema/pages/templateUploads.ts
app/tests/components/NavBarLinks.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/597

597 wording updates

---

docs/process_to_manipulate_data.md

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/502
Just some minor updates to the data manipulation process readme.

chore: update data manipulation readme

---

app/components/Form/SubmitButtons.tsx
app/components/FormDiv.tsx
app/components/Layout.tsx
app/components/Stepper.tsx
app/components/index.ts
app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx
app/pages/dashboard.tsx
app/pages/form/[id]/[page].tsx
app/pages/form/[id]/success.tsx
app/styles/GlobalTheme.tsx
app/tests/components/Stepper.test.tsx

https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/467
Settled on a fixed width for the stepper so that we wouldn't get a jumpy effect when changing to pages with longer names. This will probably be a good one to pull down and test locally when reviewing.

467 mvp application stepper

---

app/formSchema/uiSchema/pages/coverage.ts
app/tests/components/Form/FileWidget.test.tsx

feat: change eligibility mapping accepted file type and description

---

app/.eslintrc.js

chore: disable arrow-body-style eslint rule

---

.bin/install-gitleaks-linux-x64.sh

chore: update gitleaks and disable latest version check

---

app/pages/dashboard.tsx
app/tests/pages/dashboard.test.tsx

- feat: dashboard wording updates
- test: add dashboard status wording tests

382 dashboard wording updates

---

app/backend/lib/sso-middleware.ts
app/components/LoginForm.tsx
app/components/NavbarLinks.tsx
app/data/ssoConstants.ts
app/package.json
app/pages/index.tsx
app/styles/GlobalTheme.tsx
app/tests/backend/lib/sso-middleware.test.ts
app/tests/jest-setup.ts
app/tests/pages/index.test.tsx
app/yarn.lock

feat: landing page shows multiple login buttons

---

docs/CONTRIBUTING.md
docs/Team_Agreements.md

Updated Team Agreement and discussion points (marked as [TBD]- to Be Discussed)

feat: updates and comments to team agreement

---

app/components/Form/ApplicationForm.tsx
app/components/Form/SubmitButtons.tsx
app/tests/components/Form/ApplicationForm.test.tsx

Implements missing detail  for disabled submit in #121

feat: submit button is disabled if form is uneditable

---

helm/app/templates/_helpers.tpl
helm/app/templates/cronJobs/receive-applications.yaml
helm/app/templates/deployment.yaml

fix: receive-applications job should run with ccbc_app user

---

app/components/DynamicAlert.tsx
app/components/index.ts
app/package.json
app/pages/dashboard.tsx
app/pages/index.tsx
app/tests/pages/dashboard.test.tsx
app/tests/pages/index.test.tsx

feat: allow changes to banners using Growthbook

---

app/components/Dashboard/Table.tsx
app/components/Form/ApplicationForm.tsx
app/components/Form/Back.tsx
app/components/Form/SubmitButtons.tsx
app/components/Navigation.tsx
app/components/Stepper.tsx
app/cypress.json
app/cypress/integration/index.spec.js
app/cypress/integration/upload.spec.js
app/formSchema/schema.ts
app/lib/theme/widgets/custom/SubmissionCompletedForWidget.tsx
app/next.config.js
app/pages/applicantportal/dashboard.tsx
app/pages/applicantportal/form/[id]/[page].tsx
app/pages/applicantportal/form/[id]/success.tsx
app/pages/applicantportal/index.tsx
app/tests/components/Form/ApplicationForm.test.tsx
app/tests/components/Form/SubmitButtons.test.tsx
app/tests/components/Stepper.test.tsx
app/tests/pages/dashboard.test.tsx
app/tests/pages/form/[page].test.tsx
app/tests/pages/form/success.test.tsx
app/tests/pages/index.test.tsx

26-update-base-url

---

app/backend/lib/createUser.ts
app/pages/analyst/request-access.tsx
app/tests/backend/lib/createUser.test.ts

fix: createUser doesn't get called for unauthorized idirs

---

app/.eslintrc.js
app/components/Form/ApplicationFormStatus.tsx
app/schema/mutations/application/updateFormData.ts
app/tests/components/Form/ApplicationFormStatus.test.tsx

fix: use updatedAt from formData instead of application

---

app/components/Form/ApplicationForm.tsx
app/components/Form/SubmitButtons.tsx
app/schema/mutations/application/updateApplicationForm.ts
app/schema/schema.graphql
app/tests/components/Form/ApplicationForm.test.tsx
db/deploy/mutations/update_application_form.sql
db/revert/mutations/update_application_form.sql
db/sqitch.plan
db/test/unit/mutations/update_application_form_test.sql
db/verify/tables/ccbc_user_001_admin_analyst_permissions.sql

final :crossed_fingers:  fix for #697

fix: setting the submission page fields is done by a custom mutation

---

db/deploy/tables/ccbc_user_001_no_unique_email.sql
db/revert/tables/ccbc_user_001_no_unique_email.sql
db/sqitch.plan
db/test/unit/tables/ccbc_user_test.sql

fix: ccbc_user.email should not be unique

---

app/components/AnalystDashboard/AnalystRow.tsx
app/components/AnalystDashboard/AnalystTable.tsx
app/components/AnalystDashboard/index.tsx
app/cypress/integration/analyst/dashboard.spec.js
app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx
db/data/dev/001_received_applications.sql

feat: analyst dashboard frontend

---

app/components/AnalystDashboard/AnalystRow.tsx
app/cypress/integration/analyst/dashboard.spec.js
app/tests/pages/analyst/dashboard.test.tsx
db/data/dev/001_received_applications.sql
db/data/e2e/001_received_applications.sql
db/data/test/001_received_applications.sql

feat: click on row leads to analyst application page

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.13.0

---

app/.happo.js
app/cypress/integration/analyst/application/[applicationId].spec.js
db/data/e2e/001_application_received.sql

844 - analyst application view e2e screenshot test

---

db/data/dev/001_intake.sql
db/data/test/001_intake.sql
helm/app/templates/_helpers.tpl
helm/app/templates/db-pre-upgrade-job.yaml
helm/app/templates/deployment.yaml
helm/app/values.yaml

- run pre-upgrade job with postgres command
- set role to table owner before inserting dev/test intakes

Fix permissions in dev/test deployment scripts

---

app/schema/schema.graphql
db/deploy/tables/analyst.sql
db/revert/tables/analyst.sql
db/sqitch.plan
db/test/unit/tables/analyst_test.sql

759 list of analysts

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/user-story-template.md

User story template was updated to follow the DoR document and created the "bug report" template.

docs: update issue templates - user story and bug

---

app/components/Analyst/AnalystLayout.tsx
app/components/Analyst/ApplicationHeader.tsx
app/components/Analyst/index.ts
app/cypress/integration/analyst/application/[applicationId].spec.js
app/pages/analyst/application/[applicationId].tsx
app/pages/analyst/application/[applicationId]/assessments.tsx
app/pages/analyst/application/[applicationId]/history.tsx
app/tests/components/Analyst/ApplicationHeader.test.tsx
app/tests/pages/analyst/application/[applicationId].test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments.test.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

826 application header

---

helm/app/templates/cronJobs/receive-applications.yaml

fix: receive-applications cronjob utc/pst schedule

---

app/backend/lib/s3archive.ts
app/tests/utils/getArchivePath.test.tsx
app/utils/getArchivePath.ts

Eslint was complaining that I didn't return anything from async function so I threw a `return res.end()` which prematurely ended the function. Also added missing filenames.

fix: s3archive response

---

CHANGELOG.md
db/sqitch.plan
package.json

Small release fixing review page file upload bug

chore: release v1.16.1

---

db/deploy/tables/analyst_001_update_names.sql
db/revert/tables/analyst_001_update_names.sql
db/sqitch.plan
db/test/unit/tables/analyst_test.sql

Implements # 759
Changes the names as listed by Mars

chore(db): edit names for analysts

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.16.2

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.17.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.18.0

---

.bin/install-gitleaks-linux-x64.sh

chore: update gitleaks to v8.15.2

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.19.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.20.0

---

CHANGELOG.md
db/sqitch.plan
package.json

Release with fix for assessments

chore: release v1.21.0

---

README.md

docs: update release instructions

---

app/package.json
app/yarn.lock

Update dependencies to remove in-test error of qs dependency, and update decode-uri dependency

chore: update dependencies

---

helm/app/templates/hpa.yaml
helm/app/values-prod.yaml
helm/app/values.yaml

Add horizontal pod autoscaler for our deployment.

889 autoscaler

---

CHANGELOG.md
db/sqitch.plan
package.json

Comes with Horizontal Autoscaler and bug fix

chore: release v1.22.0

---

app/pages/applicantportal/index.tsx
app/tests/pages/applicantportal/index.test.tsx

feat: subtract time in intake callout

---

app/backend/lib/graphql/resolveFileUpload.ts
app/backend/lib/s3client.ts
app/config/index.js
app/package.json
app/tests/backend/lib/graphql/resolveFileUpload.test.ts
app/yarn.lock
helm/app/templates/deployment.yaml
helm/app/templates/routes/secureRoute.yaml

s3 upload v3

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.23.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.23.1

---

db/deploy/tables/analyst_002_update_lia_lastname.sql
db/revert/tables/analyst_002_update_lia_lastname.sql
db/sqitch.plan
db/test/unit/tables/analyst_test.sql

chore: update Lia's last name in DB

---

app/components/Analyst/RFI/RFI.tsx
app/components/Analyst/RFI/RfiForm.tsx
app/pages/analyst/application/[applicationId]/rfi/[rfiId]/index.tsx
app/pages/analyst/application/[applicationId]/rfi/index.tsx
app/schema/mutations/application/updateRfi.ts
app/schema/schema.graphql
app/tests/pages/analyst/application/[applicationId]/rfi/[rfiId]/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/index.test.tsx
db/deploy/mutations/update_rfi.sql
db/revert/mutations/update_rfi.sql
db/sqitch.plan
db/test/unit/mutations/update_rfi_test.sql

Implements # 895
While in draft, is branched off of `37-list-rfi`, should be rebased onto master before being put into review

895 edit rfi

---

app/components/Analyst/RFI/RFI.tsx
app/pages/analyst/application/[applicationId]/assessments.tsx
app/pages/analyst/application/[applicationId]/rfi/index.tsx
app/schema/mutations/application/updateRfiJsonData.ts
app/tests/pages/analyst/application/[applicationId]/rfi/index.test.tsx

Adds saving for the email uploads. Also refactored the `RFI` component to use a fragment.

986 save email uploads

---

app/formSchema/analyst/screening.ts
app/formSchema/uiSchema/analyst/screeningUi.ts
app/lib/theme/FieldTemplate.tsx
app/lib/theme/widgets/DatePickerWidget.tsx

Implements # 804
Adds the horizontal line after the date picker and changes "screening" to progress

804-line-and-progress

---

app/lib/theme/widgets/DatePickerWidget.tsx

chore: remove unnecessary option

---

app/components/Analyst/RFI/RfiForm.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/[rfiId]/index.test.tsx

Implements # 895 
Adds the RFI Number on the Edit RFI Page

feat: rfi number on edit rfi page

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.24.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.24.1

---

app/backend/lib/s3archive.ts

fix: wrapped call to getObjectTagging in try/catch

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.24.2

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.25.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.26.0

---

app/backend/lib/s3archive.ts
app/tests/backend/lib/s3archive.test.ts

Implements fix for s3 non-array data

fix: s3-archive-non-array-data

---

CHANGELOG.md
db/sqitch.plan
package.json

Implements S3 archive fix if non-array data

chore: release v1.27.0

---

app/backend/lib/s3archive.ts
app/backend/lib/s3client.ts

feat: add config correctClockSkew to s3client

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.28.0

---

app/lib/theme/functions/formatDates.ts
app/lib/theme/widgets/DatePickerWidget.tsx
app/tests/components/Form/DatePickerWidget.test.tsx

1018 date display

---

app/components/Analyst/ApplicationHeader.tsx
app/components/Analyst/ChangeStatus.tsx
app/components/Analyst/ChangeStatusModal.tsx
app/data/statusColors.ts
app/data/statusStyles.ts
app/schema/mutations/assessment/createApplicationStatus.ts
app/schema/schema.graphql
app/tests/components/Analyst/ChangeStatus.test.tsx
app/tests/pages/analyst/application/[applicationId].test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments.test.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/[rfiId]/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/index.test.tsx
app/tests/utils/mockStatusTypes.ts
db/deploy/tables/application_status_002_change_reason.sql
db/deploy/tables/application_status_type_002_add_types.sql
db/revert/tables/application_status_002_change_reason.sql
db/revert/tables/application_status_type_002_add_types.sql
db/sqitch.plan
db/test/unit/tables/application_status_test.sql

- feat: add column change_reason to application_status table
- feat: add permissions and new status types
- feat: add createApplicationStatus mutation
- feat: add change status menu and modal
- test: add change status tests
- feat: set status pill width
- feat: add rls policies for application_status
- fix: handle change status for withdrawn application

669 view change status

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.29.0

---

helm/ccbc-tools/templates/sysdigteam.yaml

feat: update sysdig team yaml

---

app/backend/lib/s3download.ts
app/components/Form/FormBase.tsx
app/lib/theme/widgets/FileWidget.tsx
app/lib/theme/widgets/GenericModal.tsx
app/tests/backend/lib/s3download.test.ts
app/tests/components/Form/FileWidget.test.tsx

feat: handle single file download

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.30.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.31.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.32.0

---

app/.eslintrc.js

chore: change relay eslint rules

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.33.0

---

app/package.json
app/yarn.lock

chore: convict version bump

---

app/components/Dashboard/Modal.tsx
app/components/Dashboard/Row.tsx
app/components/Dashboard/StatusPill.tsx
app/components/Dashboard/Table.tsx
app/components/Dashboard/index.ts
app/pages/applicantportal/dashboard.tsx
app/tests/pages/applicantportal/dashboard.test.tsx

- feat: add applicant intake column and cleanup dashboard
- test: add applicant dashboard intake column tests
Implements #370

370 intake column

---

app/components/Analyst/Assessments/AssessmentsRow.tsx
app/components/Analyst/StatusPill.tsx
app/formSchema/analyst/financialRisk.ts
app/formSchema/analyst/screening.ts
app/formSchema/analyst/sharedAssessmentFields.ts
app/formSchema/analyst/technical.ts
app/tests/pages/analyst/application/[applicationId]/assessments/financial-risk.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/project-management.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/screening.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/shared-assessments.ts
app/tests/pages/analyst/application/[applicationId]/assessments/technical.test.tsx

- feat: add default radio options for assessments progress and decision
- test: add assessment radio button tests

1097 assessment radio buttons

---

helm/app/templates/PostgresCluster.yaml

chore: update crunchy images to use artifactory

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.34.0

---

app/backend/lib/importJsonSchemasToDb.ts
app/components/Analyst/Assessments/AssessmentsForm.tsx
app/components/Analyst/Assessments/AssessmentsRow.tsx
app/components/Analyst/Assessments/AssessmentsTable.tsx
app/components/Analyst/Assessments/AssessmentsTabs.tsx
app/cypress/integration/analyst/application/[applicationId]/assessments/permitting.js
app/cypress/integration/analyst/application/[applicationId]/assessments/technical.js
app/data/assessmentPillStyles.ts
app/formSchema/analyst/index.ts
app/formSchema/analyst/permitting.ts
app/formSchema/uiSchema/analyst/assessmentsUiSchema.ts
app/pages/analyst/application/[applicationId]/assessments/permitting.tsx
app/tests/backend/lib/importJsonSchemasToDb.test.ts
app/tests/pages/analyst/application/[applicationId]/assessments/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/permitting.test.tsx

feat: add permitting assessment

---

app/backend/lib/login.ts
app/backend/lib/logout.ts
app/backend/lib/session.ts
app/backend/lib/sso-middleware.ts
app/components/LoginForm.tsx
app/components/NavLoginForm.tsx
app/components/Navigation.tsx
app/config/dev.json
app/config/index.js
app/config/local.json
app/config/prod.json
app/config/test.json
app/package.json
app/server.ts
app/tests/backend/lib/login.test.ts
app/tests/backend/lib/logout.test.ts
app/tests/pages/applicantportal/index.test.tsx
app/yarn.lock

feat: add custom logout route

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.35.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.35.1

---

app/config/dev.json
app/config/index.js
app/config/local.json
app/config/prod.json
app/config/test.json

Implements #1043
Configuration fixes

fix: sns topic arn config

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.35.2

---

app/backend/lib/lastIntake.ts
app/backend/lib/s3admin-archive.ts

fix: lastIntake query error

---

app/backend/lib/s3admin-archive.ts
app/backend/lib/s3client.ts
app/tests/backend/lib/requestArchive.test.ts
app/tests/backend/lib/s3client.test.ts

Implements #1043
- use s3 instead of sns due to permission issues

feat: save attachment list in s3

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.36.0

---

app/config/prod.json

fix: prod siteminder logout url

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.37.0

---

app/backend/lib/s3admin-archive.ts
app/backend/lib/s3client.ts
app/components/ButtonLink.tsx
app/jest.config.ts
app/package.json
app/pages/analyst/admin/download-attachments.tsx
app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/admin/download-attachments.test.tsx
app/yarn.lock

1120 dowload attachments

---

helm/ccbc-tools/templates/sysdigteam.yaml

Remove old team memebers from sysdig team.

chore: update sysdig team roles

---

app/package.json
app/sentry.client.config.js
app/sentry.server.config.js
app/yarn.lock

- chore: update sentry/nextjs
- feat: enable sentry performance metrics

sentry performance setup

---

Infrastructure/arc_lambda/index.js
app/backend/lib/attachments.ts
app/tests/backend/lib/attachmentList.test.ts

feat: pass more information about attachments

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.38.0

---

helm/app/values-prod.yaml

chore: update pgbouncer requests in prod

---

Infrastructure/arc_lambda/index.js
app/backend/lib/attachments.ts
app/backend/lib/s3archive.ts
app/backend/lib/s3download.ts
app/tests/backend/lib/attachmentList.test.ts
app/tests/backend/lib/s3archive.test.ts
app/tests/backend/lib/s3download.test.ts

Implements #1021
Fixes based on testing with real data

1021 error logging attachments

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.39.0

---

app/backend/lib/graphql/resolveFileUpload.ts
app/lib/theme/widgets/FileWidget.tsx
app/tests/backend/lib/graphql/resolveFileUpload.test.ts

This PR adds some Sentry custom spans to better track file uploads.

feat: add sentry custom spans for file uploads

---

helm/ccbc-tools/templates/sysdigteam.yaml

Small PR to add myself to the sysdig

chore: add anthony to sysdig yaml

---

app/components/Analyst/ApplicationHeader.tsx
app/components/Analyst/AssignLead.tsx
app/components/Analyst/AssignPackage.tsx
app/components/Analyst/ChangeStatus.tsx
app/tests/components/Analyst/ApplicationHeader.test.tsx

- feat: add labels to application header dropdowns
- test: add tests for application header labels

1128 update application header

---

Infrastructure/arc_lambda/index.js
package.json
yarn.lock

fix: updated text in the file

---

app/server.ts

use sentry to collect pod termination logs

---

helm/ccbc-tools/templates/sysdigteam.yaml

chore: update sysdig team permissions

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.40.0

---

app/pages/analyst/admin/download-attachments.tsx

enable TimeMachine on Download Attachment page

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.41.0

---

app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx

Implements fix for page size on dashboard

fix: add large initial pagesize

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.41.1

---

docs/Data_Dump_With_Pg_Dump.md

Docs for dumping data with pg_dump

docs: add docs to download data with pg_dump

---

CHANGELOG.md
db/sqitch.plan
package.json

Release for upcoming sprint review

chore: release v1.42.0

---

app/cypress/integration/analyst/dashboard.spec.js
app/cypress/integration/applicantportal/dashboard.spec.js
app/cypress/integration/applicantportal/index.spec.js
db/data/dev/001_intake.sql
db/data/dev/002_applications.sql
db/deploy/extensions/audit.sql
helm/app/templates/deployment.yaml
helm/app/values-dev.yaml

Implements #1210
- fixed deployment issue

fix: create extension 

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.43.0

---

app/formSchema/uiSchema/analyst/rfiUiSchema.ts

fix: move multiple file from rfi to FileWidget

---

app/backend/lib/graphql/index.ts

- fix to allow graphiql interface work in dev while using persisted queries for BFF calls

fix: enable graphiql in dev

---

README.md

Started a table of contents and improved some of the development setup documentation. Let me know what I can do to improve this thanks.
I think the one area of this particular ticket that could use some work is the environment variables section. Need to figure out which env vars are absolutely required to start development.

docs: add table of contents and improve project setup documentation

---

app/.postgraphilerc.js
app/backend/lib/graphql/index.ts
app/components/Table/FilterRow.tsx
app/package.json
app/pages/analyst/dashboard.tsx
app/schema/schema.graphql
app/tests/components/Table/FilterRow.test.tsx
app/tests/components/Table/index.test.tsx
app/tests/pages/analyst/dashboard.test.tsx
app/yarn.lock
db/deploy/computed_columns/application_status_sort_filter.sql
db/revert/computed_columns/application_status_sort_filter.sql
db/sqitch.plan
db/test/unit/computed_columns/application_status_sort_filter_test.sql

Implements the basic dashboard filter for #1192. That ticket is very outdated since we decided to go with the built in filters.

1192 dashboard filtering

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.44.0

---

app/components/Admin/AddAnalyst.tsx
app/components/Admin/AnalystList.tsx
app/components/Admin/AnalystListRow.tsx
app/components/Admin/index.tsx
app/pages/analyst/admin/list-of-analysts.tsx
app/schema/mutations/analyst/createAnalyst.ts
app/schema/mutations/analyst/updateAnalyst.ts
app/tests/pages/analyst/admin/list-of-analyst.test.tsx
db/deploy/tables/analyst_003_permissions.sql
db/revert/tables/analyst_003_permissions.sql
db/sqitch.plan
db/test/unit/tables/analyst_test.sql
db/verify/tables/analyst_003_permissions.sql

- feat: add insert and update permissions for analyst table
- feat: add list of analysts to admin dashboard
- feat: add create and update analyst mutations

1039 view and add analysts

---

app/backend/lib/graphql/resolveFileUpload.ts

Implements handler for uncaught exceptions, should prevent pod from crashing

fix: add uncaughtException handler with sentry

---

.github/actions/app/action.yaml
.github/workflows/deploy.yaml
.github/workflows/deploy_load_test.yaml
.github/workflows/main.yaml
app/.env.example
app/backend/lib/readinessTests.ts
app/config/index.js
app/package.json
app/server.ts
app/tests/backend/lib/readinessTests.test.ts
app/yarn.lock
helm/app/templates/deployment.yaml

1170-readiness-check

---

app/components/Analyst/AssignLead.tsx

fix: inactive analyst is shown for select

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.46.0

---

app/pages/analyst/dashboard.tsx

feat: add default sorting from query context

---

app/components/SessionExpiryHandler.tsx
app/pages/_app.tsx

- feat: add on mousedown event to session expiry handler
- fix: add next router to session expiry handler resetOnChange

session expiry

---

app/backend/lib/logout.ts
app/components/Table/index.tsx
app/pages/analyst/dashboard.tsx

feat: save sort order on analyst dashboard

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.47.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.47.1

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryIcon.tsx
app/components/Analyst/History/HistoryRow.tsx
app/components/Analyst/History/HistoryTable.tsx
app/components/Analyst/History/index.ts
app/pages/analyst/application/[applicationId]/history.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
db/deploy/computed_columns/application_history.sql

- feat: add basic history table and icons
- fix: history last child border
- feat: add history content
- feat: add more application history content types

1211 history front end

---

CHANGELOG.md
db/sqitch.plan
package.json

Release for the MVP history page

chore: release v1.48.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.48.1

---

db/data/dev/001_intake.sql

Implements fix for deployment of dev data

fix: add same on conflict as e2e tests

---

app/backend/lib/graphql/resolveFileUpload.ts

After looking at the implementation details of Upload.js, there seems to be an issue with overloading the method in the way I did. 
```javascript
on(event, listener) {
this.uploadEvent = event;
return super.on(event, listener);
}
```
Since the order of the call of `on` uses `uncaughtException`, later the notifyProgress function emits the same event assigned to `uploadEvent`. 
```javascript
__notifyProgress(progress) {
if (this.uploadEvent) {
this.emit(this.uploadEvent, progress);
}
}
```
This reordering should prevent `notifyProgress` here to emit an `uncaughtException` 
I've also added a guard around the caught exception

fix: check if what is passed is error before rethrowing

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.49.0

---

.github/workflows/schemaspy.yaml
README.md
db/deploy/tables/history_item.sql
db/deploy/tables/history_item@1.49.0.sql
db/revert/tables/history_item.sql
db/revert/tables/history_item@1.49.0.sql
db/sqitch.plan

Implements #933
- added GitHub action to generate Schemaspy webpage, commit to `gh-pages` branch and deploy to GitHub pages;
- updated project settings to expose  Schemaspy from  `gh-pages` branch;
- added index to `history_item` utility table to fix Anomaly reported by Schemaspy;
Schemaspy available at https://bcgov.github.io/CONN-CCBC-portal/schemaspy/

933 install schemaspy

---

app/components/NavLoginForm.tsx
app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx

- feat: save and set analyst dashboard scroll position
- feat: clear scroll position session storage on logout

1248 dashboard page position

---

app/components/Analyst/Assessments/AssessmentsForm.tsx

feat: disable submit if form is already saved

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.50.0

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryTable.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

feat: remove all history items before received and reverse history order

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.51.0

---

Infrastructure/arc_lambda/index.js
Infrastructure/file_export.tf
app/backend/lib/s3admin-archive.ts

Implements #1352
- updated Terraform scripts to attach lambda to different bucket;
- updated backend code to save list of attachments to different bucket;

feat: changed bucket for list of attachments

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.52.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.53.0

---

app/cypress/integration/analyst/admin/setup.js
app/cypress/integration/analyst/application/[applicationId].spec.js
app/cypress/integration/analyst/application/[applicationId]/assessments/financial-risk.js
app/cypress/integration/analyst/application/[applicationId]/assessments/permitting.js
app/cypress/integration/analyst/application/[applicationId]/assessments/project-management.js
app/cypress/integration/analyst/application/[applicationId]/assessments/screening.js
app/cypress/integration/analyst/application/[applicationId]/assessments/setup.js
app/cypress/integration/analyst/application/[applicationId]/assessments/technical.js
app/cypress/integration/analyst/dashboard.spec.js
db/data/e2e/001_analyst.sql
db/data/e2e/reset_db.sql

test: add more cypress tests for screenings

---

README.md
db/README.md
docs/Database_Development.md

chore: update database development docs

---

app/pages/analyst/application/[applicationId].tsx

feat: add padding on expand all

---

app/components/Analyst/Assessments/AssessmentsRow.tsx
app/formSchema/analyst/permitting.ts
app/tests/pages/analyst/application/[applicationId]/assessments/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/permitting.test.tsx

feat: add progress options to permitting assessment

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.54.0

---

app/components/Analyst/ChangeStatus.tsx
app/cypress/integration/applicantportal/dashboard.spec.js
db/data/e2e/001_application.sql
db/data/e2e/001_application_received.sql
db/data/e2e/001_fake_status.sql

test: add e2e test for changing the status

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.55.0

---

app/backend/lib/importJsonSchemasToDb.ts
app/components/Analyst/Assessments/AssessmentsForm.tsx
app/components/Analyst/Assessments/AssessmentsTable.tsx
app/components/Analyst/Assessments/AssessmentsTabs.tsx
app/components/Analyst/History/HistoryContent.tsx
app/cypress/integration/analyst/application/[applicationId]/assessments/gis.js
app/formSchema/analyst/gis.ts
app/formSchema/analyst/index.ts
app/formSchema/uiSchema/analyst/assessmentsUiSchema.ts
app/lib/theme/FieldTemplate.tsx
app/lib/theme/components/FieldLabel.tsx
app/lib/theme/widgets/TextAreaWidget.tsx
app/pages/analyst/application/[applicationId]/assessments/gis.tsx
app/schema/mutations/assessment/createAssessment.ts
app/styles/GlobalTheme.tsx
app/tests/backend/lib/importJsonSchemasToDb.test.ts
app/tests/pages/analyst/application/[applicationId]/assessments/gis.test.tsx

feat: add gis assessment page

---

app/pages/analyst/dashboard.tsx

fix: analyst dashboard scroll position when table is sorted

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.56.0

---

helm/ccbc-tools/templates/sysdigteam.yaml

Add Rafael to sysdig team yaml

chore: update sysdig team yaml file

---

app/lib/theme/functions/formatDates.ts
app/lib/theme/widgets/DatePickerWidget.tsx

fix: date display issues

---

app/backend/lib/gis-schema.json
app/backend/lib/gis-upload.ts
app/components/AnalystDashboard/DashboardTabs.tsx
app/package.json
app/pages/analyst/gis.tsx
app/schema/schema.graphql
app/server.ts
app/tests/backend/lib/gis-data-200.json
app/tests/backend/lib/gis-data-400.json
app/tests/backend/lib/gis-data-errors.json
app/tests/backend/lib/gis-upload.test.ts
app/tests/pages/analyst/admin/gis-upload.test.tsx
app/utils/isRouteAuthorized.ts
app/yarn.lock
db/deploy/computed_columns/application_gis_data.sql
db/deploy/mutations/save_gis_data.sql
db/deploy/tables/gis_data.sql
db/deploy/types/gis_data_item.sql
db/revert/computed_columns/application_gis_data.sql
db/revert/mutations/save_gis_data.sql
db/revert/tables/gis_data.sql
db/revert/types/gis_data_item.sql
db/sqitch.plan
db/test/unit/computed_columns/application_gis_data_test.sql
db/test/unit/mutations/save_gis_data_test.sql
db/test/unit/tables/gis_data_test.sql

feat: import GIS analysis data

---

app/lib/theme/widgets/SelectWidget.tsx
app/lib/theme/widgets/custom/AnalystSelectWidget.tsx

Implements #1411 
updated isPlaceholder logic, added more styling

fix: select dropdown showing grey

---

app/backend/lib/CustomHttpsAgent.ts
app/backend/lib/awsCommon.ts
app/package.json
app/tests/backend/lib/CustomHttpsAgent.test.ts
app/yarn.lock

1357 custom request agent

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.57.0

---

app/backend/lib/gis-upload.ts
app/package.json
app/pages/analyst/gis.tsx
app/yarn.lock

Implements #1424
Follow-up on #1400

GIS JSON upload improvements

---

CHANGELOG.md
db/sqitch.plan
package.json

Implements release one more time

chore: release v1.57.2

---

db/data/e2e/001_rfi.sql

Implements fix for spurrious diffs on happo screenshots for the applicant RFI page

fix(test): use mocks for creating rfi

---

app/data/assessmentPillStyles.ts
app/formSchema/analyst/permitting.ts
app/tests/pages/analyst/application/[applicationId]/assessments/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/permitting.test.tsx

feat: change text in permitting assessment

---

CHANGELOG.md
db/sqitch.plan
package.json

Implements # Release for permitting text and RFI ID

chore: release v1.58.0

---

app/backend/lib/gis-upload.ts
app/schema/schema.graphql
app/tests/backend/lib/gis-upload.test.ts
db/deploy/mutations/parse_gis_data.sql
db/deploy/tables/application_gis_data.sql
db/revert/mutations/parse_gis_data.sql
db/revert/tables/application_gis_data.sql
db/sqitch.plan
db/test/unit/tables/application_gis_data_test.sql
db/test/unit/trigger_functions/upsert_archive_trigger_test.sql

1453 GIS Import to use row per CCBC ID

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.59.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.59.1

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.59.2

---

app/package.json
app/yarn.lock

Fixes Dependabot alert 28 https://github.com/bcgov/CONN-CCBC-portal/security/dependabot/28 (weakness CWE-1321)

fix: updated dependency

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.60.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.61.0

---

.github/workflows/main.yaml
db/revert/computed_columns/application_all_assessments.sql
db/revert/computed_columns/application_assessment_form.sql
db/revert/computed_columns/application_assessment_form@1.30.1.sql
db/revert/computed_columns/application_history.sql
db/revert/computed_columns/application_history@1.47.0.sql
db/revert/computed_columns/application_project_name@1.9.0.sql
db/revert/computed_columns/application_rfi.sql
db/revert/computed_columns/form_data_is_editable@1.12.0.sql
db/revert/import/import_once.sql
db/revert/mutations/create_assessment_form.sql
db/revert/mutations/create_new_form_data.sql
db/revert/schemas/private@1.9.0.sql
db/revert/schemas/public@1.9.0.sql
db/revert/tables/application.sql
db/revert/tables/application_form_data.sql
db/revert/tables/application_status.sql
db/revert/tables/application_status_004_archiver_role_permissions.sql
db/revert/tables/form_data.sql
db/revert/tables/history_item.sql
db/revert/tables/history_item_001_add_external_analyst.sql
db/revert/util_functions/grant_permissions.sql
db/revert/util_functions/increment_counter.sql
db/revert/util_functions/upsert_policy.sql
db/revert/util_functions/upsert_timestamp_columns.sql
db/revert/util_functions/verify_grants.sql
helm/app/values-dev.yaml
mocks_schema/revert/schemas/main.sql

1486 fix revert scripts

---

README.md

docs: update pgtap documentation

---

app/schema/schema.graphql
db/deploy/computed_columns/gis_data_counts.sql
db/deploy/mutations/parse_gis_data.sql
db/deploy/mutations/parse_gis_data@1.62.0.sql
db/deploy/types/gis_data_count.sql
db/revert/computed_columns/gis_data_counts.sql
db/revert/mutations/parse_gis_data.sql
db/revert/mutations/parse_gis_data@1.62.0.sql
db/revert/types/gis_data_count.sql
db/revert/types/gis_data_item.sql
db/sqitch.plan
db/test/unit/computed_columns/gis_data_counts_test.sql
db/test/unit/computed_columns/parse_gis_data_test.sql

Implements #1496 
- added type `gis_data_count`;
- updated `parse_gis_data`;
- added function `gis_data_counts(batch_id int)`;
- added and tested revert scripts;
- added tests

feat: GIS History DB only

---

app/pages/analyst/application/[applicationId]/assessments/gis.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/gis.test.tsx

Adds a feature flag for `ApplicationGisData` component.

feat: add show application gis data feature flag

---

app/lib/theme/widgets/DatePickerWidget.tsx

feat: handle datepicker "clear"

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.64.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.65.0

---

app/components/Analyst/Assessments/ApplicationGisData.tsx

fix: separate conditional for gis contesting map and household data

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.65.1

---

.github/workflows/deploy.yaml

Implements part of 1485
The latest release in the codebase was made using this job/action

feat: create github release job on deploy

---

app/schema/schema.graphql
db/deploy/extensions/application_gis_data.sql.sql
db/deploy/import/application_gis_data.sql
db/revert/extensions/application_gis_data.sql.sql
db/revert/import/application_gis_data.sql
db/sqitch.plan
db/test/unit/tables/application_gis_data_test.sql

feat: audit and import on application gis data

---

app/formSchema/uiSchema/analyst/rfiUiSchema.ts

fix: add file type for coverage map

---

CHANGELOG.md
db/sqitch.plan
package.json

Implements release (last time I swear)

chore: release v1.66.0

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.67.0

---

app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx
app/components/Toast.tsx

fix: toast renders on each save

---

docs/auth.md

docs: add documentation for user roles

---

app/components/Analyst/Project/widgets/CcbcIdWidget.tsx

I'm unsure what the purpose of that code I removed here was...and I wrote it 😅 Though it seems to be working great now.

fix: ccbc id widget invisible colour

---

.github/workflows/test-code.yaml

feat: revert ci check

---

app/formSchema/uiSchema/analyst/conditionalApprovalUiSchema.tsx
app/lib/theme/components/FileComponent.tsx
app/lib/theme/widgets/FileWidget.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

feat: change ui element titles and allow multiple

---

app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalModal.tsx
app/lib/theme/widgets/DatePickerWidget.tsx

fix: conditional approval datepicker z-index

---

app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx
app/components/Toast.tsx

Implements # 1529 White text on sucess toast links

feat: change link color to white

---

.github/workflows/main.yaml

fix: release script does not close unrelated PRs

---

app/lib/theme/widgets/DatePickerWidget.tsx

A better z-index fix for the datepicker

---

app/package.json
app/pages/_app.tsx
app/yarn.lock

Implements # 1222
I can't seem to get the chrome plugin to work, and I think it's because CORS is blocking our requests

feat: add snowplow tracking

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.70.0

---

.github/workflows/main.yaml

chore: comment out create-release-pr while it's non-functional

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.71.0

---

app/backend/lib/sow-upload.ts
app/backend/lib/sow_import/summary_tab.ts
app/tests/backend/lib/sow-upload.test.ts

SoW upload : new parameters and basic validation

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.72.0

---

app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalForm.tsx

fix: update relay store on conditional approval save

---

app/components/Analyst/History/HistoryAttachment.tsx
app/components/Analyst/History/HistoryContent.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

feat: show downloadable filename on history

---

app/backend/lib/sow-upload.ts
app/backend/lib/sow_import/tab_8.ts
app/schema/schema.graphql
app/tests/backend/lib/sow_tab_8.test.ts
db/deploy/tables/sow_tab_8.sql
db/revert/tables/sow_tab_8.sql
db/sqitch.plan

1551-Auto-import SoW tab 8

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.73.0

---

app/backend/lib/sow_import/summary_tab.ts

fix: use parseint on application number in summary tab import

---

CHANGELOG.md
db/sqitch.plan
package.json

Had to get in a parseInt fix for application id in the sow api to allow it to work, thought it was coming in another PR.

chore: release v1.73.1

---

.github/workflows/test-code.yaml
app/components/Analyst/History/HistoryAttachment.tsx

fix: eslint workflow throwing errors for ignored lines

---

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/formSchema/analyst/projectInformation.ts
app/tests/components/Analyst/Project/ProjectInformation/widgets/SowImportFileWidget.test.tsx

- chore: update project information form datepicker width
- chore: update project information sow upload description
Just a couple of minor changes Mars asked for.

sow ui updates

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryFile.tsx
app/components/Analyst/History/HistoryRow.tsx
app/components/Analyst/History/HistoryTable.tsx
app/components/DiffTable.tsx
app/components/DownloadLink.tsx
app/formSchema/uiSchema/history/rfi.ts
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
db/deploy/computed_columns/application_history@1.73.0.sql
db/revert/computed_columns/application_history.sql
db/revert/computed_columns/application_history@1.73.0.sql
db/sqitch.plan

feat: history of RFIs

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.74.0

---

README.md

chore: add OpenShift info

---

app/backend/lib/gis-upload.ts

fix: add analyst as authorized for gis upload

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.75.0

---

app/backend/lib/linkPreview.ts

fix: enable link preview for analyst

---

helm/app/templates/routes/secureRoute.yaml
helm/hotfix/templates/routes/secureRoute.yaml

chore: disable haproxy router cookies

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryFile.tsx
app/formSchema/uiSchema/history/projectInformation.ts
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

feat: project information history details

---

app/components/Analyst/ApplicationHeader.tsx
app/components/Analyst/ChangeModal.tsx
app/components/Analyst/ChangeStatus.tsx
app/components/Analyst/ExternalChangeModal.tsx
app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalForm.tsx
app/cypress/integration/applicantportal/dashboard.spec.js
app/data/statusStyles.ts
app/schema/mutations/project/createConditionalApproval.ts
app/tests/components/Analyst/ChangeStatus.test.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx
db/deploy/tables/application_status_type_006_add_new_types.sql
db/revert/tables/application_status_type_006_add_new_types.sql
db/sqitch.plan

Let me know if you can find any bugs thanks!!
Takes care of #1630

1630 update internal external status

---

.github/workflows/test-code.yaml

feat(ci): add test to ensure that no sqitch tags are deleted

---

.tool-versions
README.md
docs/Getting_started_wsl.md

docs: wsl docs for installing and getting started

---

CHANGELOG.md
db/sqitch.plan
package.json

chore: release v1.76.0

---

app/components/Analyst/Project/ProjectInformation/MetabaseLink.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/pages/analyst/gis/[batchId]/success.tsx
app/pages/analyst/gis/index.tsx
app/tests/components/MetabaseLink.test.tsx
app/tests/pages/analyst/admin/gis-upload.test.tsx
app/tests/pages/analyst/gis/[batchId]/success.test.tsx

feat: adding metabase link to gis page

---

app/backend/lib/sow-upload.ts
app/backend/lib/sow_import/summary_tab.ts
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/schema/mutations/project/archiveApplicationSow.ts
app/schema/mutations/project/archiveSowApplication.ts
app/schema/mutations/project/archiveSowTab1.ts
app/schema/mutations/project/archiveSowTab2.ts
app/schema/mutations/project/archiveSowTab7.ts
app/schema/mutations/project/archiveSowTab8.ts
app/schema/mutations/project/createProjectInformation.ts
app/schema/schema.graphql
app/tests/pages/analyst/application/[applicationId]/project.test.tsx
db/deploy/mutations/archive_application_sow.sql
db/deploy/mutations/create_application_sow.sql
db/deploy/tables/sow_grant_update.sql
db/revert/mutations/archive_application_sow.sql
db/revert/mutations/create_application_sow.sql
db/revert/tables/sow_grant_update.sql
db/sqitch.plan

feat: clear project data on no

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryIcon.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
db/deploy/computed_columns/application_history@1.76.0.sql
db/revert/computed_columns/application_history@1.76.0.sql
db/sqitch.plan

feat: add basic history content for change request

---

app/components/Analyst/History/HistoryContent.tsx
app/formSchema/analyst/projectInformation.ts
app/formSchema/analyst/projectInformationReadOnly.ts
app/formSchema/uiSchema/analyst/projectInformationReadOnlyUiSchema.tsx
app/formSchema/uiSchema/analyst/projectInformationUiSchema.ts
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

feat: add sow wireless upload

---

app/backend/lib/s3download.ts
app/components/DownloadLink.tsx
app/components/Review/widgets/FileWidget.tsx
app/tests/pages/analyst/application/[applicationId].test.tsx

feat: make list of attachments downloadable links on review page

---

.github/workflows/main.yaml
.github/workflows/schemaspy.yaml
app/public/data/rfi_data.json
app/schema/schema.graphql
db/deploy/tables/json_data_comments.sql
db/revert/tables/json_data_comments.sql
db/sqitch.plan
meta/ccbc_public.meta.xml

feat: using meta data file to enchance schemaspy docs

---

app/backend/lib/sow_import/tab_7.ts
app/tests/backend/lib/sow_tab_7.test.ts

fix: add missing detailed budget import tab 7

---

app/formSchema/uiSchema/analyst/projectInformationReadOnlyUiSchema.tsx
app/formSchema/uiSchema/analyst/projectInformationUiSchema.ts
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

fix: project information date funding agreement signed label

---

app/components/Analyst/Project/ChangeRequest/ChangeRequestForm.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/components/Analyst/Project/ProjectInformation/widgets/SowImportFileWidget.tsx
app/lib/helpers/sowValidate.ts
app/tests/components/Analyst/Project/ChangeRequest/ChangeRequestForm.test.tsx
app/tests/lib/helpers/sowValidate.test.ts

feat: add validation code to change request form

---

app/pages/_app.tsx

chore: change spm to spt

---

cpanfile

chore: bump cpanm dependencies

---

app/schema/schema.graphql
db/deploy/missing_metadata.sql
db/revert/missing_metadata.sql
db/sqitch.plan

Let me know if there are any descriptions I could improve, thanks!

feat: add missing database table and column descriptions

---

.github/workflows/schemaspy.yaml
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
meta/ccbc_public.meta.xml

1714 sow metabase link

---

app/backend/lib/gis-upload.ts
app/backend/lib/sow-upload.ts
app/lib/helpers/sowValidate.ts

feat: failsafe to prevent filepath error

---

app/lib/theme/FieldTemplate.tsx
app/lib/theme/components/FileComponent.tsx
app/lib/theme/widgets/CheckboxWidget.tsx
app/lib/theme/widgets/CheckboxesWidget.tsx
app/lib/theme/widgets/DatePickerWidget.tsx
app/lib/theme/widgets/MoneyWidget.tsx
app/lib/theme/widgets/NumberWidget.tsx
app/lib/theme/widgets/NumericStringWidget.tsx
app/lib/theme/widgets/RadioWidget.tsx
app/lib/theme/widgets/SelectWidget.tsx
app/lib/theme/widgets/TextAreaWidget.tsx
app/lib/theme/widgets/TextWidget.tsx
app/lib/theme/widgets/UrlWidget.tsx

set margins for inputs to 8px top to separate them, set margin bottom to container div to 16px to separate questions
Implements # 1802

chore: set margins for inputs and questions

---

app/components/Analyst/Project/ProjectInformation/widgets/SowImportFileWidget.tsx
app/lib/helpers/sowValidate.ts
app/lib/theme/components/FileComponent.tsx
app/lib/theme/widgets/FileWidget.tsx
app/pages/analyst/gis/index.tsx
app/tests/components/Analyst/Project/ProjectInformation/widgets/SowImportFileWidget.test.tsx
app/tests/lib/helpers/sowValidate.test.ts
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

Error messages for SOW upload

---

app/components/Analyst/StatusInformationModal.tsx

Quick PR to fix wrong font on modal

fix: status info modal chip font

---

app/components/MetabaseEmbed.tsx
app/pages/analyst/gis/index.tsx

feat: add gis test dashboard link

---

app/components/Analyst/ChangeStatus.tsx
app/cypress/integration/applicantportal/dashboard.spec.js
app/tests/components/Analyst/ChangeStatus.test.tsx
app/tests/pages/analyst/application/[applicationId]/edit/[section].test.tsx

feat: external status reason for change

---

app/components/Analyst/Project/ProjectInformation/ImportErrorMessage.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/components/Analyst/Project/ProjectInformation/ReadOnlyView.tsx
app/components/Analyst/Project/ProjectInformation/widgets/SowImportFileWidget.tsx
app/formSchema/analyst/changeRequest.ts
app/formSchema/analyst/projectInformation.ts
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

Persist sow upload errors

---

helm/app/templates/_helpers.tpl

chore: connect via pgbouncer

---

app/formSchema/uiSchema/analyst/conditionalApprovalReadOnlyUiSchema.tsx

fix: use hidden widget for applicant status sees

---

app/components/Admin/Intake.tsx
app/components/Admin/index.tsx
app/pages/analyst/admin/application-intakes.tsx
app/tests/pages/analyst/admin/application-intakes.test.tsx

- feat: add view intake component
- feat: format intake date time

651 view intake dates

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryFile.tsx

Error found while backlog refinement

fix: add null check for filesArray and check when passing content

---

app/formSchema/pages/organizationProfile.ts
app/formSchema/uiSchema/pages/organizationProfile.ts

chore: move max char limit to under input

---

app/components/Dashboard/Table.tsx

feat: add info tooltip on applicant dashboard

---

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

fix: only show sow import toast when sow file has been uploaded

---

app/formSchema/analyst/changeRequest.ts
app/formSchema/analyst/financialRisk.ts
app/formSchema/analyst/gis.ts
app/formSchema/analyst/permitting.ts
app/formSchema/analyst/screening.ts
app/formSchema/analyst/sharedAssessmentFields.ts
app/formSchema/analyst/technical.ts

chore: make radio buttons agile

---

.github/workflows/test-containers.yaml

chore: update zaproxy action to v.0.5.1

---

.github/workflows/main.yaml
helm/app/Chart.yaml
helm/app/values.yaml

Certbot update

---

app/components/Admin/AddIntake.tsx
app/components/Admin/Intake.tsx
app/pages/analyst/admin/application-intakes.tsx
app/schema/mutations/admin/archiveIntakeMutation.ts
app/schema/schema.graphql
app/tests/pages/analyst/admin/application-intakes.test.tsx
db/deploy/mutations/archive_intake.sql
db/deploy/tables/intake_006_partial_unique.sql
db/revert/mutations/archive_intake.sql
db/revert/tables/intake_006_partial_unique.sql
db/sqitch.plan
db/test/unit/mutations/archive_intake_test.sql

Implements #1124 \<issue number\>

1124 delete future intake

---

app/backend/lib/sow-upload.ts

Fix to allow analysts to upload sow files

fix: allow analyst role to use sow-upload api route

---

app/components/Analyst/Project/ProjectInformation/MetabaseLink.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/pages/analyst/gis/[batchId]/success.tsx
app/tests/components/MetabaseLink.test.tsx
app/tests/pages/analyst/gis/[batchId]/success.test.tsx

- refactor: add test href prop to metabase link component
- feat: add metabase test gis link to gis success page

1901 gis page metabase link

---

app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalObjectFieldTemplate.tsx
app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalReadOnlyTheme.ts
app/components/Analyst/Project/ConditionalApproval/widgets/ReadOnlyRequestedMoneyWidget.tsx
app/components/Analyst/Project/ConditionalApproval/widgets/index.ts
app/formSchema/analyst/conditionalApproval.ts
app/formSchema/uiSchema/analyst/conditionalApprovalReadOnlyUiSchema.tsx
app/formSchema/uiSchema/analyst/conditionalApprovalUiSchema.tsx
app/tests/components/Review/ReviewTheme.ts
app/utils/formatMoney.ts

Add selection deck data into portal

---

app/components/Dashboard/Row.tsx

fix: link and hash conflict

---

app/components/Analyst/Project/ProjectForm.tsx

Implements # 1800 but specifically the bottom margin

fix: remove bottom margin on header

---

app/postgraphile.tags.json5
app/schema/schema.graphql
db/deploy/computed_columns/rfi_data_attachments.sql
db/deploy/functions/extract_uuids.sql
db/revert/computed_columns/rfi_data_attachments.sql
db/revert/functions/extract_uuids.sql
db/sqitch.plan

feat: rfi attachments computed column

---

app/lib/theme/widgets/FileWidget.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/index.test.tsx

feat: save datetime uploaded in file form data

---

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/components/Analyst/Project/CommunityProgressReport/CommunityProgressView.tsx
app/components/Analyst/Project/CommunityProgressReport/index.ts
app/postgraphile.tags.json5
app/schema/mutations/project/createCommunityProgressReport.ts
app/schema/schema.graphql
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx
app/tests/utils/fiscalFormat.test.ts
app/utils/fiscalFormat.ts
db/deploy/mutations/create_application_community_progress_report_data.sql
db/deploy/tables/application_community_progress_report_data_001.sql
db/revert/mutations/create_application_community_progress_report_data.sql
db/revert/tables/application_community_progress_report_data.sql
db/revert/tables/application_community_progress_report_data_001.sql
db/sqitch.plan
db/test/unit/mutations/create_application_community_progress_report_data_test.sql

1955 community progress view

---

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/components/Analyst/Project/ProjectForm.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx

Implements # 1959
Note: you might need to add a "fake" two second timeout to see the spinner as the import is very quick.

Community progress report import spinner and success toast

---

app/lib/theme/components/FileComponent.tsx

fix: big file upload boxes

---

db/sqitch.plan

chore: sqitch plan order

---

.github/actions/app/action.yaml
.github/workflows/deploy.yaml
.github/workflows/main.yaml
README.md
helm/app/Chart.yaml
helm/app/templates/routes/secureRoute.yaml
helm/app/values.yaml

Cert process

---

docs/Tech_Stack.md

docs: update to add toolkit link

---

app/backend/lib/session.ts
app/backend/lib/sso-express/controllers.ts
app/backend/lib/sso-express/helpers.ts
app/tests/backend/lib/sso-express/controllers.test.ts

Login changes

---

docs/Tech_Stack.md

Implements comment from 1263, adds mui to the tech stack

docs: add MUI to tech stack

---

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx

feat: ui does not change when selecting no

---

app/backend/lib/sso-express/helpers.ts

fix: change is auth logic to check refresh token

---

app/lib/theme/components/FileComponent.tsx

feat: display date file received for analyst rfi

---

app/components/Review/widgets/FileWidget.tsx

feat: use received date on summary page

---

app/components/Form/ApplicationForm.tsx
app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx

feat: show errors on submission page

---

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/components/Analyst/Project/ProjectForm.tsx
app/components/Analyst/Project/ProjectTheme.ts
app/components/Analyst/Project/widgets/ContextErrorWidget.tsx
app/components/Analyst/Project/widgets/index.ts
app/formSchema/analyst/communityProgressReport.ts
app/formSchema/uiSchema/analyst/communityProgressReportUiSchema.ts
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

2057 community progress form validation

---

.github/actions/local-app-run/action.yaml
app/components/Analyst/Project/widgets/CcbcIdWidget.tsx
app/config/dev.json
app/cypress/integration/analyst/application/[applicationId]/project.spec.js
app/lib/theme/sharedWidgetStyles.ts

fix: announcement field alignment

---

app/components/Admin/AddIntake.tsx
app/components/Admin/Intake.tsx
app/lib/theme/widgets/DateTimePickerWidget.tsx
app/pages/analyst/admin/application-intakes.tsx
app/postgraphile.tags.json5
app/schema/mutations/admin/updateIntakeMutation.ts
app/schema/schema.graphql
app/tests/pages/analyst/admin/application-intakes.test.tsx
db/deploy/mutations/update_intake.sql
db/revert/mutations/update_intake.sql
db/sqitch.plan
db/test/unit/mutations/update_intake_test.sql

This one got pretty spicy with all the logic for validation on the front end so give it a solid look for me thanks, very open to suggestions to simplify the validation.
Implements #1123

1123 edit intake dates

---

app/components/Analyst/Project/Claims/ClaimsView.tsx
app/tests/components/Analyst/Project/Claims/ClaimsForm.test.tsx

- feat: show claims from year
- test: update claims form test for from date changes
Implements #2162

2162 claims from year

---

lib/backups/create_vault_secrets.sh
lib/backups/extract_all_secrets.sh

chore: secrets and vault scripts

---

app/components/Analyst/Project/ProjectForm.tsx
app/cypress/integration/analyst/application/[applicationId]/project.spec.js
app/formSchema/analyst/claims.ts
app/formSchema/analyst/communityProgressReport.ts
db/data/e2e/001_application.sql

2087 project e2e tests

---

app/backend/lib/claims-upload.ts
app/backend/lib/excel_import/claims.ts
app/components/Analyst/Project/Claims/ClaimsForm.tsx
app/components/Analyst/Project/Claims/ClaimsView.tsx
app/components/Analyst/Project/ProjectInformation/widgets/ExcelImportFileWidget.tsx
app/cypress/integration/analyst/application/[applicationId]/project.spec.js
app/tests/backend/lib/claims-upload.test.ts
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

2161 claim number validation and display

---

app/cypress/integration/analyst/application/[applicationId]/project.spec.js

I think this should fix it, or most of the issues at least 🤞 The buggy diffs look fixed here as I moved the happo screenshots to after each form has been filled but before we click save. 
https://happo.io/a/336/p/1172/compare/8d14f6c79a7d00aa35b996bc06a62133145aceeb/ff21f319301ae5ef0e422bc693b4aef3448cf9cb

test: fix flakey project page tests happo screenshots

---

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx

Metabase link to CPR section

---

app/formSchema/uiSchema/analyst/milestonesUiSchema.ts

Add support for multiple uploads for #2017

feat: allow multiple file uploads for milestones evidence of completion

---

app/components/Analyst/Project/Milestones/MilestonesForm.tsx
app/components/Analyst/Project/Milestones/MilestonesView.tsx
app/schema/mutations/project/archiveApplicationMilestoneData.ts
app/schema/schema.graphql
app/tests/components/Analyst/Project/Milestones/MilestonesForm.test.tsx
db/deploy/mutations/archive_application_milestone_data.sql
db/deploy/tables/application_milestone_data_001.sql
db/revert/mutations/archive_application_milestone_data.sql
db/revert/tables/application_milestone_data_001.sql
db/sqitch.plan
db/test/unit/mutations/archive_application_milestone_data_test.sql
db/test/unit/tables/application_milestone_data_test.sql

2009 delete milestone

---

app/backend/lib/excel_import/milestone.ts
app/components/Analyst/Project/Milestones/MilestonesForm.tsx
app/tests/backend/lib/milestone-upload.test.ts
app/tests/components/Analyst/Project/Milestones/MilestonesForm.test.tsx
db/sqitch.plan

Implements #2014 
Branched off #2009

2014 milestone excel validation

---

app/components/Accordion.tsx
app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx
app/components/Analyst/Project/Claims/ClaimsForm.tsx
app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalForm.tsx
app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalModal.tsx
app/components/Analyst/Project/Milestones/MilestonesForm.tsx
app/components/Analyst/Project/ProjectForm.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/cypress/integration/analyst/application/[applicationId]/project.spec.js
app/pages/analyst/application/[applicationId]/project.tsx
app/schema/mutations/project/createConditionalApproval.ts
app/tests/components/Analyst/Project/Claims/ClaimsForm.test.tsx
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx
app/tests/components/Analyst/Project/ConditionalApproval/ConditionalApprovalForm.test.tsx
app/tests/components/Analyst/Project/Milestones/MilestonesForm.test.tsx
app/tests/components/Analyst/Project/ProjectInformation/ProjectInformationForm.test.ts
app/tests/components/Analyst/Project/ProjectInformation/ProjectInformationFormExcel.test.ts
app/tests/pages/analyst/application/[applicationId]/project.test.tsx
app/tests/utils/projectAccordionValidators.test.ts
app/utils/projectAccordionValidators.ts

Implements #1979
I also did a pretty big refactor of the project page jest tests and moved all of them except for the announcements to their own form tests in their `components` folder. This will make it a lot easier to work with as that file was getting way too large.

1979 project accordion

---

app/components/Form/Label.tsx
app/lib/theme/widgets/MoneyWidget.tsx
app/lib/theme/widgets/NumericStringWidget.tsx
app/lib/theme/widgets/ReadOnlyMoneyWidget.tsx
app/lib/theme/widgets/ReadOnlyWidget.tsx
app/lib/theme/widgets/TextWidget.tsx

chore: add space for helper/error labels

---

app/.env.example
app/backend/lib/sharepoint.ts
app/config/index.js
app/package.json
app/server.ts
app/tests/backend/lib/sharepoint.test.ts
app/yarn.lock

2213 get sharepoint access

---

README.md

docs: growthbook

---

Makefile

chore: add no verify

---

app/package.json
app/yarn.lock

chore: update express session

---

app/backend/lib/sso-express/controllers.ts

Increase the Sentry captures for the login flow as the error seems to be mainly occurring on the auth callback after initial login. Further, delete token if it exists and is expired during login and delete the code challenge until after the initial token is acquired.

chore: increase captures, logic change

---

app/components/Accordion.tsx

Implements # 2283
Tried many solutions as outlined in the MUI style guide, but ultimately landed on using the sx prop.

fix: use sx prop to add styles to accordion

---

app/backend/lib/importJsonSchemasToDb.ts
app/components/Form/ApplicationForm.tsx
app/components/Review/ReviewPageField.tsx
app/components/Stepper.tsx
app/cypress/integration/applicantportal/dashboard.spec.js
app/formSchema/index.ts
app/formSchema/schemaV2.ts
app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx
app/lib/theme/widgets/custom/SubmissionCompletedForWidget.tsx
app/pages/analyst/application/[applicationId]/edit/[section].tsx
app/pages/applicantportal/form/[id]/[page].tsx
app/tests/backend/lib/importJsonSchemasToDb.test.ts
app/tests/components/Form/FileWidget.test.tsx
app/tests/components/Form/ReadOnlySubmissionWidget.test.tsx
app/tests/components/Form/SubmissionCompletedForWidget.test.tsx
app/tests/components/Stepper.test.tsx
app/tests/pages/applicantportal/form/[id]/submission.test.tsx
app/tests/utils/formTestRenderer.tsx
app/utils/getFormPage.ts
app/utils/schemaUtils.ts

400 application question changes in future intake

---

.github/workflows/test-containers.yaml

chore: update owasp image for new version

---

.github/workflows/main.yaml
db/data/dev/002_applications.sql

Fixes dev issue is currently having when inserting the fresh dev data. 
psql:data/dev/002_applications.sql:170: ERROR:  function ccbc_public.submit_application(integer) does not exist

chore: update dev data sql

---

.github/actions/app/action.yaml
.github/workflows/deploy.yaml
.github/workflows/main.yaml
app/backend/lib/excel_import/cbc_project.ts
app/backend/lib/sharepoint.ts
app/postgraphile.tags.json5
app/schema/schema.graphql
app/tests/backend/lib/excel_import/cbc_project.test.ts
app/tests/backend/lib/sharepoint.test.ts
db/deploy/mutations/create_cbc_project.sql
db/deploy/tables/cbc_project.sql
db/revert/mutations/create_cbc_project.sql
db/revert/tables/cbc_project.sql
db/sqitch.plan
db/test/unit/mutations/create_cbc_project_test.sql
db/test/unit/tables/cbc_project_test.sql
helm/app/templates/deployment.yaml
helm/app/values.yaml

2160 upload cbc project spreadsheet

---

.github/actions/app/action.yaml
.github/workflows/main.yaml

Fix deployment app action

---

app/cypress/integration/analyst/dashboard.spec.js
db/deploy/tables/application_002_analyst_can_see_withdrawn.sql
db/revert/tables/application_002_analyst_can_see_withdrawn.sql
db/sqitch.plan

feat: analysts can see withdrawn applications

---

app/components/Analyst/ApplicationHeader.tsx
app/components/Analyst/ChangeStatus.tsx
app/data/statusStyles.ts
db/deploy/tables/application_status_type_007_add_analyst_withdrawn.sql
db/revert/tables/application_status_type_007_add_analyst_withdrawn.sql
db/sqitch.plan

2164 analyst can withdraw applications

---

app/components/Review/ReviewSectionField.tsx
app/pages/analyst/application/[applicationId].tsx

Implements # 926
Forgotten criteria for 926

feat: analysts can't edit form data when withdrawn

---

app/backend/lib/excel_import/template_one.ts
app/backend/lib/excel_import/template_two.ts
app/components/Form/ApplicationForm.tsx

Implements # 1379
Uses the title next to the column rather than the absolute position. Only worry is if that title ever changes

feat: template import uses title to find data

---

cron/sp/app.mjs
helm/app/values.yaml

Update sp auto import cron

---

app/cypress/integration/analyst/application/[applicationId]/project.spec.js

test: add milestone e2e test

---

app/backend/lib/excel_import/cbc_project.ts
app/tests/backend/lib/excel_import/cbc_project.test.ts

fix: cbc_project milestone complete validate number instead of date

---

app/components/Analyst/AssignLead.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/AnalystDashboard/AssessmentLead.tsx
app/components/AnalystDashboard/index.tsx
app/pages/analyst/assessments.tsx
app/pages/analyst/dashboard.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
app/tests/pages/analyst/assessments.test.tsx

2318 assessment assignment table edit

---

.github/workflows/main.yaml
helm/app/values.yaml

1995 reduce bcgov backup storage request to allow restore

---

app/components/Form/ApplicationForm.tsx
app/pages/analyst/application/[applicationId]/edit/[section].tsx

fix: remove other funding sources array data when 'no' is selected

---

app/backend/lib/template-upload.ts
app/components/Analyst/RFI/RFIAnalystUpload.tsx
app/pages/analyst/application/[applicationId].tsx
app/pages/analyst/application/[applicationId]/rfi/[rfiId]/upload.tsx
app/tests/components/Analyst/RFI/RFIAnalystUpload.test.ts

2458 analyst rfi uploads

---

docs/Data_Dump_With_Pg_Dump.md

feat: update command to use oc

---

.github/actions/local-app-run/action.yaml

chore: update growthbook key

---

docs/Moving_Github_Accounts.md

docs: how to transfer the ccbc service account

---

app/pages/applicantportal/dashboard.tsx
app/tests/pages/applicantportal/dashboard.test.tsx

Implements # 2495
Had some trouble with the test I added, if the test is added at the bottom of the file the test was erroring out for me. The wrong return value was being given in the `useFeature` spy.

feat: use feature flag for internal intake

---

docs/Alternate_Applicant_Form_Entry.md

Implements docs update from conversation with Mars

docs: update documentation for transferring owner

---

.github/renovate.json
.github/workflows/main.yaml
.github/workflows/recreate-hotfix.yaml

chore: update ccbc service account email

---

app/components/Analyst/Project/Claims/ClaimsForm.tsx
app/tests/components/Analyst/Project/Claims/ClaimsForm.test.tsx

chore: rename Claims & Progress report

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/AnalystDashboard/AssessmentLead.tsx
app/package.json
app/pages/_app.tsx
app/styles/muiTheme.ts
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
app/tests/pages/analyst/assessments.test.tsx
app/yarn.lock

Implements #2494
Saving table state based off the Material React Table docs example:
https://www.material-react-table.com/docs/guides/state-management

2494 styling of assessment table

---

app/components/Analyst/Project/Milestones/MilestonesForm.tsx

fix: close modal on milestone delete

---

app/cypress/integration/analyst/application/[applicationId]/project.spec.js
app/pages/analyst/application/[applicationId]/project.tsx

- chore: reorder project page accordions
- test: update project page e2e tests for accordion reorder

2329 reorder project page accordions

---

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/formSchema/analyst/communityProgressReport.ts
app/formSchema/uiSchema/analyst/communityProgressReportUiSchema.ts
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx

feat: change text in community progress reports section

---

app/formSchema/analyst/changeRequest.ts
app/formSchema/analyst/milestones.ts

feat: update optionals for change request and milestone

---

app/components/Analyst/NavigationSidebar.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/pages/analyst/dashboard.tsx

feat: remember last visited dashboard

---

app/components/Form/ApplicationForm.tsx
app/formSchema/uiSchema/uiSchemaV2.ts

Implements # 2590 feature flag

feat: add feature flag for hiding benefits

---

app/backend/lib/sso-express/helpers.ts

feat: idle based on longer of refresh and access token

---

README.md
docs/CI_CD.md

1265 doc cicd pipeline

---

README.md

1268 doc metabase

---

README.md

docs: add dev related relay information

---

app/components/Form/ApplicationForm.tsx
app/pages/analyst/application/[applicationId]/edit/[section].tsx

Benefits hh fix

---

app/lib/theme/widgets/FileWidget.tsx

fix: multi delete files (hotfix)

---

app/lib/theme/widgets/FileWidget.tsx

fix: multi file delete always delete first (main)

---

app/backend/lib/sow_import/summary_tab.ts
app/tests/backend/lib/summary_tab.test.ts

Implements [NDT-39]
[NDT-39]: https://connectivitydivision.atlassian.net/browse/NDT-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: skip/accept sow summary when blank

---

app/components/Analyst/ApplicationHeader.tsx
app/tests/components/Analyst/ApplicationHeader.test.tsx

feat: internal intakes allow analyst to jump straight to recommendation

---

.tool-versions
app/package.json
app/pages/_app.tsx

Implements NDT-8
It seems the bug/error that occured with the upload of the SOW may have been related to this bug that has been occuring on and off. 
Tested the build locally, worked fine. If using this locally with asdf remember to use "asdf install" to install the updated version of node.

fix: handle error when attempting to access growthbook

---

app/next.config.js

Implements [NDT-19]
[NDT-19]: https://connectivitydivision.atlassian.net/browse/NDT-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: prod www redirect to non-www

---

app/components/Review/widgets/FileWidget.tsx

Implements: [NDT-2]
[NDT-2]: https://connectivitydivision.atlassian.net/browse/NDT-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show star for latest received rfi by field

---

.github/workflows/deploy-hotfix.yaml
.github/workflows/deploy.yaml
.github/workflows/main.yaml
.github/workflows/recreate-hotfix.yaml
docs/database_development_hotfix.md
docs/process_for_hotfix.md

Implements #NDT-29
Tested the recreate-hotfix workflow and it made the expected change: https://github.com/bcgov/CONN-CCBC-portal/tree/hotfix

fix: change hotfix ci to use certs

---

app/components/Form/ApplicationForm.tsx
app/components/Form/ProjectAreaModal.tsx
app/components/Review/ReviewPageField.tsx
app/components/Review/ReviewTheme.tsx
app/cypress/e2e/applicantportal/dashboard.cy.js
app/formSchema/pages/projectArea.ts
app/formSchema/uiSchema/pages/projectArea.ts
app/lib/theme/widgets/custom/ReadOnlyProjectAreaWidget.tsx
app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx
app/lib/theme/widgets/custom/index.ts
app/tests/pages/applicantportal/form/[id]/submission.test.tsx
app/tests/pages/applicantportal/form/[page].test.tsx

Implements [NDT-9] [NDT-6]
[NDT-9]: https://connectivitydivision.atlassian.net/browse/NDT-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDT-8]: https://connectivitydivision.atlassian.net/browse/NDT-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDT-6]: https://connectivitydivision.atlassian.net/browse/NDT-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: restrict intake to zones based on flag

---

app/components/Form/ProjectAreaModal.tsx
app/tests/pages/applicantportal/form/[page].test.tsx

feat: update modal text and title

---

app/backend/lib/intakeId.ts
app/backend/lib/s3admin-archive.ts
app/tests/backend/lib/intakeId.test.ts
app/tests/backend/lib/requestArchive.test.ts

Fixes [NDT-45]
[NDT-45]: https://connectivitydivision.atlassian.net/browse/NDT-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: attachments not being generated or downloaded

---

app/backend/lib/excel_import/cbc_project.ts
app/tests/backend/lib/excel_import/cbc_project.test.ts

feat: trim cbc data before importing

---

app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalForm.tsx
app/components/Analyst/Project/ProjectForm.tsx
app/cypress/e2e/analyst/application/[applicationId]/project.cy.js
app/tests/components/Analyst/Project/ConditionalApproval/ConditionalApprovalForm.test.tsx
app/tests/components/Analyst/Project/ProjectInformation/ProjectInformationForm.test.ts

fix: use collapse instead of custom animation

---

app/components/Form/ApplicationForm.tsx
app/formSchema/validate.ts
app/pages/analyst/application/[applicationId].tsx
app/tests/formSchema/validate.test.tsx

Implements [#NDT-93](https://connectivitydivision.atlassian.net/browse/NDT-93)
✅ Fix red text warning but all the accordians are closed and no warning symbols

fix: review page error even when all fields filled out

---

app/pages/applicantportal/index.tsx
app/tests/pages/applicantportal/index.test.tsx

Implements [NDT-92](https://connectivitydivision.atlassian.net/browse/NDT-92)
change 
- 'are' →  'will be'
- new line
[NDT-92]: https://connectivitydivision.atlassian.net/browse/NDT-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update text on applicant portal banner

---

app/components/Form/ApplicationForm.tsx
app/components/Form/ProjectAreaModal.tsx
app/tests/pages/applicantportal/form/[page].test.tsx

feat: additional logic for project area page after submission

---

db/data/dev/001_intake.sql

Purely out of convenience whenever I go about deploying dev data. If the other devs find it's not useful feel free to close the PR

chore: update dev data to create relevant intake

---

app/backend/lib/s3admin-archive.ts
app/tests/backend/lib/requestArchive.test.ts

Implements [NDT-96](https://connectivitydivision.atlassian.net/browse/NDT-96)
[NDT-96]: https://connectivitydivision.atlassian.net/browse/NDT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: prepare download crashed when passed -1 as intake id

---

app/components/Form/ApplicationForm.tsx
app/components/Review/ReviewPageField.tsx
app/components/Review/ReviewSectionField.tsx
app/components/Review/fields/ReviewFieldTemplate.tsx
app/formSchema/validate.ts
app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx
app/tests/components/Form/ReadOnlySubmissionWidget.test.tsx

Implements NDT-97 along with another fix for the initial state of the FN-led question and the submission text at the end.

fix: submit and review page now consistent with each other

---

app/components/Form/ApplicationForm.tsx
app/tests/components/Form/ApplicationForm.test.tsx

fix: save and continuie button is disabled while a save operation is in flight

---

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx

Implements [NDT-74](https://connectivitydivision.atlassian.net/browse/NDT-74)
[NDT-74]: https://connectivitydivision.atlassian.net/browse/NDT-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update metabase link for sow in prod

---

app/components/Form/ApplicationForm.tsx
app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx
app/tests/components/Form/ReadOnlySubmissionWidget.test.tsx
app/tests/pages/applicantportal/form/[id]/submission.test.tsx
app/tests/pages/applicantportal/form/[page].test.tsx

Implements [NDT-100](https://connectivitydivision.atlassian.net/browse/NDT-100)
[NDT-100]: https://connectivitydivision.atlassian.net/browse/NDT-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make geographic area required for submission

---

app/components/Form/ApplicationForm.tsx

Fixes [NDT-97]
[NDT-97]: https://connectivitydivision.atlassian.net/browse/NDT-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: inconsistent submit and review page

---

.github/workflows/main.yaml
app/config/dev.json
app/utils/getAuthRole.ts

I'm hoping to push this extra logs to test to help check the claims when the error occurs, should give us more info to find the cause.
Debug [NDT-78]
[NDT-78]: https://connectivitydivision.atlassian.net/browse/NDT-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 78 on login user gets permission denied

---

helm/ccbc-tools/templates/sysdigteam.yaml

chore: update sysdig team

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/Table/RowCount.tsx
app/components/Table/index.tsx
app/pages/analyst/dashboard.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
app/tests/pages/analyst/dashboard.test.tsx

Implements [NDT-57](https://connectivitydivision.atlassian.net/browse/NDT-57)
[NDT-57]: https://connectivitydivision.atlassian.net/browse/NDT-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show row count for analyst dashboard and assessment tables

---

app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx

Implements [NDT-34](https://connectivitydivision.atlassian.net/browse/NDT-34)
[NDT-34]: https://connectivitydivision.atlassian.net/browse/NDT-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make status filter a dropdown

---

app/components/Analyst/ApplicationHeader.tsx
app/components/AnalystDashboard/AnalystRow.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/Dashboard/Row.tsx
app/pages/applicantportal/dashboard.tsx
db/deploy/tables/application_sow_data_002_give_read_applicant.sql
db/revert/tables/application_sow_data_002_give_read_applicant.sql
db/sqitch.plan
db/test/unit/tables/application_sow_data_test.sql

Implements [NDT-33]
[NDT-33]: https://connectivitydivision.atlassian.net/browse/NDT-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 33 header shows the most recent project title

---

app/components/LoginForm.tsx
app/pages/analyst/index.tsx

Implements [NDT-77]
[NDT-77]: https://connectivitydivision.atlassian.net/browse/NDT-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: ised login on analyst page, make login text changeable

---

app/server.ts

feat: add sentry exception capturing 404 errors with static content

---

.zap/rules.tsv

chore: update zap scans to remove warning about CSRF

---

.github/workflows/test-checks.yaml

chore: set cocogitto version to 3.4

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

Implements [NDT-110]
[NDT-110]: https://connectivitydivision.atlassian.net/browse/NDT-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add filtering text to assessment dashboard

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

Implements [NDT-111]
[NDT-111]: https://connectivitydivision.atlassian.net/browse/NDT-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: sort assessment by ccbc number asc

---

app/components/Analyst/AssignPackage.tsx

Implements [NDT-112](https://connectivitydivision.atlassian.net/browse/NDT-112)
[NDT-112]: https://connectivitydivision.atlassian.net/browse/NDT-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style: change package dropdown styles

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
app/tests/pages/analyst/assessments.test.tsx

Implements [NDT-47](https://connectivitydivision.atlassian.net/browse/NDT-47)
[NDT-47]: https://connectivitydivision.atlassian.net/browse/NDT-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add and remove columns from assessment table

---

app/server.ts

HOTFIX: add sentry exception capturing 404 errors with static content

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

Implements [NDT-111]
[NDT-111]: https://connectivitydivision.atlassian.net/browse/NDT-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remember assessment table sorting on session

---

app/components/AnalystDashboard/AllDashboard.tsx
app/cypress/e2e/analyst/dashboard.cy.js
app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx

feat: use mrt for main analyst dashboard

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryFile.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

Implements [NDT-120]
[NDT-120]: https://connectivitydivision.atlassian.net/browse/NDT-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: refine file history for comprehension

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/AnalystDashboard/AssessmentLead.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx

Implements [NDT-106]
[NDT-106]: https://connectivitydivision.atlassian.net/browse/NDT-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 106 make drop down filters for assessment dashboard

---

app/components/AnalystDashboard/AllDashboard.tsx

Implements fix for NDT-109 where package isn't filtering

fix: cast input and cell data as numbers

---

app/components/AnalystDashboard/AllDashboard.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/Table/ClearFilters.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx

Implements [NDT-108](https://connectivitydivision.atlassian.net/browse/NDT-108)
[NDT-108]: https://connectivitydivision.atlassian.net/browse/NDT-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add clear filter button to mui tables

---

app/components/Modal.tsx
app/styles/muiTheme.ts

Implements[ NDT-83](https://connectivitydivision.atlassian.net/browse/NDT-83)

style: refactor mui dialog styles

---

.zap/rules.tsv
app/pages/404.tsx
app/tests/pages/404.test.tsx

Implements [NDT-152](https://connectivitydivision.atlassian.net/browse/NDT-152)
`NOTE`: Ignored failing rules on zap
will be addressed in ticket https://connectivitydivision.atlassian.net/browse/NDT-185
[NDT-152]: https://connectivitydivision.atlassian.net/browse/NDT-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add custom 404 error page

---

app/components/Navigation.tsx

Implements [NDT-186](https://connectivitydivision.atlassian.net/browse/NDT-186)
[NDT-186]: https://connectivitydivision.atlassian.net/browse/NDT-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change navigation z-index

---

app/components/AnalystDashboard/AllDashboard.tsx
app/pages/analyst/dashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx

feat: show internal and external status on the dashboard

---

app/components/Analyst/History/HistoryFile.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

Fixes [NDT-120]
Fixes files not showing or showing "Replaced file with file" (missing file name)
[NDT-120]: https://connectivitydivision.atlassian.net/browse/NDT-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 120 fix

---

app/cypress/e2e/analyst/application/[applicationId]/project.cy.js
app/cypress/e2e/applicantportal/dashboard.cy.js

Implements [NDT-85](https://connectivitydivision.atlassian.net/browse/NDT-85)
[NDT-85]: https://connectivitydivision.atlassian.net/browse/NDT-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update happo screenshots

---

helm/app/templates/cronJobs/prepare-download.yaml
helm/app/templates/cronJobs/receive-applications.yaml
helm/app/templates/cronJobs/trigger-sp-import.yaml
helm/app/values.yaml

feat(cd): add timezones for cronjobs

---

docs/Offboarding.md
helm/ccbc-tools/templates/sysdigteam.yaml

docs: offboarding documentation

---

app/formSchema/uiSchema/admin/intakeUiSchema.ts
app/formSchema/uiSchema/pages/organizationProfile.ts
app/formSchema/uiSchema/pages/otherFundingSources.ts
app/formSchema/uiSchema/pages/projectInformation.ts
app/lib/theme/widgets/TextWidget.tsx

Implements [NDT-138](https://connectivitydivision.atlassian.net/browse/NDT-131?focusedCommentId=12089)
[NDT-138]: https://connectivitydivision.atlassian.net/browse/NDT-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add remaining characters to Text Widget

---

app/cypress/e2e/admin/application-intakes.cy.js
app/cypress/e2e/admin/setup.cy.js
db/data/dev/001_intake.sql
db/data/e2e/001_intake.sql

Implements [NDT-137](https://connectivitydivision.atlassian.net/browse/NDT-137)
[NDT-137]: https://connectivitydivision.atlassian.net/browse/NDT-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add e2e tests for intake

---

app/cypress/e2e/admin/application-intakes.cy.js
app/cypress/e2e/admin/setup.cy.js
db/data/e2e/001_intake.sql

Implements [NDT-85](https://connectivitydivision.atlassian.net/browse/NDT-85)
[NDT-85]: https://connectivitydivision.atlassian.net/browse/NDT-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: set intake timestamps static

---

app/components/AnalystDashboard/AllDashboard.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
app/tests/pages/analyst/dashboard.test.tsx

feat: dashboard uses dropdown for filtering

---

app/components/AnalystDashboard/AllDashboard.tsx

Implements [NDT-104]
[NDT-104]: https://connectivitydivision.atlassian.net/browse/NDT-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make status filter a multiselect on dashboard

---

.github/workflows/main.yaml
app/backend/lib/sso-express/controllers.ts
app/tests/backend/lib/sso-express/controllers.test.ts

Adds a log to check how much time callback took, disables onAuthCallback function call.
Implements [NDT-180]
[NDT-180]: https://connectivitydivision.atlassian.net/browse/NDT-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

debug slow login for analyst portal

---

app/components/AnalystDashboard/AssessmentLead.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx

Implements [NDT-184]
[NDT-184]: https://connectivitydivision.atlassian.net/browse/NDT-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add assessment status colours to dashboard

---

app/components/AnalystDashboard/AssessmentLead.tsx

to match [NDT-197] change
Implements [NDT-184]
[NDT-197]: https://connectivitydivision.atlassian.net/browse/NDT-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDT-184]: https://connectivitydivision.atlassian.net/browse/NDT-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: do not show blue on complete assessment

---

app/components/AnalystDashboard/AllDashboard.tsx
app/package.json
app/yarn.lock

Implements [NDT-198]
[NDT-198]: https://connectivitydivision.atlassian.net/browse/NDT-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: refine all dashboard display, add resize

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx

Implements [NDT-217]
[NDT-217]: https://connectivitydivision.atlassian.net/browse/NDT-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 217 add new columns to assessment dashboard

---

.gitleaks.toml

Implements [NDT-134]
[NDT-134]: https://connectivitydivision.atlassian.net/browse/NDT-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add sentry to gitleaks

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

Implements [NDT-107]
[NDT-107]: https://connectivitydivision.atlassian.net/browse/NDT-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: hide assessed apps from assessment dashboard

---

app/components/AnalystDashboard/AllDashboard.tsx

Implements [NDT-226](https://connectivitydivision.atlassian.net/browse/NDT-226)
[NDT-226]: https://connectivitydivision.atlassian.net/browse/NDT-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: zone typo in all dashboards

---

app/components/AnalystDashboard/AllDashboard.tsx

Implements [NDT-224](https://connectivitydivision.atlassian.net/browse/NDT-224)
[NDT-224]: https://connectivitydivision.atlassian.net/browse/NDT-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: make zone and package centered

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

Implements [NDT-225](https://connectivitydivision.atlassian.net/browse/NDT-225)
[NDT-225]: https://connectivitydivision.atlassian.net/browse/NDT-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: center align zone in assesment dashboard

---

.github/workflows/backup-secrets.yaml
.github/workflows/main.yaml

Fixes a typo on the export secrets job for the new CHES secrets that was making it fail the export.

fix: ches export secrets

---

app/backend/lib/s3admin-archive.ts

fixes the s3 archive download to match the lambda function on AWS

fix: s3 archive download

---

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/components/Analyst/Project/widgets/AmendmentNumberWidget.tsx

Implements [NDT-234](https://connectivitydivision.atlassian.net/browse/NDT-234)
[NDT-234]: https://connectivitydivision.atlassian.net/browse/NDT-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: error in amendment number for submitting update

---

app/data/statusStyles.ts
app/tests/components/Analyst/ChangeStatus.test.tsx
app/tests/utils/mockStatusTypes.ts
db/deploy/tables/application_status_type_009_change_complete.sql.sql
db/revert/tables/application_status_type_009_change_complete.sql.sql
db/sqitch.plan

Implements [NDT-223](https://connectivitydivision.atlassian.net/browse/NDT-223)
[NDT-223]: https://connectivitydivision.atlassian.net/browse/NDT-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: change complete status to reporting complete

---

app/components/Analyst/ApplicationHeader.tsx
app/components/AnalystDashboard/AllDashboard.tsx
app/tests/components/Analyst/ApplicationHeader.test.tsx
app/tests/pages/analyst/application/[applicationId].test.tsx
app/tests/pages/analyst/dashboard.test.tsx

Implements  [NDT-216](https://connectivitydivision.atlassian.net/browse/NDT-216)
[NDT-216]: https://connectivitydivision.atlassian.net/browse/NDT-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: hide Lead with feature flag

---

app/components/AnalystDashboard/AllDashboard.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

Implements [NDT-255](https://connectivitydivision.atlassian.net/browse/NDT-255)
[NDT-255]: https://connectivitydivision.atlassian.net/browse/NDT-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: MRT table sort freezes after two clicks

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/components/AnalystDashboard/AssessmentLead.tsx
app/components/AnalystDashboard/AssessmentLegend.tsx
app/components/AnalystDashboard/index.tsx
app/components/Table/ClearFilters.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx

Implements [NDT-228](https://connectivitydivision.atlassian.net/browse/NDT-228)
[NDT-228]: https://connectivitydivision.atlassian.net/browse/NDT-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add legend to assesmsnt assignment table

---

app/components/AnalystDashboard/AssessmentLead.tsx

fix: trim analyst names

---

app/pages/analyst/gis/index.tsx
app/tests/pages/analyst/admin/gis-upload.test.tsx

Implements [NDT-155](https://connectivitydivision.atlassian.net/browse/NDT-155)
- enabling drag and drop for GIS upload as well
- unrelated changes due to file formatting
[NDT-155]: https://connectivitydivision.atlassian.net/browse/NDT-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore enable drag and drop in GIS

---

app/components/Analyst/Assessments/AssessmentsTable.tsx
app/components/Analyst/GuideLink.tsx
app/components/Analyst/RFI/RfiForm.tsx
app/data/externalConstants.ts
app/pages/analyst/application/[applicationId]/assessments/index.tsx
app/pages/analyst/application/[applicationId]/assessments/screening.tsx
app/pages/analyst/application/[applicationId]/assessments/technical.tsx
app/pages/analyst/application/[applicationId]/rfi/[rfiId]/index.tsx
app/pages/analyst/application/[applicationId]/rfi/index.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/index.test.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/index.test.tsx

Implements [NDT-240](https://connectivitydivision.atlassian.net/browse/NDT-240)
[NDT-240]: https://connectivitydivision.atlassian.net/browse/NDT-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add assessment guides in portal

---

app/data/externalConstants.ts
app/pages/analyst/application/[applicationId]/assessments/screening.tsx
app/tests/pages/analyst/application/[applicationId]/assessments/screening.test.tsx

Implements [NDT-244](https://connectivitydivision.atlassian.net/browse/NDT-244)
[NDT-244]: https://connectivitydivision.atlassian.net/browse/NDT-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add screening template link

---

app/components/AnalystDashboard/AllDashboard.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

fix: filter function and sort function for zones

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

feat: remove inactive analysts from filter

---

app/components/Form/ApplicationForm.tsx
app/components/Form/ProjectAreaModal.tsx
app/cypress/e2e/applicantportal/dashboard.cy.js
app/tests/pages/applicantportal/form/[id]/submission.test.tsx
app/tests/pages/applicantportal/form/[page].test.tsx

Implements [NDT-274](https://connectivitydivision.atlassian.net/browse/NDT-274)
[NDT-274]: https://connectivitydivision.atlassian.net/browse/NDT-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update growthbook feature flag

---

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/cypress/e2e/applicantportal/dashboard.cy.js

Implements [NDT-253](https://connectivitydivision.atlassian.net/browse/NDT-253)
[NDT-253]: https://connectivitydivision.atlassian.net/browse/NDT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: project information edit button issue

---

app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/components/Analyst/Project/ProjectInformation/ReadOnlyView.tsx
app/formSchema/analyst/changeRequest.ts
app/formSchema/analyst/projectInformation.ts
app/formSchema/uiSchema/analyst/changeRequestUiSchema.ts
app/formSchema/uiSchema/analyst/projectInformationUiSchema.ts
app/tests/components/Analyst/Project/ProjectInformation/ProjectInformationForm.test.ts
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

Implements [NDT-266]
[NDT-266]: https://connectivitydivision.atlassian.net/browse/NDT-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add other files upload to funding agreement and change request

---

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx

fix: better sort function for zones

---

app/data/zoneKmzLinksIntake4.ts

Implements [NDT-285](https://connectivitydivision.atlassian.net/browse/NDT-285)
[NDT-285]: https://connectivitydivision.atlassian.net/browse/NDT-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove intake 4 zone 14 kmz links

---

app/data/zoneKmzLinksIntake4.ts

feat: add kmz and pdf link for zone 14

---

app/data/externalConstants.ts

Implements [NDT-272](https://connectivitydivision.atlassian.net/browse/NDT-272)
[NDT-272]: https://connectivitydivision.atlassian.net/browse/NDT-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: change assessment and RFI guide link to pdf version

---

docs/service_account_pw_change.md

Implements [NDT-281]
[NDT-281]: https://connectivitydivision.atlassian.net/browse/NDT-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add sa pw change docs

---

app/backend/lib/emails/email.ts
app/backend/lib/emails/handleEmailNotification.ts
app/backend/lib/emails/templates/assesmentSecondReviewChange.ts
app/components/Analyst/Assessments/AssessmentsForm.tsx
app/pages/analyst/application/[applicationId]/assessments/financial-risk.tsx
app/pages/analyst/application/[applicationId]/assessments/gis.tsx
app/pages/analyst/application/[applicationId]/assessments/permitting.tsx
app/pages/analyst/application/[applicationId]/assessments/project-management.tsx
app/pages/analyst/application/[applicationId]/assessments/technical.tsx
app/tests/backend/lib/emails/email.test.ts
app/tests/backend/lib/emails/handleEmailNotification.test.ts
app/tests/backend/lib/emails/templates/assesmentSecondReviewChange.test.ts

Implements [#NDT-239](https://connectivitydivision.atlassian.net/browse/NDT-239)

chore: email analyst for 2nd review on assessment page

---

app/components/Analyst/History/HistoryContent.tsx
app/formSchema/uiSchema/history/commonAssessment.ts
app/formSchema/uiSchema/history/screening.ts
app/tests/pages/analyst/application/[applicationId]/history.test.tsx

feat: screening assessment shows changes

---

.github/actions/feature/action.yaml
.github/actions/local-app-run/action.yaml
.github/workflows/clean-feature-env.yaml
.github/workflows/deploy.yaml
.github/workflows/deploy_feature.yaml
.github/workflows/main.yaml
db/Dockerfile
helm/feature/templates/_helpers.tpl
helm/feature/templates/db-pre-job.yaml
helm/feature/templates/db-pre-upgrade-job.yaml
helm/feature/templates/secret.yaml
helm/feature/values.yaml
lib/app_deploy_feature.sh
lib/feature_envs/create_feature_db.sh
lib/feature_envs/delete_feature_db.sh

Implements [NDT-208] and [NDT-213]
[NDT-208]: https://connectivitydivision.atlassian.net/browse/NDT-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDT-213]: https://connectivitydivision.atlassian.net/browse/NDT-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: feature environments

---

app/backend/lib/emails/email.ts
app/backend/lib/emails/templates/agreementSignedStatusChange.ts
app/backend/lib/emails/templates/agreementSignedStatusChangeDataTeam.ts
app/components/Analyst/ChangeStatus.tsx
app/tests/backend/lib/emails/email.test.ts
app/tests/backend/lib/emails/templates/agreementSignedStatusChange.test.ts
app/tests/backend/lib/emails/templates/agreementSignedStatusChangeDataTeam.test.ts
app/tests/components/Analyst/ChangeStatus.test.tsx

Implements [NDT-267]
[NDT-267]: https://connectivitydivision.atlassian.net/browse/NDT-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: email notification for agreement signed

---

.github/workflows/main.yaml

Implements [NDT-210](https://connectivitydivision.atlassian.net/browse/NDT-210)
[NDT-210]: https://connectivitydivision.atlassian.net/browse/NDT-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: refresh-rebase feature branches

---

.github/actions/feature/action.yaml

fix: feature env hardcoded app tag

---

app/data/statusStyles.ts

Implements [NDT-275]
[NDT-275]: https://connectivitydivision.atlassian.net/browse/NDT-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update width of status style

---

app/components/AnalystDashboard/AllDashboard.tsx

Finishes [NDT-295]
[NDT-295]: https://connectivitydivision.atlassian.net/browse/NDT-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: package number for ccbc projects on dashboard

---

app/components/Review/Accordion.tsx
app/components/Review/Components.tsx
app/components/Review/fields/ReviewFieldTemplate.tsx
app/pages/analyst/cbc/[cbcId].tsx

Implements [NDT-315]
[NDT-315]: https://connectivitydivision.atlassian.net/browse/NDT-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: cbc flag when total project budget does not add up

---

app/backend/lib/emails/email.ts
app/backend/lib/emails/templates/notifyConditionallyApproved.ts
app/components/Analyst/AssignProjectType.tsx
app/components/Analyst/ChangeStatus.tsx
app/tests/backend/lib/emails/email.test.ts
app/tests/backend/lib/emails/templates/notifyConditionallyApproved.test.ts
app/tests/components/Analyst/ChangeStatus.test.tsx

Implements [[NDT-318](https://connectivitydivision.atlassian.net/browse/NDT-318)]
[NDT-318]: https://connectivitydivision.atlassian.net/browse/NDT-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: send email when conditionally_approved

---

.github/actions/feature/action.yaml
.github/workflows/deploy_feature.yaml
.github/workflows/jira-feat.yaml

fix: trailing dashes on feature env

---

app/components/Form/ApplicationForm.tsx

Implements [[NDT-388](https://connectivitydivision.atlassian.net/browse/NDT-388)]
[NDT-388]: https://connectivitydivision.atlassian.net/browse/NDT-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: benefit schema validation issue

---

.github/actions/feature/action.yaml

fix: use shortened feature name for helm and route

---

CHANGELOG.md
app/components/DownloadLink.tsx
db/sqitch.plan
package.json

Implements [NDT-399]
[NDT-399]: https://connectivitydivision.atlassian.net/browse/NDT-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: comma on filename extension on download

---

app/backend/lib/s3download.ts
app/tests/backend/lib/s3download.test.ts

fix: add cbc_admin role to allowed download of attachments

---

.github/actions/app/action.yaml
.github/actions/feature/action.yaml
CHANGELOG.md
db/sqitch.plan
helm/app/templates/deployment.yaml
helm/app/values.yaml
helm/feature/templates/deployment.yaml
helm/feature/values.yaml
package.json

fix: match sentry release with app

---

CHANGELOG.md
app/components/Analyst/RFI/RFIAnalystUpload.tsx
app/formSchema/uiSchema/analyst/rfiUiSchema.ts
app/lib/theme/widgets/FileWidget.tsx
app/tests/components/Form/FileWidget.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-232](https://connectivitydivision.atlassian.net/browse/NDT-232)]
[NDT-232]: https://connectivitydivision.atlassian.net/browse/NDT-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: typo in alert RFI upload

---

CHANGELOG.md
app/lib/theme/widgets/ZoneMapWidget.tsx
db/sqitch.plan
package.json

Implements [NDT-444]
[NDT-444]: https://connectivitydivision.atlassian.net/browse/NDT-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use intake five map if no dict match

---

.github/workflows/nightly.yaml

chore: add install test env to nightly

---

CHANGELOG.md
app/backend/lib/excel_import/cbc_project.ts
app/backend/lib/excel_import/cbc_project_communities.ts
app/backend/lib/excel_import/communities_source_data.ts
app/backend/lib/sharepoint.ts
app/formSchema/analyst/cbc/locationsAndCounts.ts
app/formSchema/uiSchema/cbc/locationsAndCountsUiSchema.ts
app/pages/analyst/cbc/[cbcId].tsx
app/pages/analyst/cbc/[cbcId]/edit/[section].tsx
app/schema/schema.graphql
app/tests/backend/lib/excel_import/cbc_project.test.ts
app/tests/backend/lib/excel_import/cbc_project_communities.test.ts
app/tests/backend/lib/excel_import/communities_source_data.test.ts
app/tests/backend/lib/sharepoint.test.ts
app/tests/pages/analyst/cbc/[cbcId].test.tsx
app/tests/pages/analyst/cbc/[cbcId]/[section].test.tsx
app/utils/schemaUtils.ts
db/deploy/tables/cbc_project_communities.sql
db/deploy/tables/communities_source_data.sql
db/revert/tables/cbc_project_communities.sql
db/revert/tables/communities_source_data.sql
db/sqitch.plan
package.json

Implements [[NDT-345](https://connectivitydivision.atlassian.net/browse/NDT-345)]
[NDT-345]: https://connectivitydivision.atlassian.net/browse/NDT-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: import and show cbc communities data

---

CHANGELOG.md
app/components/Analyst/CBC/CbcAnalystLayout.tsx
app/components/Analyst/CBC/CbcAssignProjectType.tsx
app/components/Analyst/CBC/CbcChangeStatus.tsx
app/components/Analyst/CBC/CbcEditProjectDescription.tsx
app/components/Analyst/CBC/CbcHeader.tsx
app/components/Analyst/CBC/CbcRecordLock.tsx
app/components/Analyst/PendingChangeRequest/PendingChangeRequest.tsx
app/components/Analyst/PendingChangeRequest/PendingChangeRequestModal.tsx
app/components/Review/Accordion.tsx
app/components/Review/ReviewSectionField.tsx
app/components/Review/fields/ReviewFieldTemplate.tsx
app/cypress/e2e/analyst/cbc/[cbcId].cy.js
app/formSchema/analyst/cbc/tombstone.ts
app/formSchema/uiSchema/cbc/projectDataReviewsUiSchema.ts
app/formSchema/uiSchema/cbc/reviewUiSchema.ts
app/formSchema/uiSchema/cbc/tombstoneUiSchema.ts
app/lib/theme/widgets/GenericConfirmationModal.tsx
app/pages/analyst/cbc/[cbcId].tsx
app/tests/components/Analyst/PendingChangeRequest.test.tsx
app/tests/components/Review/ReviewTheme.ts
app/tests/pages/analyst/cbc/[cbcId].test.tsx
app/tests/pages/analyst/cbc/[cbcId]/[section].test.tsx
app/utils/isRouteAuthorized.ts
db/sqitch.plan
package.json

Implements [[NDT-355](https://connectivitydivision.atlassian.net/browse/NDT-355)]
[NDT-355]: https://connectivitydivision.atlassian.net/browse/NDT-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: cbc details page changes

---

CHANGELOG.md
app/components/Analyst/AssignProjectType.tsx
db/deploy/tables/application_project_type_001_modify_check_constraint.sql
db/revert/tables/application_project_type_001_modify_check_constraint.sql
db/sqitch.plan
package.json

Implements [NDT-438]
[NDT-438]: https://connectivitydivision.atlassian.net/browse/NDT-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add transport project type to ccbc

---

CHANGELOG.md
app/components/Form/CustomTitles.tsx
app/formSchema/analyst/screening.ts
app/formSchema/uiSchema/analyst/assessmentsUiSchema.ts
app/formSchema/uiSchema/history/screening.ts
app/tests/pages/analyst/application/[applicationId]/assessments/screening.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-431](https://connectivitydivision.atlassian.net/browse/NDT-431)]
[NDT-431]: https://connectivitydivision.atlassian.net/browse/NDT-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add dependants checkboxes to screening

---

CHANGELOG.md
app/components/Analyst/ChangeModal.tsx
app/pages/analyst/cbc/[cbcId].tsx
app/pages/analyst/cbc/[cbcId]/edit/[section].tsx
app/tests/pages/analyst/cbc/[cbcId].test.tsx
db/sqitch.plan
package.json

Implements [NDT-366]
[NDT-366]: https://connectivitydivision.atlassian.net/browse/NDT-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add change reason to quick edit, check role

---

CHANGELOG.md
app/components/AnalystDashboard/AdditionalFilters.tsx
app/components/AnalystDashboard/AllDashboard.tsx
app/components/Table/ClearFilters.tsx
app/schema/schema.graphql
app/tests/pages/analyst/dashboard.test.tsx
db/deploy/tables/application_003_add_program.sql
db/revert/tables/application_003_add_program.sql
db/sqitch.plan
package.json

Implements [[NDT-407](https://connectivitydivision.atlassian.net/browse/NDT-407)]
[NDT-407]: https://connectivitydivision.atlassian.net/browse/NDT-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add program column to application

---

app/components/AnalystDashboard/AllDashboard.tsx

fix: intake filter

---

.github/workflows/deploy-hotfix.yaml

fix-hotfix-deploy

---

app/backend/lib/validation.ts
app/components/Analyst/CBC/CbcEditProjectNumber.tsx
app/components/Analyst/CBC/CbcHeader.tsx
app/components/AnalystDashboard/AllDashboard.tsx
app/lib/theme/widgets/GenericConfirmationModal.tsx
app/pages/analyst/cbc/[cbcId].tsx
app/schema/mutations/cbc/updateCbcProjectNumber.ts
app/server.ts
app/tests/backend/lib/validation.test.ts
app/tests/pages/analyst/cbc/[cbcId].test.tsx
app/tests/pages/analyst/dashboard.test.tsx
db/deploy/tables/cbc_add_fk_update_constraint.sql
db/revert/tables/cbc_add_fk_update_constraint.sql
db/sqitch.plan

Implements [NDT-386]
[NDT-386]: https://connectivitydivision.atlassian.net/browse/NDT-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: refine cbc header

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-363](https://connectivitydivision.atlassian.net/browse/NDT-363)]
[NDT-363]: https://connectivitydivision.atlassian.net/browse/NDT-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: sort order for status ccbc and cbc combined

---

CHANGELOG.md
app/backend/lib/reporting/gcpe.ts
db/sqitch.plan
package.json

Implements [[NDT-483](https://connectivitydivision.atlassian.net/browse/NDT-483)]
[NDT-483]: https://connectivitydivision.atlassian.net/browse/NDT-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: filtering for ccbc gcpe report

---

CHANGELOG.md
app/formSchema/analyst/cbc/locationsAndCounts.ts
app/utils/cbcCustomValidator.ts
db/sqitch.plan
package.json

Implements [NDT-480]
[NDT-480]: https://connectivitydivision.atlassian.net/browse/NDT-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cbc household count validation

---

CHANGELOG.md
app/backend/lib/reporting/util.ts
db/sqitch.plan
package.json

Implements [NDT-492]
[NDT-492]: https://connectivitydivision.atlassian.net/browse/NDT-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: colour is now a background colour in gcpe report compare

---

CHANGELOG.md
app/backend/lib/reporting/header.ts
app/tests/backend/lib/reporting/testData.ts
db/sqitch.plan
package.json

Implements [NDT-496]
[NDT-496]: https://connectivitydivision.atlassian.net/browse/NDT-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: change to announced by bc/ised in gcpe report

---

.github/workflows/deploy-hotfix.yaml

fix: include new secrets added for hotfix

---

CHANGELOG.md
app/components/Form/GenericFormStatus.tsx
app/components/Form/RfiFormStatus.tsx
app/tests/pages/analyst/application/[applicationId]/rfi/[rfiId]/upload.test.tsx
app/tests/pages/applicantportal/form/[id]/rfi/[applicantRfiId].test.tsx
db/sqitch.plan
package.json

Implements [[NDT-418](https://connectivitydivision.atlassian.net/browse/NDT-418)]
[NDT-418]: https://connectivitydivision.atlassian.net/browse/NDT-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove unwanted status text from RFI

---

CHANGELOG.md
app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
db/sqitch.plan
package.json

Draft until NDT-421 is merged in so this won't merge in both
Implements [NDT-350]
[NDT-350]: https://connectivitydivision.atlassian.net/browse/NDT-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: pm assesment notification

---

CHANGELOG.md
app/backend/lib/emails/templates/notifyApplicationSubmission.ts
app/tests/backend/lib/emails/templates/notifyApplicationSubmission.test.ts
db/sqitch.plan
package.json

Implements [[NDT-517](https://connectivitydivision.atlassian.net/browse/NDT-517)]
[NDT-517]: https://connectivitydivision.atlassian.net/browse/NDT-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add more receipients to application submission mail

---

CHANGELOG.md
app/components/Analyst/Project/fields/ProjectFieldTemplate.tsx
app/components/Review/Components.tsx
app/components/Review/fields/ArrayBooleanField.tsx
app/components/Review/fields/ReviewCheckboxField.tsx
app/components/Review/fields/ReviewFieldTemplate.tsx
app/components/Review/fields/ReviewInlineArrayField.tsx
app/components/Review/index.ts
app/pages/analyst/cbc/[cbcId]/edit/[section].tsx
app/tests/pages/analyst/cbc/[cbcId]/[section].test.tsx
db/sqitch.plan
package.json

Implements [[NDT-535](https://connectivitydivision.atlassian.net/browse/NDT-535)]
[NDT-535]: https://connectivitydivision.atlassian.net/browse/NDT-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cbc edit input focus issue

---

app/components/Navigation.tsx
helm/app/templates/cronJobs/trigger-sp-import.yaml

Implements [NDT-401]
[NDT-401]: https://connectivitydivision.atlassian.net/browse/NDT-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: cutover work for cbc spreadsheet

---

.github/workflows/release-process.yaml
CHANGELOG.md
db/sqitch.plan
package.json

Implements [[NDT-533](https://connectivitydivision.atlassian.net/browse/NDT-533)]
[NDT-533]: https://connectivitydivision.atlassian.net/browse/NDT-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: user config in auto merge

---

CHANGELOG.md
app/backend/lib/emails/email.ts
app/backend/lib/emails/handleEmailNotification.ts
app/backend/lib/emails/templates/notifyFailedReadOfTemplateData.ts
app/components/Analyst/RFI/RFIAnalystUpload.tsx
app/components/Form/ApplicationForm.tsx
app/lib/theme/widgets/FileWidget.tsx
app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx
app/tests/backend/lib/emails/email.test.ts
app/tests/backend/lib/emails/templates/notifyFailedReadOfTemplateData.test.ts
app/tests/components/Form/ApplicationForm.test.tsx
app/tests/pages/applicantportal/form/[id]/rfi/[applicantRfiId].test.tsx
db/sqitch.plan
package.json

Implements [NDT-532]
[NDT-532]: https://connectivitydivision.atlassian.net/browse/NDT-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: email notification on failed template read

---

app/package.json
app/utils/isRouteAuthorized.ts
app/yarn.lock

Decided not to commit to the 8.0.0 upgrade, would add extra complexity to how we define routes. Additionally, this update covers the regexp backtracking exploit
Implements [NDT-469]
[NDT-469]: https://connectivitydivision.atlassian.net/browse/NDT-469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update isRouteAuthorized and add needed roles for certain paths

---

CHANGELOG.md
app/backend/lib/s3client.ts
db/sqitch.plan
package.json

Implements [NDT-548]
[NDT-548]: https://connectivitydivision.atlassian.net/browse/NDT-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: file download with special characters

---

CHANGELOG.md
app/lib/theme/widgets/custom/CommunitySourceWidget.tsx
db/sqitch.plan
package.json

Implements [[NDT-521](https://connectivitydivision.atlassian.net/browse/NDT-521)]
[NDT-521]: https://connectivitydivision.atlassian.net/browse/NDT-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: autocomplete community source widget

---

helm/app/values-dev.yaml

chore: increase dev/feat env db storage

---

CHANGELOG.md
README.md
db/sqitch.plan
docs/Necessary_changes_For_Intake_Update.md
package.json

Implements [NDT-452]
[NDT-452]: https://connectivitydivision.atlassian.net/browse/NDT-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: intake changes guide

---

CHANGELOG.md
app/components/Review/Accordion.tsx
app/components/Review/ReviewSectionField.tsx
app/lib/helpers/ccbcSummaryGenerateFormData.tsx
app/pages/analyst/application/[applicationId]/summary.tsx
app/tests/pages/analyst/application/[applicationId]/summary.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-505](https://connectivitydivision.atlassian.net/browse/NDT-505)]
[NDT-505]: https://connectivitydivision.atlassian.net/browse/NDT-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add alert in summary when sow not uploaded

---

CHANGELOG.md
db/deploy/clean_pre_cut_over_cbc_history.sql
db/revert/clean_pre_cut_over_cbc_history.sql
db/sqitch.plan
package.json

Implements [[NDT-559](https://connectivitydivision.atlassian.net/browse/NDT-559)]
[NDT-559]: https://connectivitydivision.atlassian.net/browse/NDT-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove cbc history data

---

CHANGELOG.md
app/lib/helpers/ccbcSummaryGenerateFormData.tsx
db/sqitch.plan
package.json

Implements [NDT-541]
[NDT-541]: https://connectivitydivision.atlassian.net/browse/NDT-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: split funding for ccbc summary (application)

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
db/sqitch.plan
package.json

Implements [NDT-530]
[NDT-530]: https://connectivitydivision.atlassian.net/browse/NDT-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add status infographic on all dashboard

---

CHANGELOG.md
app/lib/theme/widgets/custom/CommunitySourceWidget.tsx
app/pages/analyst/cbc/[cbcId].tsx
app/pages/analyst/cbc/[cbcId]/edit/[section].tsx
app/schema/mutations/cbc/updateCbcCommunityData.ts
app/tests/components/Form/CommunitySourceWidget.test.tsx
app/utils/schemaUtils.ts
db/sqitch.plan
package.json

Implements [[NDT-534](https://connectivitydivision.atlassian.net/browse/NDT-534)]
[NDT-534]: https://connectivitydivision.atlassian.net/browse/NDT-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add type and id to economicregion dropdown

---

CHANGELOG.md
app/next-env.d.ts
app/pages/analyst/application/[applicationId].tsx
app/pages/analyst/application/[applicationId]/project.tsx
app/pages/analyst/application/[applicationId]/summary.tsx
app/tests/pages/analyst/application/[applicationId]/project.test.tsx
db/sqitch.plan
package.json

Implements [NDT-489]
[NDT-489]: https://connectivitydivision.atlassian.net/browse/NDT-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add heading and explanation at top of ccbc summary

---

CHANGELOG.md
app/backend/lib/emails/templates/notifyApplicationSubmission.ts
app/tests/backend/lib/emails/templates/notifyApplicationSubmission.test.ts
db/sqitch.plan
package.json

Implements [[NDT-567](https://connectivitydivision.atlassian.net/browse/NDT-567)]
[NDT-567]: https://connectivitydivision.atlassian.net/browse/NDT-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add data team to appliction submission email list

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-573](https://connectivitydivision.atlassian.net/browse/NDT-573)]
[NDT-573]: https://connectivitydivision.atlassian.net/browse/NDT-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: enable global filter to all dashboard

---

CHANGELOG.md
app/backend/lib/communityReportsDueDate.ts
app/backend/lib/emails/templates/notifyCommunityReportDue.ts
app/next-env.d.ts
app/server.ts
app/tests/backend/lib/communityDueDate.test.ts
app/tests/backend/lib/emails/templates/notifyCommunityReportDue.test.ts
db/sqitch.plan
helm/app/templates/cronJobs/trigger-community-report-notification.yaml
helm/app/values.yaml
package.json

Note: contains changes for NDT-362 so will keep in draft until that is merged in
Implements [NDT-457]
[NDT-457]: https://connectivitydivision.atlassian.net/browse/NDT-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: notify to analysts when community progress report is due

---

CHANGELOG.md
db/sqitch.plan
helm/app/templates/deployment.yaml
package.json

Implements [NDT-618]
[NDT-618]: https://connectivitydivision.atlassian.net/browse/NDT-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove missing volumes and volumeMounts

---

.github/dependabot.yml

Implements [[NDT-623](https://connectivitydivision.atlassian.net/browse/NDT-623)]
[NDT-623]: https://connectivitydivision.atlassian.net/browse/NDT-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: group dependabot minor updates

---

CHANGELOG.md
db/sqitch.plan
helm/app/templates/deployment.yaml
package.json

Implements [NDT-618]
[NDT-618]: https://connectivitydivision.atlassian.net/browse/NDT-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update rolling update strategy

---

CHANGELOG.md
app/components/Analyst/History/HistoryContent.tsx
db/sqitch.plan
package.json

Implements [NDT-602]
[NDT-602]: https://connectivitydivision.atlassian.net/browse/NDT-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add withdrawn to status external check on history

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
db/sqitch.plan
package.json

Implements [[NDT-630](https://connectivitydivision.atlassian.net/browse/NDT-630)]
[NDT-630]: https://connectivitydivision.atlassian.net/browse/NDT-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: browser compatibility on toSorted

---

.github/actions/app/action.yaml
.github/workflows/deploy.yaml
.github/workflows/main.yaml
CHANGELOG.md
db/sqitch.plan
helm/app/templates/secret.yaml
helm/app/values.yaml
package.json

Implements [NDT-618]
[NDT-618]: https://connectivitydivision.atlassian.net/browse/NDT-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: deterministic session secret

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/components/AnalystDashboard/AllDashboardDetailPanel.tsx
app/components/Table/ClearFilters.tsx
app/tests/pages/analyst/dashboard.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-543](https://connectivitydivision.atlassian.net/browse/NDT-543)]
[NDT-543]: https://connectivitydivision.atlassian.net/browse/NDT-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: enable global filter to filter communities

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
db/sqitch.plan
package.json

Implements [[NDT-604](https://connectivitydivision.atlassian.net/browse/NDT-604)]
[NDT-604]: https://connectivitydivision.atlassian.net/browse/NDT-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll preservation when sticky header on in all dashboard

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-596](https://connectivitydivision.atlassian.net/browse/NDT-596)]
[NDT-596]: https://connectivitydivision.atlassian.net/browse/NDT-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: filter package by null

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
db/sqitch.plan
package.json

Implements [NDT-606]
[NDT-606]: https://connectivitydivision.atlassian.net/browse/NDT-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: filter status on global search

---

CHANGELOG.md
app/components/Analyst/History/HistoryContent.tsx
app/components/Review/Components.tsx
app/components/Review/fields/ReviewFieldTemplate.tsx
app/lib/helpers/ccbcSummaryGenerateFormData.tsx
app/pages/analyst/application/[applicationId]/summary.tsx
app/tests/pages/analyst/application/[applicationId]/summary.test.tsx
db/sqitch.plan
package.json

DEPENDS ON NDT-578, needs to be rebased before merge.
Implements [NDT-576]
[NDT-576]: https://connectivitydivision.atlassian.net/browse/NDT-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: summary page enhancement for dependency

---

.zap/rules.tsv
CHANGELOG.md
db/Dockerfile
db/sqitch.plan
helm/app/values.yaml
package.json

Implements [NDT-663]
[NDT-663]: https://connectivitydivision.atlassian.net/browse/NDT-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: upgrade postgres, remove image

---

CHANGELOG.md
app/backend/lib/ches/sendEmail.ts
app/backend/lib/ches/sendEmailMerge.ts
app/backend/lib/emails/email.ts
app/backend/lib/emails/templates/notifyDocumentUpload.ts
app/components/Analyst/History/HistoryFilter.tsx
app/components/Analyst/Project/Claims/ClaimsForm.tsx
app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/components/Analyst/Project/Milestones/MilestonesForm.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/components/Analyst/RFI/RFIAnalystUpload.tsx
app/lib/helpers/useEmailNotification.ts
app/lib/theme/widgets/FileWidget.tsx
app/pages/analyst/application/[applicationId]/edit/[section].tsx
app/pages/analyst/application/[applicationId]/project.tsx
app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx
app/tests/backend/lib/emails/email.test.ts
app/tests/backend/lib/emails/templates/notifyDocumentUpload.test.ts
app/tests/backend/lib/helpers/useEmailNotification.test.ts
app/tests/components/Analyst/Project/Claims/ClaimsForm.test.tsx
app/tests/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.test.tsx
app/tests/components/Analyst/Project/Milestones/MilestonesForm.test.tsx
app/tests/components/Analyst/RFI/RFIAnalystUpload.test.ts
app/tests/pages/analyst/application/[applicationId]/edit/[section].test.tsx
app/utils/formatArray.ts
app/utils/formatString.ts
db/sqitch.plan
package.json

Implements [[NDT-627](https://connectivitydivision.atlassian.net/browse/NDT-627)]
[NDT-627]: https://connectivitydivision.atlassian.net/browse/NDT-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: send email notification when a file upload to internal team

---

CHANGELOG.md
app/backend/lib/coverages-upload.ts
app/pages/analyst/gis/coverages.tsx
app/schema/schema.graphql
app/server.ts
app/tests/backend/lib/s3upload.test.ts
cron/shp/entrypoint.sh
cron/shp/sql/create_application_er.sql
cron/shp/sql/create_application_rd.sql
db/deploy/tables/coverages_upload.sql
db/revert/tables/coverages_upload.sql
db/sqitch.plan
package.json

Implements [NDT-652]
[NDT-652]: https://connectivitydivision.atlassian.net/browse/NDT-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 652 spike investigate solutions for history of ccbc e rs and r ds

---

.github/workflows/scorecards.yml
CHANGELOG.md
app/lib/helpers/ccbcSummaryGenerateFormData.tsx
app/tests/pages/analyst/application/[applicationId]/summary.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-640](https://connectivitydivision.atlassian.net/browse/NDT-640)]
[NDT-640]: https://connectivitydivision.atlassian.net/browse/NDT-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove info and error hints from dependencies in summary

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
db/sqitch.plan
package.json

Implements [[NDT-685](https://connectivitydivision.atlassian.net/browse/NDT-685)]
[NDT-685]: https://connectivitydivision.atlassian.net/browse/NDT-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: status filter on all dashboard

---

.github/workflows/move-on-merge-conflict.yaml

feat: add sprint done to columns checked for merge conflict

---

.github/workflows/test-code.yaml
.github/workflows/test-e2e.yaml
.github/workflows/test-zap.yaml
app/cypress.config.ts

Implements [NDT-624]
[NDT-624]: https://connectivitydivision.atlassian.net/browse/NDT-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: improvement to ci/cd

---

CHANGELOG.md
app/components/Analyst/GIS/GisHistory.tsx
app/components/AnalystDashboard/AllDashboard.tsx
app/components/Table/ClearFilters.tsx
app/components/Table/Filters/DateFilter.tsx
app/pages/analyst/gis/coverages.tsx
app/tests/pages/analyst/gis/coverages.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-642](https://connectivitydivision.atlassian.net/browse/NDT-642)]
[NDT-642]: https://connectivitydivision.atlassian.net/browse/NDT-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add history table to GIS coverage

---

CHANGELOG.md
app/components/Dashboard/Row.tsx
app/components/Dashboard/Table.tsx
app/components/Form/ApplicationForm.tsx
app/cypress/e2e/applicantportal/dashboard.cy.js
app/cypress/e2e/applicantportal/upload.cy.js
app/pages/applicantportal/dashboard.tsx
app/pages/applicantportal/index.tsx
app/tests/components/Dashboard/Dashboard.test.tsx
app/tests/components/Form/ApplicationForm.test.tsx
app/tests/components/Form/FileWidget.test.tsx
app/tests/pages/applicantportal/dashboard.test.tsx
app/tests/pages/applicantportal/form/[id]/submission.test.tsx
app/tests/pages/applicantportal/form/[page].test.tsx
app/tests/pages/applicantportal/index.test.tsx
db/sqitch.plan
package.json

Implements [NDT-694]
[NDT-694]: https://connectivitydivision.atlassian.net/browse/NDT-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: intake 6 UI preparation

---

cron/shp/sql/create_application_er.sql
cron/shp/sql/create_application_rd.sql

chore: add missing trigger grant to ccbc user

---

CHANGELOG.md
db/sqitch.plan
helm/app/Chart.yaml
package.json

Implements [NDT-709]
[NDT-709]: https://connectivitydivision.atlassian.net/browse/NDT-709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update crunchy-postgres version

---

.github/workflows/build.yaml

fix: set proper cache-to

---

app/backend/lib/awsCommon.ts
app/server.ts

Implements [NDT-717]
[NDT-717]: https://connectivitydivision.atlassian.net/browse/NDT-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: disable logger

---

CHANGELOG.md
app/backend/lib/map/map.ts
app/schema/schema.graphql
app/tests/backend/lib/map/map.test.ts
db/deploy/tables/application_map_data.sql
db/revert/tables/application_map_data.sql
db/sqitch.plan
package.json

Implements [NDT-719]
[NDT-719]: https://connectivitydivision.atlassian.net/browse/NDT-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: cache application map data

---

helm/app/values-dev.yaml

Implements [NDT-730]
[NDT-730]: https://connectivitydivision.atlassian.net/browse/NDT-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: increase dev db storage

---

CHANGELOG.md
app/components/Review/widgets/FileWidget.tsx
db/sqitch.plan
package.json

Implements [NDT-644]
[NDT-644]: https://connectivitydivision.atlassian.net/browse/NDT-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show Received from RFI

---

CHANGELOG.md
app/formSchema/uiSchema/analyst/assessmentsUiSchema.ts
app/lib/theme/widgets/SelectWidget.tsx
db/sqitch.plan
package.json

Implements [NDT-680]
[NDT-680]: https://connectivitydivision.atlassian.net/browse/NDT-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow selects to not have null value

---

CHANGELOG.md
app/components/Analyst/History/HistoryContent.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
db/sqitch.plan
package.json

Implements [[NDT-229](https://connectivitydivision.atlassian.net/browse/NDT-229)]
[NDT-229]: https://connectivitydivision.atlassian.net/browse/NDT-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: show package change details on history

---

CHANGELOG.md
app/backend/lib/excel_import/claims.ts
app/backend/lib/excel_import/community_progress_report.ts
app/backend/lib/excel_import/milestone.ts
app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
app/components/Analyst/Project/Milestones/MilestonesForm.tsx
db/sqitch.plan
package.json

Implements [[NDT-699](https://connectivitydivision.atlassian.net/browse/NDT-699)]
[NDT-699]: https://connectivitydivision.atlassian.net/browse/NDT-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NDT-699-Community-Progress-Report-not-Archiving-when-removed-from-Portal

---

CHANGELOG.md
app/components/Review/fields/ReviewFieldTemplate.tsx
app/formSchema/uiSchema/cbc/editLocationsUiSchema.ts
app/pages/analyst/cbc/[cbcId].tsx
db/sqitch.plan
package.json

Implements [NDT-510]
[NDT-510]: https://connectivitydivision.atlassian.net/browse/NDT-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: make cbc project locations take full width

---

CHANGELOG.md
app/pages/analyst/application/[applicationId]/summary.tsx
db/sqitch.plan
package.json

Implements [NDT-589]
[NDT-589]: https://connectivitydivision.atlassian.net/browse/NDT-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: reduce space on summary page intro

---

helm/app/values-dev.yaml

chore: increase dev storage

---

CHANGELOG.md
app/formSchema/analyst/changeRequest.ts
app/formSchema/analyst/projectInformation.ts
app/formSchema/uiSchema/analyst/changeRequestUiSchema.ts
app/formSchema/uiSchema/analyst/projectInformationUiSchema.ts
db/sqitch.plan
package.json

Implements [NDT-716]
[NDT-716]: https://connectivitydivision.atlassian.net/browse/NDT-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow kml uploads in portal

---

CHANGELOG.md
app/components/Analyst/History/HistoryContent.tsx
db/sqitch.plan
package.json

Implements [[NDT-674](https://connectivitydivision.atlassian.net/browse/NDT-674)]
[NDT-674]: https://connectivitydivision.atlassian.net/browse/NDT-674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: distorted conditional approval history

---

CHANGELOG.md
app/backend/lib/ches/sendEmail.ts
app/backend/lib/ches/sendEmailMerge.ts
db/sqitch.plan
package.json

Implements [[NDT-696](https://connectivitydivision.atlassian.net/browse/NDT-696)]
[NDT-696]: https://connectivitydivision.atlassian.net/browse/NDT-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: email sender wrongly set to dev in prod

---

CHANGELOG.md
app/components/Analyst/History/HistoryFilter.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
db/sqitch.plan
package.json

Implements [NDT-675]
[NDT-675]: https://connectivitydivision.atlassian.net/browse/NDT-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update and group history filters

---

helm/app/values-dev.yaml

chore: increase dev backup storage size

---

CHANGELOG.md
app/components/Analyst/CBC/NavigationSidebar.tsx
app/components/Analyst/NavigationSidebar.tsx
app/components/AnalystDashboard/AllDashboard.tsx
app/cypress/e2e/analyst/dashboard.cy.js
app/tests/pages/analyst/dashboard.test.tsx
db/sqitch.plan
package.json

Implements [NDT-669]
[NDT-669]: https://connectivitydivision.atlassian.net/browse/NDT-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update expanded row design

---

CHANGELOG.md
app/components/Analyst/Map/SummaryMap.tsx
db/sqitch.plan
package.json

Implements [NDT-741]
[NDT-741]: https://connectivitydivision.atlassian.net/browse/NDT-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: optional chaining on markers

---

CHANGELOG.md
app/data/externalConstants.ts
db/sqitch.plan
package.json

Implements [[NDT-750](https://connectivitydivision.atlassian.net/browse/NDT-750)]
[NDT-750]: https://connectivitydivision.atlassian.net/browse/NDT-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Pm assessment link

---

.github/actions/dev-env-setup/action.yml
.github/workflows/test-code.yaml
CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
package.json

Implements [[NDT-756](https://connectivitydivision.atlassian.net/browse/NDT-756)]
[NDT-756]: https://connectivitydivision.atlassian.net/browse/NDT-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: sow communities not showing up

---

CHANGELOG.md
app/backend/lib/dashboard/column_options.ts
app/backend/lib/dashboard/dashboard.ts
app/backend/lib/dashboard/header.ts
app/backend/lib/dashboard/util.ts
app/lib/helpers/ccbcSummaryGenerateFormData.ts
package.json

Implements [NDT-761]
[NDT-761]: https://connectivitydivision.atlassian.net/browse/NDT-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add geo name id to dashboard export

---

.github/workflows/deploy_feature.yaml
.github/workflows/jira-feat.yaml

Implements [[NDT-744](https://connectivitydivision.atlassian.net/browse/NDT-744)]
[NDT-744]: https://connectivitydivision.atlassian.net/browse/NDT-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: not transitioning PRs which are in-progress

---

.github/workflows/test-zap.yaml

Implements [NDT-748]
[NDT-748]: https://connectivitydivision.atlassian.net/browse/NDT-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update zaproxy image while weekly is bugged

---

.github/workflows/test-code.yaml
app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
app/tests/pages/analyst/cbc/[cbcId]/[section].test.tsx

Implements [NDT-753]
[NDT-753]: https://connectivitydivision.atlassian.net/browse/NDT-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test (ci): jest reliability

---

.github/workflows/build.yaml
helm/feature/templates/deployment.yaml

chore: revert db build for feature env

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
package.json

Implements [[NDT-727](https://connectivitydivision.atlassian.net/browse/NDT-727)]
[NDT-727]: https://connectivitydivision.atlassian.net/browse/NDT-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add cbc zones to all dashboard

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
package.json

Implements [[NDT-728](https://connectivitydivision.atlassian.net/browse/NDT-728)]
[NDT-728]: https://connectivitydivision.atlassian.net/browse/NDT-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add zones-cbc to excel download

---

CHANGELOG.md
app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryFileRow.tsx
app/components/Analyst/History/HistoryRfiFile.tsx
app/tests/pages/analyst/application/[applicationId]/history.test.tsx
package.json

Implements [[NDT-692](https://connectivitydivision.atlassian.net/browse/NDT-692)]
[NDT-692]: https://connectivitydivision.atlassian.net/browse/NDT-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: history for rfi file uploads to show correct category

---

CHANGELOG.md
app/backend/lib/sow-upload.ts
app/backend/lib/sow_import/tab_7.ts
app/components/Analyst/ChangeModal.tsx
app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx
app/components/Review/Components.tsx
app/components/Review/fields/ReviewFieldTemplate.tsx
app/formSchema/analyst/summary/funding.ts
app/formSchema/uiSchema/summary/fundingUiSchema.ts
app/formSchema/uiSchema/summary/reviewUiSchema.ts
app/lib/helpers/ccbcSummaryGenerateFormData.ts
app/lib/theme/FieldTemplate.tsx
app/pages/analyst/application/[applicationId]/edit/[section].tsx
app/pages/analyst/application/[applicationId]/summary.tsx
app/schema/mutations/application/saveFnhaContributionMutation.ts
app/schema/schema.graphql
app/tests/pages/analyst/application/[applicationId]/edit/[section].test.tsx
app/tests/pages/analyst/application/[applicationId]/summary.test.tsx
db/deploy/mutations/save_fnha_contribution.sql
db/deploy/tables/application_fnha_contribution.sql
db/revert/mutations/save_fnha_contribution.sql
db/revert/tables/application_fnha_contribution.sql
db/sqitch.plan
package.json

Implements [[NDT-691](https://connectivitydivision.atlassian.net/browse/NDT-691)]
[NDT-691]: https://connectivitydivision.atlassian.net/browse/NDT-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add fnha contribution to summary page

---

CHANGELOG.md
app/lib/helpers/ccbcSummaryGenerateFormData.ts
db/sqitch.plan
package.json

Implements [NDT-738]
[NDT-738]: https://connectivitydivision.atlassian.net/browse/NDT-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: incorrect source label for date agreement signed

---

CHANGELOG.md
app/pages/applicantportal/dashboard.tsx
app/pages/applicantportal/index.tsx
package.json

Implements [NDT-783]
[NDT-783]: https://connectivitydivision.atlassian.net/browse/NDT-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update email to connectingcommunitiesbc

---

CHANGELOG.md
app/backend/lib/dashboard/util.ts
app/tests/backend/lib/dashboard/util.test.ts
package.json

Implements [NDT-764]
[NDT-764]: https://connectivitydivision.atlassian.net/browse/NDT-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add conversion from closed to not selected

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
package.json

Implements [NDT-785]
[NDT-785]: https://connectivitydivision.atlassian.net/browse/NDT-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cc on cbc download on dashboard

---

CHANGELOG.md
app/backend/lib/reporting/util.ts
package.json

Implements [[NDT-780](https://connectivitydivision.atlassian.net/browse/NDT-780)]
[NDT-780]: https://connectivitydivision.atlassian.net/browse/NDT-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dashboard download to show correct value for closed

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx
package.json

Implements [NDT-747]
[NDT-747]: https://connectivitydivision.atlassian.net/browse/NDT-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: multi select on all dashboard

---

helm/ccbc-tools/templates/sysdigteam.yaml

chore: sysdig offboarding

---

CHANGELOG.md
app/backend/lib/reporting/gcpe.ts
app/backend/lib/reporting/util.ts
package.json

Implements [[NDT-807](https://connectivitydivision.atlassian.net/browse/NDT-807)]
[NDT-807]: https://connectivitydivision.atlassian.net/browse/NDT-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: wrong source for connected coast data

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
package.json

Implements [[NDT-821](https://connectivitydivision.atlassian.net/browse/NDT-821)]
[NDT-821]: https://connectivitydivision.atlassian.net/browse/NDT-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: match excel download connected coast case

---

CHANGELOG.md
app/backend/lib/linkPreview.ts
app/schema/schema.graphql
db/deploy/mutations/update_announcement.sql
db/deploy/mutations/update_announcement@1.246.0.sql
db/revert/mutations/update_announcement@1.246.0.sql
db/sqitch.plan
package.json

fix: announcement duplicate save calls

---

CHANGELOG.md
app/backend/lib/reporting/util.ts
app/tests/backend/lib/reporting/util.test.ts
package.json

Implements [[NDT-825](https://connectivitydivision.atlassian.net/browse/NDT-825)]
[NDT-825]: https://connectivitydivision.atlassian.net/browse/NDT-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: status from approved to Agreement Signed in GCPE

---

CHANGELOG.md
app/lib/theme/widgets/custom/CommunitySourceWidget.tsx
app/pages/analyst/cbc/[cbcId].tsx
app/tests/components/Form/CommunitySourceWidget.test.tsx
package.json

Implements [[NDT-819](https://connectivitydivision.atlassian.net/browse/NDT-819)]
[NDT-819]: https://connectivitydivision.atlassian.net/browse/NDT-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: enable select geographic data by geographic name

---

CHANGELOG.md
app/backend/lib/cbc/cbc.ts
app/backend/lib/cbc/create.ts
app/components/Analyst/CBC/CbcCreateForm.tsx
app/components/Analyst/CBC/CbcCreateIcon.tsx
app/components/Analyst/CBC/CbcCreateModal.tsx
app/components/AnalystDashboard/AllDashboard.tsx
app/pages/analyst/cbc/[cbcId].tsx
app/server.ts
app/tests/backend/lib/cbc/cbc.test.ts
app/tests/pages/analyst/dashboard.test.tsx
package.json

Implements [NDT-322]
[NDT-322]: https://connectivitydivision.atlassian.net/browse/NDT-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create cbc project from dashboard

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
app/backend/lib/reporting/util.ts
app/lib/helpers/ccbcSummaryGenerateFormData.ts
package.json

Implements [[NDT-786](https://connectivitydivision.atlassian.net/browse/NDT-786)]
[NDT-786]: https://connectivitydivision.atlassian.net/browse/NDT-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: fix data issues in xls download

---

CHANGELOG.md
app/backend/lib/logout.ts
package.json

fix: azure logout

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
app/tests/backend/lib/dashboard/testData.ts
package.json

Implements [[NDT-836](https://connectivitydivision.atlassian.net/browse/NDT-836)]
[NDT-836]: https://connectivitydivision.atlassian.net/browse/NDT-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: zones in excel download for CCBC

---

CHANGELOG.md
app/components/Analyst/Map/SummaryMap.tsx
package.json

Implements [[NDT-795](https://connectivitydivision.atlassian.net/browse/NDT-795)]
[NDT-795]: https://connectivitydivision.atlassian.net/browse/NDT-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove layer hover text from map

---

CHANGELOG.md
app/pages/analyst/dashboard.tsx
package.json

chore: add profiler to all dashboard

---

CHANGELOG.md
app/backend/lib/map/map.ts
package.json

Implements [NDT-796]
[NDT-796]: https://connectivitydivision.atlassian.net/browse/NDT-796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove current and upgraded network from map

---

CHANGELOG.md
app/components/Analyst/RFI/RFIAnalystUpload.tsx
app/lib/helpers/useTemplateUpload.ts
app/lib/theme/widgets/FileWidget.tsx
app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx
app/tests/components/Analyst/RFI/RFIAnalystUpload.test.ts
app/tests/components/Form/FileWidget.test.tsx
package.json

Implements [[NDT-828](https://connectivitydivision.atlassian.net/browse/NDT-828)]
[NDT-828]: https://connectivitydivision.atlassian.net/browse/NDT-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: template 9 file delete to not save data extracted

---

CHANGELOG.md
app/components/Analyst/History/HistoryFileRow.tsx
app/components/Analyst/History/HistoryRfiFile.tsx
package.json

Implements [NDT-844]
[NDT-844]: https://connectivitydivision.atlassian.net/browse/NDT-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 844 history for ccbc 030052 gives 500

---

CHANGELOG.md
app/formSchema/uiSchema/cbc/tombstoneUiSchema.ts
package.json

Implements [NDT-830]
[NDT-830]: https://connectivitydivision.atlassian.net/browse/NDT-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: select an intake on cbc dashboard

---

CHANGELOG.md
app/backend/lib/gis-upload.ts
app/components/Analyst/History/HistoryFileUpload.tsx
app/components/Analyst/History/UploadHistory.tsx
app/pages/analyst/gis/coverages.tsx
app/pages/analyst/gis/index.tsx
app/schema/schema.graphql
app/tests/pages/analyst/gis/index.test.tsx
db/deploy/tables/gis_data_001_add_file_name.sql
db/revert/tables/gis_data_001_add_file_name.sql
db/sqitch.plan
package.json

Implements [[NDT-643](https://connectivitydivision.atlassian.net/browse/NDT-643)]
[NDT-643]: https://connectivitydivision.atlassian.net/browse/NDT-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: list GIS upload history

---

.github/pull_request_template.md

Implements [NDT-862]
[NDT-862]: https://connectivitydivision.atlassian.net/browse/NDT-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Make automatic rebasing enabled by default

---

.github/workflows/release-process.yaml
conn-ticket-queue/src/lib/merge.ts
conn-ticket-queue/src/routes/api/queue/+server.ts

Implements [NDT-856]
[NDT-856]: https://connectivitydivision.atlassian.net/browse/NDT-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 856 update ticket queue so it doesn t get stuck when a pr does not exist

---

.github/pull_request_template.md

chore: Fixed pull_request_template.md

---

.github/workflows/deploy.yaml
conn-ticket-queue/package.json
conn-ticket-queue/yarn.lock

Implements [NDT-833]
[NDT-833]: https://connectivitydivision.atlassian.net/browse/NDT-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Updated dependencies

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
app/backend/lib/dashboard/util.ts
app/backend/lib/reporting/gcpe.ts
app/formSchema/analyst/summary/funding.ts
app/formSchema/uiSchema/summary/fundingUiSchema.ts
app/formSchema/uiSchema/summary/reviewUiSchema.ts
app/lib/helpers/ccbcSummaryGenerateFormData.ts
package.json

Implements [[NDT-860](https://connectivitydivision.atlassian.net/browse/NDT-860)]
[NDT-860]: https://connectivitydivision.atlassian.net/browse/NDT-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: funding data for CCBC in gcpe report

---

CHANGELOG.md
app/backend/lib/ches/sendEmail.ts
app/backend/lib/dashboard/dashboard_export.ts
app/tests/backend/lib/dashboard/dashboard_export.test.ts
package.json

Implements [NDT-737]
[NDT-737]: https://connectivitydivision.atlassian.net/browse/NDT-737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: email copy of dashboard export to dev inbox

---

.github/workflows/schemaspy.yaml

Implements [NDT-845]
[NDT-845]: https://connectivitydivision.atlassian.net/browse/NDT-845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: schema spy

---

CHANGELOG.md
app/components/Analyst/ProjectNavigationSidebar.tsx
app/components/Analyst/SideMap.tsx
app/components/Review/widgets/MapWidget.tsx
app/pages/analyst/application/[applicationId]/summary.tsx
app/tests/components/Analyst/ProjectNavigationSidebar.test.tsx
package.json

Implements [NDT-745]
[NDT-745]: https://connectivitydivision.atlassian.net/browse/NDT-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 745 keep current location of form when moving between applications

---

CHANGELOG.md
app/backend/lib/reporting/gcpe.ts
app/lib/helpers/ccbcSummaryGenerateFormData.ts
package.json

Implements [NDT-858]
[NDT-858]: https://connectivitydivision.atlassian.net/browse/NDT-858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: conditional approval date on gcpe report

---

.github/workflows/deploy.yaml
.github/workflows/main.yaml
CHANGELOG.md
package.json

Implements [NDT-893]
[NDT-893]: https://connectivitydivision.atlassian.net/browse/NDT-893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: tag version

---

CHANGELOG.md
app/sentry.client.config.ts
package.json

chore: temp disable sentry

---

.github/workflows/deploy_feature.yaml

Implements [NDT-886]
[NDT-886]: https://connectivitydivision.atlassian.net/browse/NDT-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: transition id from dev to po review

---

CHANGELOG.md
app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx
app/tests/pages/applicantportal/form/[id]/rfi/[applicantRfiId].test.tsx
package.json

Implements [NDT-812]
[NDT-812]: https://connectivitydivision.atlassian.net/browse/NDT-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show success/error messages on applicant rfi

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
package.json

Implements [NDT-879]
[NDT-879]: https://connectivitydivision.atlassian.net/browse/NDT-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: zone filter to some

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
package.json

Implements [[NDT-888](https://connectivitydivision.atlassian.net/browse/NDT-888)]
[NDT-888]: https://connectivitydivision.atlassian.net/browse/NDT-888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove unresponsive caret icon in all dashboard

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx
package.json

Implements [[NDT-867](https://connectivitydivision.atlassian.net/browse/NDT-867)]
[NDT-867]: https://connectivitydivision.atlassian.net/browse/NDT-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: enable filters by default in all dashboard

---

CHANGELOG.md
app/lib/helpers/ccbcSummaryGenerateFormData.ts
package.json

Implements [NDT-892]
[NDT-892]: https://connectivitydivision.atlassian.net/browse/NDT-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: intakes greater than 5 are rolling

---

CHANGELOG.md
app/components/AnalystDashboard/ProjectChangeLog.tsx
package.json

Implements [NDT-938]
[NDT-938]: https://connectivitydivision.atlassian.net/browse/NDT-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove projectNumber from log

---

app/cypress/e2e/analyst/application/[applicationId]/project.cy.js

Implements [NDT-928]
[NDT-928]: https://connectivitydivision.atlassian.net/browse/NDT-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: project e2e

---

CHANGELOG.md
app/pages/applicantportal/dashboard.tsx
app/pages/applicantportal/index.tsx
app/tests/pages/applicantportal/dashboard.test.tsx
app/tests/pages/applicantportal/index.test.tsx
package.json

Implements [NDT-964]
[NDT-964]: https://connectivitydivision.atlassian.net/browse/NDT-964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update intake closing date

---

CHANGELOG.md
app/components/AnalystDashboard/ProjectChangeLog.tsx
app/tests/pages/analyst/change-log.test.tsx
package.json

Implements [[NDT-935](https://connectivitydivision.atlassian.net/browse/NDT-935)]
[NDT-935]: https://connectivitydivision.atlassian.net/browse/NDT-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add virtualization to change log

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboardDetailPanel.tsx
app/cypress/e2e/analyst/dashboard.cy.js
package.json

Implements [NDT-927]
[NDT-927]: https://connectivitydivision.atlassian.net/browse/NDT-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: all dashboard detail panel display

---

CHANGELOG.md
app/components/AnalystDashboard/ProjectChangeLog.tsx
package.json

Implements [NDT-933]
[NDT-933]: https://connectivitydivision.atlassian.net/browse/NDT-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: user drop down to change log

---

app/tests/pages/analyst/admin/application-intakes.test.tsx

Implements [[NDT-979](https://connectivitydivision.atlassian.net/browse/NDT-979)]
[NDT-979]: https://connectivitydivision.atlassian.net/browse/NDT-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: failing intake tests

---

CHANGELOG.md
README.md
docs/FAQs/Update_Summary_Page_For_New_Application.md
docs/FAQs/index.md
package.json

Implements [NDT-949]
[NDT-949]: https://connectivitydivision.atlassian.net/browse/NDT-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Added readme for updating summary page for new applications

---

CHANGELOG.md
app/backend/lib/dashboard/column_options.ts
app/backend/lib/dashboard/dashboard.ts
app/backend/lib/dashboard/header.ts
app/tests/backend/lib/dashboard/dashboard.test.ts
package.json

Implements [NDT-921]
[NDT-921]: https://connectivitydivision.atlassian.net/browse/NDT-921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: added proposed completion date to xls export

---

CHANGELOG.md
app/backend/lib/reporting/gcpe.ts
package.json

Implements [NDT-976]
[NDT-976]: https://connectivitydivision.atlassian.net/browse/NDT-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: removed archived CBC projects

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
app/backend/lib/dashboard/util.ts
app/components/AnalystDashboard/AllDashboard.tsx
app/components/Review/fields/ReviewInlineArrayField.tsx
app/formSchema/uiSchema/cbc/locationsUiSchema.ts
package.json

Implements [[NDT-875](https://connectivitydivision.atlassian.net/browse/NDT-875)]
[NDT-875]: https://connectivitydivision.atlassian.net/browse/NDT-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: zone order for cbc

---

CHANGELOG.md
app/backend/lib/dashboard/dashboard.ts
package.json

Implements [NDT-948]
[NDT-948]: https://connectivitydivision.atlassian.net/browse/NDT-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fnha funding on dashboard export

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboardDetailPanel.tsx
package.json

Implements [[NDT-895](https://connectivitydivision.atlassian.net/browse/NDT-895)]
[NDT-895]: https://connectivitydivision.atlassian.net/browse/NDT-895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: highlight issue when spaces present on communities

---

CHANGELOG.md
app/components/Analyst/Assessments/AssessmentsForm.tsx
package.json

Implements [[NDT-986](https://connectivitydivision.atlassian.net/browse/NDT-986)]
[NDT-986]: https://connectivitydivision.atlassian.net/browse/NDT-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: assessment page data update with project navigation

---

helm/app/templates/cronJobs/trigger-shp-import.yaml
helm/app/values-dev.yaml
helm/app/values.yaml

Implements [[NDT-923](https://connectivitydivision.atlassian.net/browse/NDT-923)]
[NDT-923]: https://connectivitydivision.atlassian.net/browse/NDT-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: disable cron-shp on dev

---

app/.happo.js

First try
Implements [NDT-940]
[NDT-940]: https://connectivitydivision.atlassian.net/browse/NDT-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: disable safari, freeze animation, reduce motion

---

.github/workflows/main.yaml
CHANGELOG.md
helm/app/templates/cronJobs/trigger-community-report-notification.yaml
helm/app/templates/cronJobs/trigger-milestone-notification.yaml
helm/app/values-dev.yaml
helm/app/values.yaml
package.json

Implements [NDT-962]
[NDT-962]: https://connectivitydivision.atlassian.net/browse/NDT-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: enable deploy for milestone and community

---

helm/app/values-prod.yaml

Implements [NDT-997]
[NDT-997]: https://connectivitydivision.atlassian.net/browse/NDT-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: increase prod crunchy volume size

---

CHANGELOG.md
app/backend/lib/map/map.ts
app/backend/lib/map/utils.ts
package.json

Implements [[NDT-957](https://connectivitydivision.atlassian.net/browse/NDT-957)]
[NDT-957]: https://connectivitydivision.atlassian.net/browse/NDT-957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: kml not showing on map

---

CHANGELOG.md
app/backend/lib/reporting/gcpe.ts
package.json

Implements [[NDT-978](https://connectivitydivision.atlassian.net/browse/NDT-978)]
[NDT-978]: https://connectivitydivision.atlassian.net/browse/NDT-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NDT-978-Display-Projects-in-Numerical-Order-in-GCPE-List

---

CHANGELOG.md
app/.happo.js
app/cypress.config.ts
app/cypress/e2e/admin/list-of-analysts.cy.js
app/cypress/e2e/analyst/application/[applicationId].cy.js
app/cypress/e2e/analyst/dashboard.cy.js
app/cypress/e2e/analyst/gis/upload.cy.js
app/cypress/e2e/applicantportal/dashboard.cy.js
app/cypress/support/commands.js
app/cypress/support/e2e.js
app/cypress/support/screenshot-helpers.js
package.json

Implements [NDT-940]
[NDT-940]: https://connectivitydivision.atlassian.net/browse/NDT-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: refine happo

---

CHANGELOG.md
app/components/AnalystDashboard/AllDashboard.tsx
app/tests/pages/analyst/dashboard.test.tsx
package.json

Implements [NDT-981]
[NDT-981]: https://connectivitydivision.atlassian.net/browse/NDT-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 981 add funding source indicator on dashboard for cbc and ccbc projects

---

db/sqitch.plan

chore: add missing tag

---

app/cypress/e2e/analyst/application/[applicationId]/summary.cy.js
db/data/e2e/001_application_summary_announced.sql
db/data/e2e/001_application_summary_approved.sql
db/data/e2e/001_application_summary_approved_no_sow.sql
db/data/e2e/001_application_summary_conditionally_approved.sql
db/data/e2e/001_application_summary_received.sql
db/data/e2e/001_application_summary_with_milestones.sql
db/data/e2e/reset_db.sql

Implements [NDT-946]
[NDT-946]: https://connectivitydivision.atlassian.net/browse/NDT-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 946 add summary page scenario for e2 e testing

---

CHANGELOG.md
app/formSchema/uiSchema/cbc/reviewUiSchema.ts
package.json

Implements [[NDT-950](https://connectivitydivision.atlassian.net/browse/NDT-950)]
[NDT-950]: https://connectivitydivision.atlassian.net/browse/NDT-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: construction completed on ui schema

---

.github/workflows/cleanup-feature-environments.yaml
.github/workflows/nightly.yaml

Implements [NDT-1023]
[NDT-1023]: https://connectivitydivision.atlassian.net/browse/NDT-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ndt 1023 update cleanup task to clean merged

---

CHANGELOG.md
app/components/Analyst/CBC/History/CbcHistoryContent.tsx
app/components/Analyst/History/HistoryContent.tsx
app/components/Analyst/History/HistoryDetails.tsx
app/formSchema/analyst/cbc/locations.ts
app/formSchema/uiSchema/history/commonAssessment.ts
app/formSchema/uiSchema/history/technical.ts
app/utils/historyFileUtils.ts
app/utils/historyTableConfig.ts
package.json

Implements [[NDT-881](https://connectivitydivision.atlassian.net/browse/NDT-881)]
[NDT-881]: https://connectivitydivision.atlassian.net/browse/NDT-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add technical assessment data to history
