bcgov/CONN-CCBC-portal

app/components/FooterLinks.tsx, app/components/Layout.tsx, app/components/NavbarLinks.tsx, app/components/Navigation.tsx, app/components/SubHeader.tsx, app/styles/GlobalTheme.tsx
This has been bugging me for awhile, in the spirit of this sprint goal of making the page and form more polished I decided to make the header/footer items only take up the page max width.
=> feat: set max width for nav/footer items

app/pages/_app.tsx
Update Growthbook features on route change. Still seems to take about 10-30 seconds after I've turned a feature on/off but I've tested it a bunch and it seems to work well, should make for a better experience.
=> feat: update growthbook features on route change

app/tests/pages/dashboard.test.tsx, app/tests/pages/form/success.test.tsx, app/tests/pages/index.test.tsx
These are very basic jest tests since the old ones broke once we implemented Relay SSR. Currently only doing basic unauthenticated tests, I will likely have to do up a mock relay auth at some point.
=> feat: add basic pages ssr tests

app/formSchema/pages/index.ts, app/formSchema/pages/otherFundingSources.ts, app/formSchema/schema.ts, app/formSchema/uiSchema.ts, app/lib/theme/FormWithTheme.tsx, app/lib/theme/ObjectFieldTemplate.tsx, app/lib/theme/fields/ArrayFieldTemplate.tsx, app/lib/theme/fields/index.ts
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/238
This one wasn't as bad as I thought, the friction was mostly figuring out that I had to nest the `uiSchema` stuff similar to how the `otherFundingSources` page schema was nested. This page is more complex than others because it dynamically allows us to add as many new groups of fields as we want with the `Add another funding source` button, as well as remove ones though that button only shows up on the second group onward.
This required me to add the custom `ArrayFieldTemplate` renderer. Even though we are unlikely to use this for another page in this project I added custom button labels using the `ui:array-buttons` prop to make it a little more generic than just for this …
=> 238 other funding sources

.github/actions/app/action.yaml, .github/actions/dev-env-setup/action.yml, app/formSchema/pages/benefits.ts, app/formSchema/pages/budgetDetails.ts, app/formSchema/pages/declarations.ts, app/formSchema/pages/declarationsSign.ts, app/formSchema/pages/existingNetworkCoverage.ts, app/formSchema/pages/mapping.ts, app/formSchema/pages/organizationProfile.ts, app/formSchema/pages/projectPlan.ts, app/formSchema/uiSchema.ts, db/deploy/functions/session.sql, db/revert/create_roles.sql, db/test/tables/table_applications_test.sql, db/test/tables/table_connect_session_test.sql, docs/Definition_of_ Ready.md, docs/Team_Agreements.md, helm/app/.helmignore
This fixes some weird text formatting issues due to my use of `white-space: pre line` so we could have multi line titles as required in some form pages. This just removes the line breaks and turns template literals into regular strings. 
Also changed instances of the term `Applicant` to lowercase and removed oxford commas as these aren't used in government/
=> fix: form text formatting

helm/app/templates/networkPolicies/metabase-ingress.yaml
The Metabase NetworkPolicy selector uses a label that is not created by the crunchydata postgres operator. This fixes it.
References #270
=> fix(helm): metabase NetworkPolicy selector uses postgres-operator label

app/formSchema/pages/projectFunding.ts, app/formSchema/uiSchema.ts, app/lib/theme/ObjectFieldTemplate.tsx
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/282
This one was a little bit involved as I had to refactor my previously made `ui:inline` schema handling in the `ObjectFieldTemplate` so we could have more of a grid style layout to make inline fields behave like I circled in the picture. Instead of spreading out fields to fit in a `flex` layout we can specify the number of columns and then pass a `gridColumn` value to the field key.
=> 282 remove project funding

app/pages/dashboard.tsx
Turns out the need to force a network request was necessary, so this is a temporary fix for that
=> fix: prevent stale data on dashbaord

app/formSchema/pages/organizationLocation.ts, app/formSchema/uiSchema.ts, app/lib/theme/FieldTemplate.tsx, app/lib/theme/widgets/FieldLabel.tsx
Updated the postal code example formatting and added a new `ui:options` attribute `ignoreOptional` which removes the `(optional)` to the end of non required fields if desired.
=> feat: add ignoreoptional option

app/lib/theme/widgets/FileWidget.tsx
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/266
Everything else in this ticket was completed in other tickets except for the failed upload error warning. This can be easily tested by passing in junk data to the `handleChange` function such as a 0 for `applicationId`.
=> feat: add file widget error handling

app/schema/schema.graphql, db/deploy/tables/attachment.sql, db/deploy/tables/attachment_001.sql, db/revert/tables/attachment_001.sql, db/sqitch.plan, db/verify/tables/attachment_001.sql
Added some new columns to `attachment` table and sqitch didn't know about them. Instead of rebasing I am trying a way that Dylan suggested that will be good if we have to add columns when in prod. Basically make a numbered file in sqitch `attachment_001` `with alter table add column` and add to sqitch plan.
I tested pushing this to dev so it works, will need to merge in so we can deploy db to dev again (sorry I didn't know a better way).
=> Fix migration

app/backend/lib/graphql/authenticationPgSettings.ts, app/schema/schema.graphql, db/deploy/functions/session.sql, db/deploy/types/keycloak_jwt.sql, db/revert/tables/applications/remove_unique_owner.sql
Discussed ticket 169 with Junmin. He suggested to use `identity_provider` and `preferredUsername` as main identifiers, and do not store idir, bceid_basic or bceid_business because Keycloak is using `preferredUsername` as `keycloak_username`, and it is unique user identifier.
Code changes:
- added `identity_provider` in keycloak_jwt type
- updated code to populate `identity_provider` from JWT
- updated revert action for `applications` table that was blocking `sqitch revert` and `sqitch deploy`
=> detect and persist identity provider

app/components/Navigation.tsx, app/cypress/integration/index.spec.js
Hide `Dashboard` link in the header for un-authenticated users
=> show Dashboard link only for logged in

helm/app/templates/PostgresCluster.yaml, helm/app/values.yaml
Increases the app replicas to 3 for high availability and lowers requests
of all pods to 10m across the board.
Do not merge until request to increase namespace limits is approved.
=> feat: configure for HA

helm/app/values.yaml
Increases the netapp file backup size from 64Mi to 2Gi
=> chore: increase netapp file backup volume size

app/formSchema/pages/alternateContact.ts, app/formSchema/pages/authorizedContact.ts, app/formSchema/uiSchema.ts, app/lib/theme/widgets/TextAreaWidget.tsx, app/lib/theme/widgets/TextWidget.tsx
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/421
Adds max lengths to all fields in authorized and alternate contact pages, as well as a max length of 32000 for any text fields that don't have one set.
=> 421 - error saving

app/components/Review/Review.tsx, app/components/Review/Table.tsx, app/lib/theme/widgets/FileWidget.tsx
Fixes a bug where if a user deletes a file it would still store an empty array in the field, causing required fields to incorrectly validate as filled. This is what caused the missing required field Mars flagged on the review page in this ticket: 
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/277
=> fix: filewidget delete empty array validation bug

app/cypress/integration/index.spec.js
A spelling error that was fixed in a recently merged PR broke the end to end test, this fixes that.
=> fix: field id spelling in e2e test

app/components/Form/ApplicationForm.tsx, app/components/Review/ReviewField.tsx, app/components/Review/index.ts, app/formSchema/pages/review.ts, app/formSchema/pages/submission.ts, app/formSchema/uiSchema.ts, app/lib/theme/FormWithTheme.tsx, app/lib/theme/fields/SubmissionDescriptionField.tsx, app/lib/theme/fields/index.ts, app/pages/dashboard.tsx, app/pages/form/[id]/[page].tsx, app/pages/index.tsx, app/schema/schema.graphql, app/tests/components/Form/ApplicationForm.test.tsx, app/tests/pages/dashboard.test.tsx, app/tests/pages/index.test.tsx, db/deploy/functions/add_ccbc_id.sql, db/deploy/functions/open_intake.sql, db/deploy/tables/add_intake_table.sql, db/revert/functions/open_intake.sql, db/sqitch.plan, db/test/unit/functions/open_intake_test.sql, db/verify/functions/open_intake.sql
PR to add intake dates that match the real intake dates in the DB.
References 314
- Current Intake
- Current Intake
- Draft Status = Current Intake
- Submit Status = My intake
- Submit Status = My intake
_(Include any notes you have about this pull request)_
=> 314 dynamic intakes on pages

app/components/Form/ApplicationForm.tsx, app/tests/components/Form/ApplicationForm.test.tsx
This PR changes the `Save and continue` button text to `Continue` if the application status is withdrawn as well as fixes the page routing that was refactored to happen upon completion of the update application mutation. The button text will remain `Continue` even on the final submission page so there isn't any confusion.
=> View withdrawn application continue button fix

app/components/Navigation.tsx, app/cypress.json, app/next.config.js
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/board
Sets the nextjs basepath to `/applicantportal` and a redirect from `/` to `applicantportal` as well as the cypress base path.
=> 463 reroute

app/backend/lib/sso-middleware.ts
One thing we forgot to update in #532
=> fix: logged in user should be redirected to '/applicantportal/dashboard'

app/formSchema/pages/authorizedContact.ts, app/formSchema/pages/organizationLocation.ts, app/formSchema/pages/otherFundingSources.ts, app/formSchema/pages/techSolution.ts, app/formSchema/uiSchema.ts, app/lib/theme/FieldTemplate.tsx, app/lib/theme/widgets/FieldLabel.tsx
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/415
@wenzowski I added `altOptionalText` to `ui:options` so we can override the optional text as you asked. I decided to keep the `hideOptional` flag to hide the label on non required fields but I'm open to other suggestions.
=> 415 - Switch up some requireds, optionals, & if applicables

Infrastructure/README.md, Infrastructure/main.tf, Infrastructure/variable.tf
- updated terraform scripts to provision new s3 bucket;
- updated README with steps how to provision new s3 buckets if needed;
=> 436 Provision s3 bucket for database backups

cog.toml
adds a `cog.toml` to ignore merge commits
=> ci: ignore merge commit formatting

app/components/FooterLinks.tsx, app/cypress/integration/index.spec.js, app/tests/components/FooterLinks.test.tsx
Elliott asked me to change this to `Program details` in the footer.
=> Change footer project details to program details

app/formSchema/uiSchema/pages/supportingDocuments.ts
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/454
Change the location of the `otherSupportingMaterials` `(if applicable)` field as requested in this ticket.
=> refactor: change field (if applicable) location

app/Dockerfile, db/Dockerfile
The time travel feature was added, but mock_schema was not deployed, so the time travel does not work in dev and test environments.
This PR fixes the issue.
=> fix: using correct dockerfile to copy mock schema

helm/app/values-dev.yaml
This is making our dev deploy fail unless you manually drop the schema before redeploying
=> fix: in dev environment, drop mocks schema before redeploying

app/components/Form/ApplicationForm.tsx, app/tests/components/Form/ApplicationForm.test.tsx
Fix for submit button being disabled if all acknowledgements aren't checked
=> fix: submit button is disabled if acknowledgements not checked

app/components/Review/ReviewTheme.tsx, app/cypress/integration/index.spec.js, app/formSchema/pages/alternateContact.ts, app/formSchema/pages/authorizedContact.ts, app/formSchema/pages/benefits.ts, app/formSchema/pages/contactInformation.ts, app/formSchema/pages/organizationProfile.ts, app/formSchema/uiSchema/pages/alternateContact.ts, app/formSchema/uiSchema/pages/authorizedContact.ts, app/formSchema/uiSchema/pages/benefits.ts, app/formSchema/uiSchema/pages/contactInformation.ts, app/formSchema/uiSchema/pages/estimatedProjectEmployment.ts, app/formSchema/uiSchema/pages/organizationProfile.ts, app/lib/theme/widgets/NumberWidget.tsx, app/lib/theme/widgets/NumericStringWidget.tsx, app/lib/theme/widgets/TextWidget.tsx, app/lib/theme/widgets/index.ts, app/tests/components/Form/NumberWidget.test.tsx, app/tests/components/Form/NumericStringWidget.test.tsx
Other than the change above, this PR contains the following refactor:
- `NumberWidget` is used by default for all numbers
- Added a `NumericStringWidget`, taking code out of `NumberWidget`
=> feat: number of households allow decimals

.github/pull_request_template.md
Implements #441 
The PR templates don't support custom titles, as the issues templates does. 
As per the [github docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#pull-request-templates), PR templates only display the markdown's contents in the PR body.
=> chore: fix PR template

.bin/install-gitleaks-linux-x64.sh
Hotfix for Gitleaks failing due to a new release: https://github.com/zricethezav/gitleaks/releases/tag/v8.14.1
Should we lock in a version and change how the `install-gitleaks-linux-x64.sh` script is handled?
=> chore: update gitleaks to v8.14.1

app/components/NavbarLinks.tsx, app/components/Navigation.tsx, app/pages/index.tsx, app/styles/GlobalTheme.tsx, app/tests/components/Form/ApplicationFormStatus.test.tsx, app/tests/jest-setup.ts, app/tests/pages/form/success.test.tsx, app/tests/pages/index.test.tsx, db/data/dev/001_intake.sql, db/data/test/001_intake.sql
Implements #699 + adds second intake in dev and test data
=> feat: add callout displaying intake state on landing page

db/deploy/computed_columns/form_data_is_editable.sql, db/test/unit/computed_columns/application_project_name_test.sql, db/test/unit/computed_columns/form_data_is_editable_test.sql
Implements # 121
Adds the missing criteria in #121 that a draft form is  uneditable when the intake is not open.
=> feat: drafts-are-uneditable-between-intakes

app/components/Form/SubmitButtons.tsx
Implements No issue
Adds a margin to the `Return to dashboard` button to match the design
=> fix(frontend): add margin to return to dashboard button

.github/renovate.json
Implements No Issue
Adds `gitAuthor` so that commits come from the ccbc user
=> chore: add gitAuthor to renovate config

app/components/Form/ApplicationForm.tsx, app/tests/components/Form/ApplicationForm.test.tsx
This bug was from when we moved the form_data to it's own table. Just had to use the `updated_at` column from `form_data` instead of the `application` table one.
=> 697 - Returning to submit page at a later date changes the date to the previous date

.github/workflows/test-containers.yaml
I'm not sure why this wasn't failing when we merged in the PR with the new redirects though I assume that Github might just be running a bit slow today. Seems that this is caused by the target being set to `http://localhost:3000/` and the redirect to `/applicantportal` causing it to time out most of the time.
Passing twice now: 
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/3339970295/jobs/5529555075
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/3340019510/jobs/5529662044
=> Fix: OWASP Zap CI timeout

app/lib/theme/widgets/FileWidget.tsx, app/tests/components/Form/FileWidget.test.tsx
Potential fix for #807.
I managed to confirm that the mutation was sent twice, resulting in double uploads, but I am unable to manually reproduce the bug.
This ensures that `handleChange` will not trigger another mutation if the previous one is still in flight.
=> fix: FileWidget cannot call two mutations concurrently

app/components/Analyst/NavItem.tsx, app/pages/_app.tsx
Fix for the Fontawesome bug which we noticed by the padding between the text and the icon to not work properly:
Though if you refresh the page it would work again correctly. I should have caught this during development as I thought it was weird that the icons wouldn't size correctly unless they were in a container with a set width. Now they are working correctly and inherit their size from the text size of the parent container.
Also I added bold styling to the selected text which I previously missed. Anyways this might be a good one to pull and test locally to confirm it's working on another machine thank you.
=> fix: fontawesome css loading bug

helm/app/templates/routes/secureRoute.yaml
By default, the routes use the `source` strategy, which means that requests coming from the same IP are directed to the same pod. The round-robin strategy provides better load balancing between the replicas
=> feat: route uses roundrobin load balancing

CHANGELOG.md, db/sqitch.plan, package.json
Never had this issue before but the last release I just did won't [check sqitch plan release and deploy to test](https://github.com/bcgov/CONN-CCBC-portal/actions/runs/3473638332/jobs/5806761668) I believe because according to the docs we need to merge the PR locally using fast forward. 
Not sure why merging from the Github GUI worked in the past, either way our readme says to:
-once the pull request is approved, merge using fast-forward, from your local git repository. Only commits that are tagged can be deployed to test and prod.
=> chore: release v1.15.0

app/schema/schema.graphql, db/data/perf/001_applications.sql, db/deploy/computed_columns/application_rfi.sql, db/deploy/mutations/create_rfi.sql, db/deploy/tables/application_rfi_data.sql, db/deploy/tables/rfi_data.sql, db/deploy/tables/rfi_data_status_type.sql, db/revert/computed_columns/application_rfi.sql, db/revert/mutations/create_rfi.sql, db/revert/tables/application_rfi_data.sql, db/revert/tables/rfi_data.sql, db/revert/tables/rfi_data_status_type.sql, db/sqitch.plan, db/test/unit/computed_columns/application_analyst_lead_test.sql, db/test/unit/computed_columns/application_form_data_test.sql, db/test/unit/computed_columns/application_organization_name_test.sql, db/test/unit/computed_columns/application_project_name_test.sql, db/test/unit/computed_columns/form_data_is_editable_test.sql, db/test/unit/mutations/create_application_test.sql, db/test/unit/mutations/create_rfi_test.sql, db/test/unit/mutations/submit_application_test.sql, db/test/unit/mutations/update_application_form_test.sql, db/test/unit/tables/application_form_data_test.sql, db/test/unit/tables/application_test.sql, db/test/unit/tables/form_data_test.sql, db/test/unit/tables/form_test.sql, db/test/unit/tables/rfi_data_test.sql
Implements backend support for #881
P.S. Tests were updated to include TRUNCATE ... CASCADE due to new foreign key dependencies.
=> feat: db changes for RFI

app/tests/pages/analyst/application/[applicationId]/rfi/[rfiId]/index.test.tsx
I had this completed but must have reverted some work and lost it and it should be in there.
@AntBush I saw your sonarcloud failing, if you modify this test file for `/assessments` page it should pass no  problem.
=> test: add mutation test for create rfi

db/README.md, db/deploy/computed_columns/application_status.sql, db/deploy/computed_columns/application_status@1.20.0.sql, db/revert/computed_columns/application_status.sql, db/revert/computed_columns/application_status@1.20.0.sql, db/sqitch.plan
Implements #999
Metabase uses ccbc_readonly user which did not have execute permissions on function `application_status`.
This PR fixes the issue.
=> fix: added permissions to function application_status

app/formSchema/analyst/screening.ts
Made "Decision" -> "Progress instead of "Next Steps" -> "Progress" like a dingus
=> chore: fix titles on screening schema

app/components/Analyst/AnalystLayout.tsx, app/components/Analyst/ApplicationHeader.tsx, app/components/Analyst/ChangeModal.tsx, app/components/Analyst/ChangeStatus.tsx, app/components/AnalystDashboard/AnalystRow.tsx, app/components/AnalystDashboard/AnalystTable.tsx, app/components/AnalystDashboard/StatusPill.tsx, app/components/AnalystDashboard/index.tsx, app/data/statusStyles.ts, app/pages/analyst/application/[applicationId]/edit/[section].tsx, app/pages/analyst/dashboard.tsx, app/tests/pages/analyst/dashboard.test.tsx
- fix: application header title wrap
- fix: analyst dashboard width
- feat: analyst dashboard status pill component
- test: add dashboard status pill tests
- feat: change status list order
- feat: clear modal textarea on successful save
This PR fixes some minor styling issues and adds features that weren't in the acceptance criteria for the change status ticket such as styled status pills on the analyst dashboard and changing the order of the `ChangeStatus` dropdown.
=> change status updates

app/lib/theme/widgets/FileWidget.tsx, app/pages/analyst/application/[applicationId]/assessments/screening.tsx
Fixes the error deleting attachments on the assessments page after it has been saved as well as allowing archived attachments to be deleted from the form data incase someone deletes then refreshes the page without saving.
=> fix: assessment delete attachment error

app/formSchema/reviewUiSchema.tsx
Fix for #1062 `typeOfOrganization` radio widgets field displaying as 'Yes' instead of the enum value on the review pages. You can see this is fixed in the Happo diffs here:
https://happo.io/a/336/p/1172/compare/67fd91f05835a7a6a050c9b5269cfdd5c319555a/586a6822219b30bc36bd66dd0c5a5d994b9b76da
=> fix: review schema type of organization display value

app/components/BCGovTypography.tsx, app/package.json
Fix for missing bc sans package
Happo diffs:
https://happo.io/a/336/p/1172/compare/4a5a2bd7043029e607ce20e0bf4be7ad97a6e511/881509bab1e305c1f2fa1bd208e6b63cbe7e631c
=> fix: use bc-sans package

app/components/Analyst/RFI/ObjectFieldTemplate.tsx, app/components/Analyst/RFI/RfiForm.tsx, app/tests/utils/removeFalseyValuesFromObject.test.ts, app/utils/removeFalseValuesFromObject.ts, db/deploy/computed_columns/application_has_rfi_open.sql, db/test/unit/computed_columns/application_has_rfi_open_test.sql
This is branched off #1107 though we can probably just merge this one. Since we haven't made a release since the last changes to `application_has_rfi_open` no `sqitch rework` was needed.
Takes care a few issues from #1105 and #1106:
- #1105 
- #1106
- Also fixes bug if a user unchecks requested files RJSF would leave that field in the form data but set to false. So I created a function `removeFalseyValuesFromObject` to sanitize the form data of those false fields when we submit.
- Fixed a weird CSS bug on the analyst RFI side.
=> 1106 rfi files

db/deploy/computed_columns/application_has_rfi_open.sql, db/test/unit/computed_columns/application_has_rfi_open_test.sql
Implements #1105
This changed the `application_has_rfi_open` function to return false if there was no due date set. Previously it returned true so an RFI would remain open indefinitely.
Also I didn't do a `sqitch rework` on the function because we haven't made a release since #1096 which also edited this file was merged.
=> fix: reply rfi requires due date set to display on applicant portal

app/components/Navigation.tsx, app/pages/applicantportal/index.tsx, app/tests/pages/applicantportal/dashboard.test.tsx, app/tests/pages/applicantportal/index.test.tsx
Implements #806
I also added a redirect for logged in analysts/admin on the homepage `/applicantportal` route. It now redirects them to the analyst side as the dashboard button led to an error page (due to lack of permissions) as well as the issues with the nav we were trying to fix here.
=> 806-analyst-header

.bin/install-gitleaks-linux-x64.sh
I upgraded Gitleaks and slightly modified the script so it is locked into this version and shouldn't break CI when a new release comes out.
=> chore: upgrade gitleaks

app/components/Admin/AdminTabs.tsx, app/components/AnalystDashboard/DashboardTabs.tsx, app/components/AnalystDashboard/index.tsx, app/cypress/integration/analyst/admin/application-intakes.spec.js, app/cypress/integration/analyst/admin/download-attachments.spec.js, app/cypress/integration/analyst/admin/list-of-analysts.spec.js, app/cypress/integration/analyst/admin/setup.js, app/cypress/integration/analyst/dashboard.spec.js, app/pages/analyst/admin/application-intakes.tsx, app/pages/analyst/admin/download-attachments.tsx, app/pages/analyst/admin/list-of-analysts.tsx, app/pages/analyst/dashboard.tsx, app/tests/pages/analyst/admin/application-intakes.test.tsx, app/tests/pages/analyst/admin/download-attachments.test.tsx, app/tests/pages/analyst/admin/list-of-analyst.test.tsx, app/tests/pages/analyst/admin/shared-admin-tests.ts, app/tests/pages/analyst/dashboard.test.tsx, app/tests/utils/isRouteAuthorized.test.ts, app/utils/isRouteAuthorized.ts
Implements #1119
This also updates the route authorizations. Previously `ccbc_analyst` and `ccbc_admin` users could access any route in the `/analyst/(.*)` side. Now analysts can only access `/analyst/dashboard` and anything in `/analyst/application/(.*)` so that only admins can access `/analyst/admin/(.*)`.
Not sure if there is a better way to do that so we don't have to update this if we add an `analyst/some-other-page` route.
=> 1119 add admin tab

app/components/Form/ApplicationForm.tsx, app/lib/theme/fields/SubmissionDescriptionField.tsx, app/tests/components/Form/ApplicationForm.test.tsx, app/tests/pages/applicantportal/form/[id]/submission.test.tsx
Fixes bug #1146 
Pretty sure this was made before we had `received` applications so I've removed the `submitted` check to show the `intakeByIntakeId` if it exists.
I'm not sure if we will encounter this scenario unless using the time machine but if there is no open intake or no `intakeByIntakeId` we don't show a date at all.
Also I moved the submission form page tests to their own file as the `ApplicationForm` tests were getting out of control.
=> 1146 invalid datetime

app/components/Admin/AdminTabs.tsx
Fix for the admin tabs Elliott pointed out for the bottom border of the selected admin tab wouldn't disappear. 
Before:
After:
=> fix: admin tabs border top css

Infrastructure/arc_lambda/index.js
Implements #1021
Updated lambda code to fix an issue with opening archive on Windows 11 where folders in the archive were not handled properly due to leading slash /
=> fix: archive structure

app/formSchema/uiSchema/analyst/rfiUiSchema.ts
Implements multiple uploads and file types for some fields
=> fix: add flag for multiple uploads on widgets

app/package.json, app/schema/schema.graphql, db/deploy/backfill_history.sql, db/deploy/import/application.sql, db/deploy/import/application_status.sql, db/deploy/import/assessment_data.sql, db/deploy/import/attachment.sql, db/deploy/import/import_once.sql, db/deploy/import/rfi_data.sql, db/revert/backfill_history.sql, db/revert/import/application.sql, db/revert/import/application_status.sql, db/revert/import/assessment_data.sql, db/revert/import/attachment.sql, db/revert/import/import_once.sql, db/revert/import/rfi_data.sql, db/sqitch.plan
Implements #1209 
- created functions to populate record_version table with existing records 
- no duplicate records are created in record_version table;
- after deployment import function should be run once;
=> feat: backfill history

app/schema/schema.graphql, db/deploy/computed_columns/application_history.sql, db/deploy/extensions/audit_form_data.sql, db/deploy/tables/history_item.sql, db/revert/computed_columns/application_history.sql, db/revert/extenstions/audit_form_data.sql, db/revert/tables/history_item.sql, db/sqitch.plan, db/test/unit/computed_columns/application_history_test.sql, db/verify/tables/analyst_003_permissions.sql
Implements #1211
created function to return audit records related to application. Includes:
- record when application was created;
- records when application status was changed;
- records when attachments were added to the application;
- records when assessment entries were created;
- records when RFI entries were created;
=> feat: computed function for application history

app/components/Table/index.tsx
Looks like we missed a minor issue where the first click of a sort column would not save the query param though it would save fine after that. For some reason next router was behind, though I am just grabbing it from the url now which seems to be working great.
=> fix: use url query param instead of next router

.bin/install-gitleaks-linux-x64.sh
Gitleaks action was broken again, this time due to the release api url changing.
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/4361309832/jobs/7625090142
```
+ releases_api=https://api.github.com/repos/zricethezav/gitleaks/releases/tags/v8.15.3
++ curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/tags/v8.15.3
+ releases_json='{
"message": "Moved Permanently",
"url": "https://api.github.com/repositories/[11](https://github.com/bcgov/CONN-CCBC-portal/actions/runs/4361309832/jobs/7625090142#step:3:12)9190187/releases/tags/v8.15.3",
"documentation_url": "https://docs.github.com/v3/#http-redirects"
}'
+ case "$OSTYPE" in
+ arch=linux_x64
++ jq -r '.assets[] | select(.name | contains("linux_x64")) | .browser_download_url'
++ echo '{
"message": "Moved Permanently", …
```
=> chore: update gitleaks release url and bump to v8.16.0

app/backend/lib/graphql/resolveFileUpload.ts, app/tests/backend/lib/graphql/resolveFileUpload.test.ts
Implements nothing in particular, just thought it would be useful after looking at the sentry log info. Can help shed light as to whether this is a problem with our appilcation's resources (is our app hanging waiting to communicate with AWS or is it just taking a long time to setup the connection because the app in general runs slowly)
I'd love to add some log info of the pod load at the same time, but I'm not sure how to get that data in our app
=> feat: add sentry data tags to get clearer picture

Infrastructure/demo/main.tf, Infrastructure/demo/variable.tf, README.md, docs/AWS_Infrastructure.md, helm/app/templates/cronJobs/prepare-download.yaml
Implements #1272
- added separate document and linked from README;
- added demo Terraform scripts to allow user to provision necessary AWS infrastructure using any AWS account not linked to BC Gov Terraform Cloud;
=> docs: AWS infrastructure documentation and Terraform scripts demo

app/components/Review/Accordion.tsx
Implements # 1168 With the icon being consistent with the state of the accordion
=> feat: align icons to be inline with state for accordion

README.md, docs/CONTRIBUTING.md
Added a small section on Happo screenshot testing as well as a section on signed commits.
=> docs: add signed commits section to contributing doc

app/tests/pages/analyst/application/[applicationId]/edit/[section].test.tsx
Increases test coverage past 80% by adding tests to the cancel button functionality.
=> test: add test coverage for cancel button

.github/workflows/schemaspy.yaml
Replaced the `snapshot` tag with `latest`. Snapshot is the latest development build which is volatile by nature, while latest is the latest release and only behind by a few weeks at the moment. If this issue comes up again we can lock in a specific version in the future.
Successful test run:
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/4736614960/jobs/8408408417
=> fix: replace schemaspy snapshot tag with latest

app/components/Analyst/Project/ConditionalApproval/ConditionalApprovalModal.tsx, app/pages/analyst/application/[applicationId]/project.tsx, app/tests/utils/formatStatus.test.ts, app/utils/formatStatus.ts
External status in header should update instantly on change now
=> feat: update relay store for external status change

app/components/AnalystDashboard/AnalystRow.tsx, app/tests/pages/analyst/dashboard.test.tsx
Implements fix for analyst dashboard showing applicant status
=> fix: use analyst status on analyst dashboard

.github/actions/dev-env-setup/action.yml, .github/workflows/build.yaml, .github/workflows/deploy.yaml, .github/workflows/deploy_load_test.yaml, .github/workflows/deploy_tools_chart.yaml, .github/workflows/schemaspy.yaml, .github/workflows/test-code.yaml, .github/workflows/test-containers.yaml
Fixed all of the `set-state`, `set-output` and `node 12` being depreciated warnings in our workflows except for the `zaproxy` warning. Supposedly it has been fixed though I don't see a release since that was merged and all the rest of the notification have disappeared. Something to keep an eye on anyways, I created a new issue to track it: #1502 
https://github.com/zaproxy/action-full-scan/issues/61
Fixed our singluar usage of `set-output` and updated a lot of our actions. 
Full scan completed with warning removed (except for zaproxy):
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/4812941028
=> Update depreciated actions

app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx, app/components/Analyst/Project/Announcements/ViewAnnouncements.tsx, app/components/Analyst/Project/ProjectForm.tsx, app/components/Analyst/Project/widgets/CcbcIdWidget.tsx, app/schema/mutations/project/updateAnnouncement.ts, app/tests/components/Analyst/AnnouncementsForm.test.tsx, app/tests/components/Analyst/CcbcIdWidget.test.tsx, app/tests/pages/analyst/application/[applicationId]/project.test.tsx
This is working aside from the Relay store update, so you can only see changes on refresh and also only edit an announcement once without refresh due to stale id. I had some issues trying to get the store to update and also tried removing/adding a node using the [connection handler](https://relay.dev/docs/v13.0.0/guided-tour/list-data/updating-connections/).
Anyways leaving this up here in case someone needs it or wants to give it a go, if not I can figure it out when I get back thanks.
=> 1524 edit announcements

app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx, app/components/Analyst/Project/widgets/CcbcIdWidget.tsx, app/tests/components/Analyst/CcbcIdWidget.test.tsx
I noticed a quirk in the announcements form. Right now, if you've added a project to an announcement (so in the dev data, if you're on CCBC-010001 and you've added CCBC-010003) you'll see the added project in its own project. 
I've changed it so that it always adds its own ccbcNumber as the value, and additionally removes the reference to itself in the success toast and in the autocomplete.
=> feat: do not include the ccbc id of your own application

app/pages/analyst/application/[applicationId]/edit/[section].tsx, app/tests/pages/analyst/application/[applicationId]/edit/[section].test.tsx
- feat: only allow save when edit application data has changed
- test: add test for edit application save button
Implements #1504
=> 1504 application history row

helm/app/templates/PostgresCluster.yaml
Updating crunchy images to prepare for upcoming PGO 5.3 upgrade. Successful deployment to dev: 
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/4993774729/jobs/8943986428
=> chore: update crunchy postgres images

.github/workflows/main.yaml
Implements a job to recreate the release PR whenever a merge to main is done
=> feat: workflow to create release PR on merge to main

app/components/Analyst/Project/ConditionalApproval/widgets/ReadOnlyFileWidget.tsx
Implements # 1370 
Fix for read only view
=> feat: add word break on read-only component

app/backend/lib/linkPreview.ts, app/components/Analyst/Project/Announcements/ViewAnnouncements.tsx
Bug fix for announcements link previews.
=> fix: handle links without protocol

app/backend/lib/linkPreview.ts, app/utils/getLinkPreview.ts
The link previews were infinitely waiting due to the rate limiter and/or response from the fetch when getting the preview. This change should allow enough requests in a minute, or abort the fetch if it's taking longer than 10 seconds since we fetch the preview each time the user visits/refreshes the page, adds or deletes an announcement.
=> fix: link preview increase rate, set timeout

.tool-versions, app/package.json, app/yarn.lock
Also had to update `openid-client` since the version we were using only supported up to node 16.
=> chore: update openid client to node 18 compatible version and nodejs and node types to v18.16.0

app/cypress/integration/analyst/dashboard.spec.js
Implements #1331 
This should fix that happo dashboard diff we regularly get. Looks like the screenshot just gets taken before the sorting completes sometimes.
=> fix: add cy.wait before analyst dashboard happo screenshot

app/components/Analyst/History/HistoryContent.tsx, app/components/DiffTable.tsx
Fixed RFI issue in which file information was being show for size, type, name, on the diff table. This is handled separately and should not be there.
=> fix: ignore file fields in diff table

app/components/Analyst/Project/AddButton.tsx, app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx, app/components/Analyst/Project/ChangeRequest/ChangeRequestCard.tsx, app/components/Analyst/Project/ChangeRequest/ChangeRequestForm.tsx, app/components/Analyst/Project/ChangeRequest/index.ts, app/components/Analyst/Project/ProjectForm.tsx, app/components/Analyst/Project/index.ts, app/components/DownloadLink.tsx, app/formSchema/analyst/changeRequest.ts, app/formSchema/uiSchema/analyst/changeRequestUiSchema.ts, app/pages/analyst/application/[applicationId]/project.tsx, app/schema/mutations/project/createChangeRequest.ts, app/schema/schema.graphql, app/tests/components/Analyst/Project/ChangeRequest/ChangeRequestForm.test.tsx, db/deploy/mutations/create_change_request.sql, db/deploy/tables/change_request_data.sql, db/revert/mutations/create_change_request.sql, db/revert/tables/change_request_data.sql, db/sqitch.plan, db/test/unit/mutations/create_change_request_test.sql, db/test/unit/tables/change_request_data_test.sql
- feat: add change_request_data table
- feat: add postgres mutation create_change_request
- feat: add change request json form schema and ui schema
- chore: update graphql schema
- feat: add createChangeRequest graphql mutation
- refactor: move add button to separate component
- feat: update create change request db mutation to check expected number
- chore: update graphql schema
- feat: save change request number with form
- refactor: move form animation to project form for reuse
- feat: add change request card
- feat: order by change request number
Implements #1691
=> 1691 enable change requests mvp

.github/workflows/main.yaml
Implements fix for the release action by specifying the tag version to be what release-it is attempting to commit. 
Also added the sqitch config for the ccbc service account's username and email so we don't get something like: 
`@1.69.0 2023-05-19T22:45:23Z ,,, <runner@fv-az482-816> # release v1.69.0`
The error it faced last time was due to the tag deleted and being recreated. Note that the tag for release 1.69.0 is not associated with any branch in the repository https://github.com/bcgov/CONN-CCBC-portal/commit/b3ee81ed99d6920814464b3748634398e8192120
=> fix(ci): use release-it to determine tag

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx, app/components/Analyst/Project/ProjectInformation/widgets/SowImportFileWidget.tsx, app/tests/components/Analyst/Project/ProjectInformation/ProjectInfomrationForm.test.ts
Implements # 1617
1. Moved messages to appear right below sow upload field
2. "Checking the data..." is now a fixed width to prevent it from sliding
3. The moment you upload a new file, the errors disappear rather than waiting for the vlidation to occur
4. Even if errors occur, the onChange is committed to allow for the form to still be required *and* for that file to not be valid
=> feat: cosmetic changes for sow

app/components/Analyst/Project/Announcements/Announcement.tsx
Implements #1727 
After some discussion we decided to use `object-fit: contain` which will display the full image while maintaining aspect ratio
=> feat: use object-fit: contain on announcement image preview

app/lib/helpers/useDisposeOnRouteChange.tsx, app/lib/theme/widgets/FileWidget.tsx, app/package.json, app/tests/lib/helpers/useDisposeOnRouteChange.test.tsx, app/yarn.lock
Implements # 1652
I've added a reusable hook to be able to dispose of requests made to graphql (and thus cancelling the onComplete that initiates once it ends) on a route change.
=> feat: add new hook to cancel operations on hook change

app/backend/lib/sow_import/summary_tab.ts, app/tests/backend/lib/summary_tab.test.ts
Implements #1829
This must have slipped by in a validation ticket. Since query params are all strings this made `validation = true` all the time so it wouldn't save in the database.
=> fix: sow validate query param boolean bug

app/components/SessionExpiryHandler.tsx, app/patches/@bcgov-cas+sso-express+3.2.0.patch, app/patches/@bcgov-cas+sso-react+2.0.0.patch
Implements # 1690
- Updated logout for inactivity to be handled by sso-express
- Separate session-idle-remaining and extend into their own endpoints
- session-idle will no longer refresh token to prevent countdown from 1700+
- Refresh the timeout when session is extended
=> fix: session timeout

app/lib/theme/widgets/RadioWidget.tsx
Pushing up a small fix I did when I was doing the radio button spike #1775 
Before:
After:
=> fix: radio focus border and label spacing

app/components/Analyst/Project/Announcements/Announcement.tsx, app/components/Analyst/Project/Announcements/ViewAnnouncements.tsx
=> fix: do not show self project number on announcement list

app/pages/analyst/gis/index.tsx, app/tests/pages/analyst/admin/gis-upload.test.tsx
Elliott asked me to remove this since we have the dashboard embedded on the page itself now.
=> chore: remove gis-upload metabase link

app/formSchema/analyst/projectInformation.ts
=> chore: allow project information save only with date signed set

db/data/dev/001_intake.sql
Implements fix where creating an intake produces an error in deev data. @marcellmueller
=> fix: set the sequence value to match what is set on override

app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx, app/tests/pages/analyst/application/[applicationId]/project.test.tsx
=> sow spinner and success toast should not show when SOW validation has failed

app/components/Review/fields/ReviewFieldTemplate.tsx
=> fix: rfi files not showing on application page field that has no value error

README.md, app/backend/lib/awsCommon.ts, app/config/index.js, app/config/prod.json, app/config/test.json
Adds a new env var called `ENABLE_AWS_LOGS` which is set to true by default in `test` and `prod`.
Implements #255
=> 2055 suppress aws logs

app/backend/lib/claims-upload.ts, app/backend/lib/community-report-upload.ts, app/backend/lib/excel_import/excel-limiter.ts, app/backend/lib/sow-upload.ts
Increased the limit to 20 connections per IP per minute, which seems like a lot though the reason we were maxing out our 5 during testing is that we hit the API twice per upload, once to validate and the second to save. By the time we would get to saving our third excel file we would be at the limit of 5, so it would timeout and hang on save.
10 uploads per minute should be more than enough as it would be hard to hit even intentionally. 
Implements #2092
=> chore: increase excel api rate limit

app/components/Analyst/Project/Claims/ClaimsView.tsx
Fix for dates overlapping claims excel file name due to increased width from year being added.
=> fix: claims from year width overlap

app/cypress/integration/analyst/application/[applicationId]/project.spec.js
Increasing the timeout for excel upload tests. This doesn't add to the total time of the test unlike `cy.wait`, just gives more breathing room before it fails due to runners being slow.
=> test: increase project test excel api route timeout

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
Fix for the fiscal year validation error showing when editing a community progress report. The warning was showing since it was including the fiscal year from the report being edited.
The warning will still show up when editing if another report exists that is using the same fiscal quarter.
=> fix: fiscal year warning showing up while editing community report

app/components/Analyst/Project/ProjectForm.tsx
Turns out the login timeout modal z-index was also 100 so they were both conflicting.
=> fix: project page z-index modal conflict

app/components/Analyst/EditProjectDescription.tsx, app/postgraphile.tags.json5, app/schema/mutations/application/createApplicationInternalDescription.ts, app/schema/schema.graphql, app/tests/components/Analyst/EditProjectDescription.test.tsx, db/deploy/computed_columns/application_internal_description.sql, db/deploy/mutations/create_application_internal_description.sql, db/deploy/tables/application_internal_description.sql, db/revert/computed_columns/application_internal_description.sql, db/revert/mutations/create_application_internal_description.sql, db/revert/tables/application_002_add_internal_description.sql, db/revert/tables/application_internal_description.sql, db/sqitch.plan, db/test/unit/computed_columns/application_internal_description_test.sql, db/test/unit/mutations/create_application_internal_description_test.sql, db/test/unit/tables/application_internal_description_test.sql, db/test/unit/tables/application_test.sql
PR to save `internal_description` in its own table instead of the `application` table so we can better track history of changes.
Implements #2376
=> 2376 project description table

app/components/Form/ApplicationForm.tsx
Implements # 1379 fix for incorrect  keys associated with
=> fix: use the correct keys for returned data

helm/app/values-dev.yaml
Sets dev schedule to only run once every year.
=> chore: set dev cronsp to once a year

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx, app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
Fixes for a few sorting and filtering issues. 
- The `CCBC ID` column filtering will not return any value that contains an `01` anymore if you type say `ccbc-01`, it will return all values that start with `ccbc-01`.
- All four assessment columns sorting and filtering is fixed. This was due to the value being an object since it has the custom dropdown for editing so by default the sorting/filtering was broken as it didn't know which values to look for.
=> fix: add custom sorting for assessment table analysts

helm/app/templates/deployment.yaml, helm/app/values-prod.yaml, helm/app/values.yaml
Implements #2157 
Note: also updating the HPAs so that the app is not always scaling as soon as one user starts using the app as it based on the `requests` of the cpu. Set to 200% on prod and 400% on dev/test, so it will auto scale when CPU usage gets around 40m on all environments.
=> chore: update resources and hpa

app/pages/applicantportal/dashboard.tsx
Implements fix for being able to create multiple applications while on the applicant dashboard.
The offending area lies in the fact that the [page] is not cached (since it is dynamic), and so if there is a slow connection to the pod that is serving this chunk/page the application will allow you hit the Create Application multiple times. 
The fix here is that, if an application has been created then the button is disabled and a user cannot hit the button multiple times. The problem is that there is nothing else to communicate to the user that something is loading until the browser attempts to load the page/chunk.
=> fix: do not allow applicant to click create application multiple times

app/components/Analyst/Project/CommunityProgressReport/CommunityProgressReportForm.tsx
Implements # 2328 comment for not showing metabase link while in edit mode
=> feat: metabase link is not visible while in edit mode

app/next.config.js, app/tests/backend/lib/lastIntake.test.ts
we are not using tunnel route in our sentry config, but setting it to undefined anyways as it is currently not possible to upgrade
=> chore: set tunnel route to undefined

app/components/Dashboard/Modal.tsx
Implements #2613 
Change withdrawal modal description to fix typo `Connection` to `Connected`
=> fix: change withdrawal modal description

app/components/Admin/Intake.tsx, app/tests/pages/analyst/admin/application-intakes.test.tsx
Implements # [NDT-41](https://connectivitydivision.atlassian.net/browse/NDT-41)
Intake edit and delete functionality fixed with time machine
[NDT-41]: https://connectivitydivision.atlassian.net/browse/NDT-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: intake edit and delete with time machine

app/components/Review/widgets/FileWidget.tsx
Implements NED-17 fix
Uses a better key for the StyledFile and adds a key on the fragment
=> fix: use unique key on StyledFile and for Fragment

app/components/Dashboard/Modal.tsx
Implements #[NDT-50](https://connectivitydivision.atlassian.net/browse/NDT-50)
Changed withdrawal modal wording from `connected` to `connecting`
[NDT-50]: https://connectivitydivision.atlassian.net/browse/NDT-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: withdrawal modal typo

app/components/AnalystDashboard/AssessmentAssignmentTable.tsx
Implements #[NDT-13](https://connectivitydivision.atlassian.net/browse/NDT-13)
changed status type criteria to --> `analystStatus`
removed status `recommendation` from list
010002, 0100003 and 010077 are shown now, but 010004 or 010041 are not shown since its in `recommendation`
[NDT-13]: https://connectivitydivision.atlassian.net/browse/NDT-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: incorrect status type criteria in assessment table

app/components/Analyst/History/HistoryContent.tsx, app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx, app/components/Analyst/Project/ProjectInformation/ReadOnlyView.tsx, app/cypress/e2e/analyst/application/[applicationId]/history.cy.js, app/formSchema/analyst/changeRequest.ts, app/formSchema/analyst/projectInformation.ts, app/formSchema/uiSchema/analyst/changeRequestUiSchema.ts, app/formSchema/uiSchema/analyst/projectInformationUiSchema.ts, app/tests/components/Analyst/Project/ProjectInformation/ProjectInformationForm.test.ts
Implements [#NDT-51](https://connectivitydivision.atlassian.net/browse/NDT-51)
✅On Analyst portal, the kmz upload for signed agreement is now a multifile upload, and should operate the same way as other multifile uploads in the portal
✅Update wording for Map upload as per screen design
✅Update wording in history to reflect wording change for the map upload
✅update map upload in change request to a multiple upload as well
=> chore: making a spatial data upload a multiple upload

app/components/Form/ApplicationForm.tsx
disable or enables the submit button on the form if the project area is fn led and has any zone, or if not fn led then it must be based on the zones selected on growthbook
Implements [NDT-63]
[NDT-63]: https://connectivitydivision.atlassian.net/browse/NDT-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: disable/enable submit based on project area data

app/components/Form/ApplicationForm.tsx, app/lib/theme/widgets/custom/ReadOnlySubmissionWidget.tsx, app/tests/pages/applicantportal/form/[page].test.tsx
Implements #[NDT-55](https://connectivitydivision.atlassian.net/browse/NDT-55)
✅ If applicant has not clicked Yes to the FN question on Project area page and they have not selected one of the zones (1,2,3,6) then display text in red bold:  
✅ Update the logic for the modal so that it operates with the FN question
[NDT-55]: https://connectivitydivision.atlassian.net/browse/NDT-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update submission page warning for zone selection

app/components/Dashboard/Row.tsx, app/components/Dashboard/Table.tsx, app/components/Form/ApplicationForm.tsx, app/pages/applicantportal/dashboard.tsx, app/tests/components/Dashboard/Dashboard.test.tsx, app/tests/pages/applicantportal/dashboard.test.tsx, app/utils/schemaUtils.ts
Implements fix for NDT-89 and also NDT-91, the crux of the issue is that the current updateApplicationForm query doesn't trigger the out of sync error if the user is on the same page. The change I made here is to consistently return the correct page, thus reducing the chance of the out of sync error happening erroneously. 
I explored other options, one that I believe would solve this issue without needing to use a sync-check on the database is to use the subscription feature of graphQL and adding a subscription to the formData on this page. The work required for that though, I believe, is of far greater scope than what I believe this ticket intended so I went with this approach.
=> fix: use filteredUiSchema to give correct lastEditedPage

app/components/Form/ApplicationForm.tsx
This turns the acknowledgeIncomplete into a state as sometimes it will have stale data at the submission page and would cause the submit button to be disabled until page refresh/reloading the application
Fixes [NDT-95]
[NDT-95]: https://connectivitydivision.atlassian.net/browse/NDT-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: submit disabled on some cases

.github/renovate.json
=> chore: disable immortal prs on renovate

app/components/Analyst/History/HistoryFile.tsx, app/tests/pages/analyst/application/[applicationId]/history.test.tsx
Implements fix for history page, problem occured as the docs doesn't explicitly state that scalar values aren't included in "keepUnchangedValues"
=> fix: use 'full' option to include unchanged value

app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx
Tests were being flakey due to some timeouts and the changes to the table (it looks like), removed async from zone to make it more consistent and increase timeout to 5000ms just in case.
=> test: fix assessment assignment table flaky tests

app/components/AnalystDashboard/AssessmentLead.tsx
Implements [NDT-184]
[NDT-184]: https://connectivitydivision.atlassian.net/browse/NDT-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: 2nd review colour not showing on assessment dash

app/data/externalConstants.ts, app/lib/theme/widgets/custom/ReadOnlyProjectAreaWidgetIntakeFour.tsx
Implements [NDT-286](https://connectivitydivision.atlassian.net/browse/NDT-286)
[NDT-286]: https://connectivitydivision.atlassian.net/browse/NDT-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: datacatalog url in area widget

db/deploy/clean_application_status.sql, db/revert/clean_application_status.sql, db/sqitch.plan
Archives lingering rows of the application status table that were not archived as they were created before the auto archiving function was created, leaves behind the two latest application status one for analyst and one for applicant.
Implements [NDT-270]
[NDT-270]: https://connectivitydivision.atlassian.net/browse/NDT-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cleanup unarchived application status

db/test/unit/computed_columns/application_history_test.sql
Uncomments using the mock time which for some reason was commented out, allowing tests to pass
=> chore: update applciation_history_test to use mock time

app/backend/lib/emails/templates/agreementSignedStatusChange.ts, app/backend/lib/emails/templates/agreementSignedStatusChangeDataTeam.ts
Implements [NDT-267] fix to only show first name
[NDT-267]: https://connectivitydivision.atlassian.net/browse/NDT-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: only use first name on e-mail

app/components/Analyst/Project/fields/ProjectFieldTemplate.tsx
adds a condition to check for the existence of the label or title before turning it into a string, otherwise null is returned so the h4 is not rendered. It was causing unintended "undefined" to be shown as labels on conditional approval
Implements [NDT-]
=> fix: undefined project labels

app/components/AnalystDashboard/AllDashboard.tsx
Implements [NDT-356]
[NDT-356]: https://connectivitydivision.atlassian.net/browse/NDT-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: filter on all dashboard due to undefined intake

app/backend/lib/emails/email.ts, app/backend/lib/emails/templates/rfiCoverageMapKmzUploaded.ts, app/components/Analyst/RFI/RFIAnalystUpload.tsx, app/lib/helpers/useRfiCoverageMapKmzUploadedEmail.ts, app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx, app/tests/backend/lib/emails/email.test.ts, app/tests/backend/lib/emails/templates/rfiCoverageMapKmzUploaded.test.ts, app/tests/components/Analyst/RFI/RFIAnalystUpload.test.ts, app/tests/lib/helpers/useRfiCoverageMapKMZUploadedEmail.test.ts, app/tests/pages/applicantportal/form/[id]/rfi/[applicantRfiId].test.tsx
Implements [NDT-305]
[NDT-305]: https://connectivitydivision.atlassian.net/browse/NDT-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: notify analyst when coverage kmz uploaded

app/components/Analyst/RFI/RFIAnalystUpload.tsx, app/components/AppProvider.tsx, app/components/Toast.tsx, app/lib/theme/widgets/FileWidget.tsx, app/pages/_app.tsx, app/tests/components/Analyst/RFI/RFIAnalystUpload.test.ts, app/tests/components/Form/FileWidget.test.tsx, app/tests/utils/componentTestingHelper.tsx, app/tests/utils/pageTestingHelper.tsx
Implements [[NDT-232](https://connectivitydivision.atlassian.net/browse/NDT-232)]
[NDT-232]: https://connectivitydivision.atlassian.net/browse/NDT-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add toast after file upload RFI template 1 and 2

helm/app/templates/cronJobs/prepare-download.yaml
Noticed the ccbc-prepare-download was failing as it was missing curl since we are now using a sqitch only image, changing image to use alpine curl and update command to use sh instead of bash. Tested on test manually.
Implements [NDT-]
=> fix: ccbc-prepare-download

.github/workflows/clean-feature-env.yaml, .github/workflows/deploy_feature.yaml
=> fix: feature db name to match release name

CHANGELOG.md, db/deploy/tables/cbc_application_pending_change_request_001_service_account.sql, db/revert/tables/cbc_application_pending_change_request_001_service_account.sql, db/sqitch.plan, package.json
Fixes the error on the import of cbc data by the cron job by granting access to the cbc_application_pending_change_request table to the ccbc_service_account so the graphql query and mutation can succeed after initial import.
Implements [NDT-423]
[NDT-423]: https://connectivitydivision.atlassian.net/browse/NDT-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: grant service account to cbc change request table

helm/app/values-dev.yaml
reduce the retention in dev as the db is getting pretty big due to multiple feature envs and running out of backup storage
Implements [NDT-]
=> chore: reduce retention in dev

app/components/Table/Pagination.tsx, app/package.json, app/tests/components/Table/Pagination.test.tsx, app/yarn.lock
Implements [[NDT-365](https://connectivitydivision.atlassian.net/browse/NDT-365)]
[NDT-365]: https://connectivitydivision.atlassian.net/browse/NDT-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update dependency for MUI

CHANGELOG.md, db/deploy/tables/communities_source_data_001_service_account.sql, db/revert/tables/communities_source_data_001_service_account.sql, db/sqitch.plan, package.json
=> fix: sa permission for communities source data

CHANGELOG.md, db/sqitch.plan, helm/app/values.yaml, package.json
=> chore: remove pgbackrest image

CHANGELOG.md, app/backend/lib/emails/templates/assesmentSecondReviewChange.ts, app/backend/lib/emails/templates/assessmentAssigneeChange.ts, app/components/AnalystDashboard/AssessmentAssignmentTable.tsx, app/data/assessmentTypes.ts, app/schema/schema.graphql, app/tests/backend/lib/emails/templates/assessmentAssigneeChange.test.ts, db/deploy/computed_columns/application_assessment_notifications.sql, db/revert/computed_columns/application_assessment_notifications.sql, db/sqitch.plan, package.json
Implements [[NDT-421](https://connectivitydivision.atlassian.net/browse/NDT-421)]
[NDT-421]: https://connectivitydivision.atlassian.net/browse/NDT-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: enable financial Risk assessments to notifiy assignees

CHANGELOG.md, app/pages/analyst/application/[applicationId]/edit/[section].tsx, db/sqitch.plan, package.json
Implements [[NDT-528](https://connectivitydivision.atlassian.net/browse/NDT-528)]
[NDT-528]: https://connectivitydivision.atlassian.net/browse/NDT-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: validation with correct schema for analyst application edit

CHANGELOG.md, app/components/Analyst/NavigationSidebar.tsx, db/sqitch.plan, package.json
Implements [[NDT-504](https://connectivitydivision.atlassian.net/browse/NDT-504)]
[NDT-504]: https://connectivitydivision.atlassian.net/browse/NDT-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add a margin to left side nav

CHANGELOG.md, app/backend/lib/gis-upload.ts, app/package.json, app/pages/analyst/gis/index.tsx, app/tests/backend/lib/gis-upload.test.ts, app/yarn.lock, db/sqitch.plan, package.json
Implements [[NDT-458](https://connectivitydivision.atlassian.net/browse/NDT-458)]
[NDT-458]: https://connectivitydivision.atlassian.net/browse/NDT-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: correct line number for GIS import

CHANGELOG.md, app/backend/lib/emails/templates/assessmentAssigneeChange.ts, app/components/AnalystDashboard/AssessmentAssignmentTable.tsx, app/tests/backend/lib/emails/templates/assessmentAssigneeChange.test.ts, db/sqitch.plan, package.json
Implements [[NDT-351](https://connectivitydivision.atlassian.net/browse/NDT-351)]
[NDT-351]: https://connectivitydivision.atlassian.net/browse/NDT-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ndt 351 email notification system for analysts assigned to screening assessments

.github/workflows/release-process.yaml, CHANGELOG.md, db/sqitch.plan, package.json
Implements [[NDT-545](https://connectivitydivision.atlassian.net/browse/NDT-545)]
this is for some cases which could fail the auto merge step, which could result in running make release step again. This is a quick fix for eliminating that scenario
[NDT-545]: https://connectivitydivision.atlassian.net/browse/NDT-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: errorneous cases of auto enable

CHANGELOG.md, app/components/AnalystDashboard/AssignmentEmailModal.tsx, app/components/LoadingSpinner.tsx, app/components/Modal.tsx, app/tests/components/AnalystDashboard/AssessmentAssignmentTable.test.tsx, db/sqitch.plan, package.json
Implements [[NDT-471](https://connectivitydivision.atlassian.net/browse/NDT-471)]
[NDT-471]: https://connectivitydivision.atlassian.net/browse/NDT-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add success and failure toasts

CHANGELOG.md, app/backend/lib/emails/email.ts, app/backend/lib/emails/templates/notifySowUpload.ts, app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx, app/pages/analyst/application/[applicationId]/project.tsx, app/tests/backend/lib/emails/email.test.ts, app/tests/backend/lib/emails/templates/notifySowUpload.test.ts, app/tests/components/Analyst/Project/ProjectInformation/ProjectInformationForm.test.ts, db/sqitch.plan, package.json
Implements [[NDT-498](https://connectivitydivision.atlassian.net/browse/NDT-498)]
[NDT-498]: https://connectivitydivision.atlassian.net/browse/NDT-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: email notification when latest sow upload

CHANGELOG.md, app/backend/lib/sow_import/tab_7.ts, app/tests/backend/lib/sow_tab_7.test.ts, db/sqitch.plan, package.json
Implements [NDT-583]
[NDT-583]: https://connectivitydivision.atlassian.net/browse/NDT-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sow tab 7 total estimated project cost not importing

CHANGELOG.md, app/formSchema/analyst/cbc/eventsAndDates.ts, app/formSchema/analyst/summary/eventsAndDates.ts, app/formSchema/uiSchema/cbc/eventsAndDatesUiSchema.ts, app/formSchema/uiSchema/summary/eventsAndDatesUiSchema.ts, db/sqitch.plan, package.json
Implements [NDT-560]
[NDT-560]: https://connectivitydivision.atlassian.net/browse/NDT-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change title display for announcedByProvince in summary

CHANGELOG.md, app/backend/lib/emails/handleEmailNotification.ts, app/backend/lib/emails/templates/notifyMilestoneReportDue.ts, app/backend/lib/milestoneDueDate.ts, app/server.ts, app/tests/backend/lib/emails/templates/notifyMilestoneReportDue.test.ts, app/tests/backend/lib/milestoneDueDate.test.ts, cron/sp/app.mjs, db/deploy/grant_read_access_to_service_account.sql, db/revert/grant_read_access_to_service_account.sql, db/sqitch.plan, helm/app/templates/cronJobs/trigger-milestone-notification.yaml, helm/app/values.yaml, package.json
Implements [NDT-362]
[NDT-362]: https://connectivitydivision.atlassian.net/browse/NDT-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: notification to analysts when upcoming milestone is due

CHANGELOG.md, app/components/Admin/AddAnalyst.tsx, app/components/Analyst/Assessments/AssessmentsForm.tsx, app/components/Analyst/Project/ProjectForm.tsx, app/components/Analyst/Project/ProjectInformation/ProjectInformationForm.tsx, app/components/Analyst/RFI/RfiForm.tsx, app/components/AppProvider.tsx, app/components/ButtonLink.tsx, app/components/Form/ApplicationForm.tsx, app/components/Form/FormBase.tsx, app/components/Modal/UnsavedChangesWarningModal.tsx, app/components/NavLoginForm.tsx, app/components/UnsavedChangesProvider.tsx, app/formSchema/admin/analyst.ts, app/formSchema/uiSchema/admin/analystUiSchema.ts, app/pages/analyst/cbc/[cbcId].tsx, app/pages/analyst/cbc/[cbcId]/edit/[section].tsx, app/pages/analyst/gis/coverages.tsx, app/pages/analyst/gis/index.tsx, app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx, app/tests/components/Form/UnsavedChangesWarning.test.tsx, app/tests/jest-setup.ts, app/tests/pages/analyst/admin/list-of-analyst.test.tsx, app/tests/utils/componentTestingHelper.tsx, app/tests/utils/formTestRenderer.tsx, app/tests/utils/pageTestingHelper.tsx, app/utils/getFormState.ts, db/sqitch.plan, package.json
Implements [[NDT-515](https://connectivitydivision.atlassian.net/browse/NDT-515)]
[NDT-515]: https://connectivitydivision.atlassian.net/browse/NDT-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add unsaved changes warning modal to forms

CHANGELOG.md, db/deploy/tables/application_form_template_9_data_001_add_missing_roles.sql, db/revert/tables/application_form_template_9_data_001_add_missing_roles.sql, db/sqitch.plan, package.json
Implements [NDT-585]
[NDT-585]: https://connectivitydivision.atlassian.net/browse/NDT-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add missing access to app template 9 table

CHANGELOG.md, app/components/AnalystDashboard/AllDashboard.tsx, app/tests/pages/analyst/dashboard.test.tsx, db/sqitch.plan, package.json
Implements [[NDT-537](https://connectivitydivision.atlassian.net/browse/NDT-537)]
[NDT-537]: https://connectivitydivision.atlassian.net/browse/NDT-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: make cbc projects filter/sort by analyst status

CHANGELOG.md, cron/sp/app.mjs, db/sqitch.plan, package.json
Implements [NDT-557]
[NDT-557]: https://connectivitydivision.atlassian.net/browse/NDT-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add exit code on error

CHANGELOG.md, app/components/Analyst/CBC/History/CbcHistoryContent.tsx, app/components/Analyst/CBC/History/CbcHistoryRow.tsx, app/components/Analyst/CBC/History/CbcHistoryTable.tsx, app/components/Analyst/History/HistoryFilter.tsx, app/components/Analyst/History/HistoryTable.tsx, app/components/Analyst/History/index.ts, app/formSchema/analyst/historyFilter.ts, app/formSchema/analyst/index.ts, app/formSchema/uiSchema/history/historyFilterUiSchema.ts, app/lib/theme/widgets/MultiSelectWidget.tsx, app/lib/theme/widgets/index.ts, app/tests/pages/analyst/application/[applicationId]/history.test.tsx, app/utils/formatString.ts, db/sqitch.plan, package.json
Implements [[NDT-488](https://connectivitydivision.atlassian.net/browse/NDT-488)]
[NDT-488]: https://connectivitydivision.atlassian.net/browse/NDT-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add type and user filters to history page

.github/actions/app/action.yaml, .github/actions/dev-env-setup/action.yml, .github/actions/feature/action.yaml, .github/actions/hotfix/action.yaml, .github/actions/s3-backup/action.yaml, .github/workflows/clean-dev-env-jobs.yaml, .github/workflows/clean-feature-env.yaml, .github/workflows/deploy_feature.yaml, .github/workflows/deploy_tools_chart.yaml, .github/workflows/refresh-pods.yaml, .github/workflows/test-checks.yaml
Implements [[NDT-668](https://connectivitydivision.atlassian.net/browse/NDT-668)]
[NDT-668]: https://connectivitydivision.atlassian.net/browse/NDT-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ubuntu latest breaks

CHANGELOG.md, app/components/Reporting/ManageReports.tsx, app/components/Reporting/ReportRow.tsx, app/components/Reporting/Tabs.tsx, app/pages/analyst/reporting/manage-reports.tsx, app/schema/mutations/reporting/archiveReportingGcpeMutation.ts, app/tests/pages/analyst/reporting/manage-reports.test.tsx, db/sqitch.plan, package.json
Implements [[NDT-495](https://connectivitydivision.atlassian.net/browse/NDT-495)]
[NDT-495]: https://connectivitydivision.atlassian.net/browse/NDT-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add manage reports page

CHANGELOG.md, app/components/Analyst/ApplicationHeader.tsx, app/components/Analyst/CBC/CbcHeader.tsx, app/components/Analyst/CBC/CbcStatusInformation.tsx, app/components/Analyst/CcbcStatusInformation.tsx, app/components/Analyst/StatusInformationIcon.tsx, app/components/Analyst/StatusInformationModal.tsx, app/components/AnalystDashboard/AllDashboard.tsx, db/sqitch.plan, package.json
Implements [[NDT-586](https://connectivitydivision.atlassian.net/browse/NDT-586)]
[NDT-586]: https://connectivitydivision.atlassian.net/browse/NDT-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add cbc infographic to all dashboard

CHANGELOG.md, app/components/Analyst/PendingChangeRequest/ClosePendingRequestModal.tsx, app/components/Analyst/PendingChangeRequest/PendingChangeRequest.tsx, app/components/Analyst/PendingChangeRequest/PendingChangeRequestModal.tsx, db/sqitch.plan, package.json
Implements [[NDT-681](https://connectivitydivision.atlassian.net/browse/NDT-681)]
[NDT-681]: https://connectivitydivision.atlassian.net/browse/NDT-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove unwanted unsaved change modal

CHANGELOG.md, app/lib/helpers/ccbcSummaryGenerateFormData.ts, app/tests/pages/analyst/application/[applicationId]/summary.test.tsx, app/utils/ccbcCustomValidator.ts, db/sqitch.plan, package.json
Implements [NDT-600]
[NDT-600]: https://connectivitydivision.atlassian.net/browse/NDT-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: counts summary page show reason for blanks on fields

CHANGELOG.md, app/components/AnalystDashboard/AllDashboard.tsx, app/tests/pages/analyst/dashboard.test.tsx, package.json
Implements [[NDT-731](https://connectivitydivision.atlassian.net/browse/NDT-731)]
[NDT-731]: https://connectivitydivision.atlassian.net/browse/NDT-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: enable global filter modes

CHANGELOG.md, app/backend/lib/excel_import/template_nine.ts, app/lib/theme/widgets/FileWidget.tsx, app/pages/applicantportal/form/[id]/rfi/[applicantRfiId].tsx, app/schema/mutations/application/updateFormRfiAndCreateTemplateNineDataMutation.ts, app/schema/mutations/application/updateRfiAndCreateTemplateNineDataMutation.ts, app/schema/mutations/application/updateRfiAndFormDataMutation.ts, app/schema/schema.graphql, app/tests/backend/lib/excel_import/template_nine.test.ts, app/tests/components/Form/FileWidget.test.tsx, app/tests/pages/applicantportal/form/[id]/rfi/[applicantRfiId].test.tsx, db/deploy/mutations/create_or_update_application_form_template_9_data.sql, db/deploy/tables/application_form_template_9_data_002_add_auth_user_role_permission.sql, db/revert/mutations/create_or_update_application_form_template_9_data.sql, db/revert/tables/application_form_template_9_data_002_add_auth_user_role_permission.sql, db/sqitch.plan, package.json
Implements [NDT-740]
[NDT-740]: https://connectivitydivision.atlassian.net/browse/NDT-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update data when applicant uploads template 9

CHANGELOG.md, app/components/Analyst/Project/Announcements/AnnouncementsForm.tsx, package.json
Implements [[NDT-1018](https://connectivitydivision.atlassian.net/browse/NDT-1018)]
[NDT-1018]: https://connectivitydivision.atlassian.net/browse/NDT-1018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: announcement not updating checkbox state on navigation
